Repository planetarium/lib9c, pull requests merged in 2022-12, with the labels that each got.

#1550 🗃️ [PBFT] Updated policy for testing
  Lib9c/Policy/BlockPolicySource.cs
  Lib9c/Policy/ValidatorsPolicy.cs
Labels: Extra Small

#1552 🗃️ [PBFT] Changed to use smaller set of validators
  Lib9c/Policy/BlockPolicySource.cs
Labels: Extra Small

#1553 🧹 [PBFT] Policy cleanup
  .Lib9c.Benchmarks/Program.cs
  .Lib9c.Tests/Policy/BlockPolicyTest.cs
  Lib9c/Policy/BlockPolicySource.cs
  Lib9c/Policy/PermanentBlockPolicySource.cs
  Lib9c/Policy/ValidatorsPolicy.cs
Labels: Medium

#1557 🗃️ [PBFT] Updated policy for pbft-pow
  Lib9c/Policy/MinBlockProtocolVersionPolicy.cs
Labels: Extra Small

#1558 🗃️ [PBFT] Updated policy for pbft
  Lib9c/Policy/ValidatorsPolicy.cs
Labels: Extra Small

#1561 ♻️ [PBFT] Changes to allow Unity client development
  Lib9c.Miner/Miner.cs
  Lib9c/Policy/BlockPolicySource.cs
  Lib9c/Policy/DebugPolicy.cs
Labels: Extra Small

#1563 🧹 [PBFT] Policy cleanup
  Lib9c.Miner/Miner.cs
  Lib9c/Policy/DebugPolicy.cs
Labels: Extra Small

#1564 🧹 [PBFT] Fixed unity editor code under directive
  Lib9c/Policy/BlockPolicySource.cs
Labels: Extra Small

#1562 Fix icon resource column
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
Labels: Extra Small

#1565 Fix rune ticker
  Lib9c/TableCSV/RuneSheet.csv
Labels: Extra Small

#1539 Winter dungeon draft
  Lib9c/TableCSV/Event/EventConsumableItemRecipeSheet.csv
  Lib9c/TableCSV/Event/EventDungeonSheet.csv
  Lib9c/TableCSV/Event/EventDungeonStageSheet.csv
  Lib9c/TableCSV/Event/EventDungeonStageWaveSheet.csv
  Lib9c/TableCSV/Event/EventScheduleSheet.csv
  Lib9c/TableCSV/Item/ConsumableItemSheet.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
Labels: Medium

#1571 Update Event Dungeon BGM & Boss info Change
  Lib9c/TableCSV/Event/EventDungeonStageSheet.csv
  Lib9c/TableCSV/Event/EventDungeonStageWaveSheet.csv
Labels: Extra Small

#1573 Apply damage reduction rate in permyriad
  Lib9c/Model/Skill/AttackSkill.cs
  Lib9c/Model/Stat/Stats.cs
Labels: Extra Small

#1572 Update Golden leaf Rune Skill Value Change
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
Labels: Extra Large

#1574 Exception handling for arena actions
  .Lib9c.Tests/Action/BattleArena6Test.cs
  .Lib9c.Tests/Action/BattleArena7Test.cs
  .Lib9c.Tests/Action/JoinArena0Test.cs
  Lib9c/Action/BattleArena6.cs
  Lib9c/Action/JoinArena0.cs
  Lib9c/Policy/BlockPolicySource.cs
Labels: bug, Extra Small

#1413 Update RedeemRewardSheet (for Arena Championship)
  Lib9c/TableCSV/RedeemRewardSheet.csv
Labels: Extra Small

#1579 100340 backmerge development
  .Lib9c.Tests/Action/BattleArena6Test.cs
  .Lib9c.Tests/Action/BattleArena7Test.cs
  .Lib9c.Tests/Action/JoinArena0Test.cs
  Lib9c/Action/BattleArena6.cs
  Lib9c/Action/JoinArena0.cs
  Lib9c/Action/PatchTableSheet.cs
  Lib9c/Model/Skill/AttackSkill.cs
  Lib9c/Model/Stat/Stats.cs
  Lib9c/Policy/BlockPolicySource.cs
  Lib9c/TableCSV/GameConfigSheet.csv
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/RuneCostSheet.csv
  Lib9c/TableCSV/RuneSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
Labels: Small

#1582 Turn on `TreatWarningsAsErrors` feature
  Lib9c.MessagePack/Action/NCActionEvaluation.cs
  Lib9c.MessagePack/Formatters/ExceptionFormatter.cs
  Lib9c.MessagePack/Formatters/NCActionFormatter.cs
  Lib9c.MessagePack/Formatters/NineChroniclesResolver.cs
  Lib9c.MessagePack/Formatters/NineChroniclesResolverGetFormatterHelper.cs
  Lib9c.MessagePack/Lib9c.MessagePack.csproj
  Lib9c.Miner/Lib9c.Miner.csproj
  Lib9c.Miner/Miner.cs
  Lib9c.Miner/ReorgMiner.cs
Labels: Extra Small

#1584 ci(gh-actions): upgrade actiosn used node12
  .github/workflows/main.yml
  .github/workflows/publish.yml
Labels: ci, Extra Small

#1577 Update Table Sheet for the winter event dungeon
  Lib9c/TableCSV/Event/EventConsumableItemRecipeSheet.csv
  Lib9c/TableCSV/Event/EventDungeonSheet.csv
  Lib9c/TableCSV/Event/EventDungeonStageSheet.csv
  Lib9c/TableCSV/Event/EventDungeonStageWaveSheet.csv
  Lib9c/TableCSV/Event/EventScheduleSheet.csv
  Lib9c/TableCSV/Item/ConsumableItemSheet.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
Labels: Medium

#1586 Update SweepCP Decrease Data
  .Lib9c.Tests/Action/HackAndSlashSweep3Test.cs
  .Lib9c.Tests/Action/HackAndSlashSweep4Test.cs
  .Lib9c.Tests/Action/HackAndSlashSweep5Test.cs
  .Lib9c.Tests/Action/HackAndSlashSweep6Test.cs
  .Lib9c.Tests/Action/HackAndSlashSweep7Test.cs
  .Lib9c.Tests/Action/HackAndSlashSweep8Test.cs
  Lib9c/TableCSV/SweepRequiredCPSheet.csv
Labels: Extra Large

#1576 Update Rune Cost Change
  Lib9c/TableCSV/RuneCostSheet.csv
Labels: Extra Large

#1593 Fix url of genesis block in test
  .Lib9c.Tests/Action/RewardGoldTest.cs
Labels: bug, Extra Small

#1594 🔧 [PBFT] Updated validators policy
  Lib9c/Policy/BlockPolicySource.cs
  Lib9c/Policy/ValidatorsPolicy.cs
Labels: Extra Small

#1599 Fix ActionRenderer not to cast SystemAction
  Lib9c/Renderer/ActionRenderer.cs
Labels: Small

#1603 Update v100350 New Data
  Lib9c/TableCSV/Event/EventConsumableItemRecipeSheet.csv
  Lib9c/TableCSV/Event/EventScheduleSheet.csv
  Lib9c/TableCSV/Item/ConsumableItemSheet.csv
  Lib9c/TableCSV/Item/CostumeStatSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
Labels: Extra Small

#1585 Introduce test-only action: Faucet
  .Lib9c.DevExtensions.Tests/Action/FaucetCurrencyTest.cs
  .Lib9c.DevExtensions.Tests/Action/FaucetRuneTest.cs
  .Lib9c.DevExtensions.Tests/Data/TableCSV/Cost/EnhancementCostSheet.csv
  .Lib9c.DevExtensions.Tests/Data/TableCSV/GameConfigSheet.csv
  .Lib9c.DevExtensions.Tests/Lib9c.DevExtensions.Tests.csproj
  .Lib9c.Tests/TableSheetsImporter.cs
  Lib9c.DevExtensions/Action/Factory/FaucetFactory.cs
  Lib9c.DevExtensions/Action/FaucetCurrency.cs
  Lib9c.DevExtensions/Action/FaucetRune.cs
  Lib9c.DevExtensions/Action/Interface/IFaucetCurrency.cs
  Lib9c.DevExtensions/Action/Interface/IFaucetRune.cs
  Lib9c/Lib9c.csproj
  Lib9c/Model/Faucet/FaucetRuneInfo.cs
Labels: enhancement, Extra Large, hardfork

#1604 Update Character Level New Data - exp need
  Lib9c/TableCSV/Character/CharacterLevelSheet.csv
Labels: Large

#1610 Revert 551e0b8 to accept path from another projects
  .Lib9c.Tests/TableSheetsImporter.cs
Labels: bug, Extra Small

#1614 Fix `TableSheetsImporter`
  .Lib9c.DevExtensions.Tests/Action/FaucetCurrencyTest.cs
  .Lib9c.DevExtensions.Tests/Action/FaucetRuneTest.cs
  .Lib9c.DevExtensions.Tests/TableSheetsImporter.cs
  .Lib9c.Tests/TableSheetsImporter.cs
Labels: Small

#1613 Fix exception message
  Lib9c/Helper/Validator.cs
Labels: Extra Small

#1617 Add faucet actions to Lib9c
  .Lib9c.DevExtensions.Tests/Action/FaucetCurrencyTest.cs
  .Lib9c.DevExtensions.Tests/Action/FaucetRuneTest.cs
  Lib9c/Action/Factory/FaucetFactory.cs
  Lib9c/Action/FaucetCurrency.cs
  Lib9c/Action/FaucetRune.cs
  Lib9c/Action/Interface/IFaucetCurrency.cs
  Lib9c/Action/Interface/IFaucetRune.cs
  Lib9c/Lib9c.csproj
Labels: enhancement, Medium
