Repository planetarium/lib9c, pull requests merged in 2022-06, with the labels that each got.

#1090 Merge `features/stake` to `2022q2`
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  Lib9c/Action/ClaimStakeReward.cs
Labels: Extra Small

#1094 Add meta file of CrystalFluctuationSheet.csv
  Lib9c/TableCSV/Crystal/CrystalFluctuationSheet.csv.meta
Labels: Extra Small

#1095 arena previenet data fixed
  .Lib9c.Tests/Action/BattleArenaTest.cs
  .Lib9c.Tests/Action/JoinArenaTest.cs
  .Lib9c.Tests/Action/Scenario/ArenaScenarioTest.cs
  .Lib9c.Tests/TableData/ArenaSheetTest.cs
  Lib9c/TableCSV/Arena/ArenaSheet.csv
  Lib9c/TableCSV/GameConfigSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
Labels: Medium

#1096 Update crystal data for previewnet
  .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  .Lib9c.Tests/Action/GrindingTest.cs
  .Lib9c.Tests/Action/ItemEnhancementTest.cs
  .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
  .Lib9c.Tests/Action/UnlockWorldTest.cs
  .Lib9c.Tests/CrystalCalculatorTest.cs
  .Lib9c.Tests/TableData/Crystal/CrystalEquipmentGrindingSheetTest.cs
  Lib9c/TableCSV/Crystal/CrystalEquipmentGrindingSheet.csv
  Lib9c/TableCSV/Crystal/CrystalFluctuationSheet.csv
  Lib9c/TableCSV/Crystal/CrystalMaterialCostSheet.csv
  Lib9c/TableCSV/Crystal/CrystalMonsterCollectionMultiplierSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
  Lib9c/TableCSV/WorldAndStage/WorldUnlockSheet.csv
Labels: Extra Large, CRYSTAL

#1088 Add zero item for chain consistency, in the condition
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  Lib9c/Action/ClaimStakeReward.cs
Labels: bug, Extra Small

#1098 chore: remove policies not required in PBFT
  .Lib9c.Tests/Policy/BlockPolicyTest.cs
  Lib9c/Policy/BlockPolicySource.cs
Labels: Small, pbft

#1100 Correct link
  Lib9c/Action/MonsterCollect.cs
Labels: bug, No Changes

#1103 Cherry pick commits from `2022q2`
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
  .Lib9c.Tests/TableData/StakeAchievementRewardSheetTest.cs
  .Lib9c.Tests/TableData/StakeRegularRewardSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Action/Stake.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/TableCSV/StakeRegularRewardSheet.csv
  Lib9c/TableData/IStakeRewardRow.cs
  Lib9c/TableData/IStakeRewardSheet.cs
  Lib9c/TableData/StakeAchievementRewardSheet.cs
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: Medium

#1105 Change item stat
  Lib9c/TableCSV/Item/CostumeItemSheet.csv
  Lib9c/TableCSV/Item/CostumeStatSheet.csv
Labels: Extra Small

#1106 Introduce oveloading of `CaculateCrystal()`
  Lib9c/Helper/CrystalCalculator.cs
Labels: Extra Small, CRYSTAL

#1110 Correct `MigrateMonsterCollection` action
  .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Model/State/StakeState.cs
Labels: bug, Extra Small

#1112 hotfix: Correct `MigrateMonsterCollection` action
  .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Model/State/StakeState.cs
Labels: bug, Extra Small

#1107 add miner addresses
  Lib9c/Policy/PermanentBlockPolicySource.cs
Labels: Extra Small

#1109 Fixed crystal cost
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  Lib9c/Action/CombinationEquipment.cs
Labels: Extra Small, CRYSTAL

#1117 Restrict staking when there is monster collection
  .Lib9c.Tests/Action/StakeTest.cs
  Lib9c/Action/MonsterCollectionExistingException.cs
  Lib9c/Action/Stake.cs
Labels: bug, Extra Small

#1116 Skip `ClaimMonsterCollectionReward` if there is no rewards
  .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
  Lib9c/Action/MigrateMonsterCollection.cs
Labels: bug, Extra Small

#1120 Restrict update staking when it is claimable
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
  Lib9c/Action/Stake.cs
  Lib9c/Action/StakeExistingClaimableException.cs
Labels: Extra Small

#1121 Merge `features/stake` to `2022q2`
  .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Action/MonsterCollectionExistingException.cs
  Lib9c/Action/Stake.cs
  Lib9c/Action/StakeExistingClaimableException.cs
Labels: Medium

#1122 Add meta file of StakeRegularFixedRewardSheet.csv
  Lib9c/TableCSV/StakeRegularFixedRewardSheet.csv.meta
Labels: Extra Large

#1126 Trust lockup interval processing
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
Labels: Extra Small

#1127 Trust lockup interval processing
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
Labels: Extra Small

#1123 CombinationEquipment chain consistency in previewnet
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  Lib9c/Action/CombinationEquipment.cs
Labels: Extra Small, CRYSTAL

#1124 Merge `2022q2` to `previewnet`
  .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Action/MonsterCollectionExistingException.cs
  Lib9c/Action/Stake.cs
  Lib9c/Action/StakeExistingClaimableException.cs
  Lib9c/TableCSV/StakeRegularFixedRewardSheet.csv.meta
Labels: Medium

#1129 Correct chain consistency & Hardfork for internal reason
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Action/Stake.cs
  Lib9c/Model/State/MonsterCollectionState.cs
Labels: bug, Small

#1131 Update hard fork block index
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Action/Stake.cs
  Lib9c/Model/State/MonsterCollectionState.cs
Labels: Extra Small

#1132 Merge `features/stake` to `development`
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
  .Lib9c.Tests/Model/State/StakeStateTest.cs
  .Lib9c.Tests/TableData/StakeAchievementRewardSheetTest.cs
  .Lib9c.Tests/TableData/StakeRegularFixedRewardSheetTest.cs
  .Lib9c.Tests/TableData/StakeRegularRewardSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/ClaimMonsterCollectionReward.cs
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Action/MonsterCollect.cs
  Lib9c/Action/MonsterCollectionExistingException.cs
  Lib9c/Action/Stake.cs
  Lib9c/Action/StakeExistingClaimableException.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/Lib9c.csproj
  Lib9c/Model/State/StakeState.cs
  Lib9c/SerializeKeys.cs
  Lib9c/TableCSV/StakeAchievementRewardSheet.csv
  Lib9c/TableCSV/StakeRegularFixedRewardSheet.csv
  Lib9c/TableCSV/StakeRegularRewardSheet.csv
  Lib9c/TableData/IStakeRewardRow.cs
  Lib9c/TableData/IStakeRewardSheet.cs
  Lib9c/TableData/StakeAchievementRewardSheet.cs
  Lib9c/TableData/StakeRegularFixedRewardSheet.cs
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: Extra Large

#1101 Obsolete monster collection
  .Lib9c.Tests/Action/ClaimMonsterCollectionRewardTest.cs
  .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
  .Lib9c.Tests/Action/MonsterCollectTest.cs
  Lib9c/Action/ClaimMonsterCollectionReward.cs
  Lib9c/Action/MonsterCollect.cs
  Lib9c/Policy/BlockPolicySource.cs
Labels: Small

#1092 Implement HAS random buff from #1085
  .Lib9c.Tests/Action/HackAndSlashRandomBuffTest.cs
  .Lib9c.Tests/Action/HackAndSlashTest.cs
  .Lib9c.Tests/CrystalCalculatorTest.cs
  .Lib9c.Tests/Model/State/CrystalRandomSkillStateTest.cs
  .Lib9c.Tests/TableData/Crystal/CrystalRandomBuffSheetTest.cs
  .Lib9c.Tests/TableData/Crystal/CrystalStageBuffGachaSheetTest.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlashRandomBuff.cs
  Lib9c/Action/InvalidGachaCountException.cs
  Lib9c/Addresses.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Helper/CrystalCalculator.cs
  Lib9c/Model/Skill/SkillCategory.cs
  Lib9c/Model/State/CrystalRandomSkillState.cs
  Lib9c/Model/State/HackAndSlashBuffState.cs
  Lib9c/TableCSV/Crystal/CrystalRandomBuffSheet.csv
  Lib9c/TableCSV/Crystal/CrystalStageBuffGachaSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemOptionSheet.csv
  Lib9c/TableCSV/Skill/BuffSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableData/Crystal/CrystalRandomBuffSheet.cs
  Lib9c/TableData/Crystal/CrystalStageBuffGachaSheet.cs
Labels: Extra Large, CRYSTAL

#1136 Block 'ranking battle action' using arena sheet
  .Lib9c.Tests/Action/RankingBattle11Test.cs
  .Lib9c.Tests/Action/RankingBattleTest.cs
  .Lib9c.Tests/Action/Scenario/WeeklyArenaStateUpdateScenarioTest.cs
  Lib9c/Action/RankingBattle.cs
  Lib9c/Action/RankingBattle11.cs
  Lib9c/Action/RewardGold.cs
Labels: Extra Large

#1138 Limit minimum staking amount
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
  Lib9c/Action/Stake.cs
  Lib9c/TableCSV/StakeRegularRewardSheet.csv
Labels: Extra Small

#1139 Add new miner address
  Lib9c/Policy/PermanentBlockPolicySource.cs
Labels: Extra Small

#1141 Fix build
  .Lib9c.Tests/Action/HackAndSlashTest.cs
  Lib9c/Action/HackAndSlash.cs
Labels: ci, CRYSTAL

#1144 Avoid InvalidStateRootHashException in genesis
  .Lib9c.Tests/Action/RewardGoldTest.cs
  Lib9c/Action/RewardGold.cs
Labels: bug, Small

#1146 Merge `main` to `development`
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
  Lib9c/Action/Stake.cs
  Lib9c/TableCSV/StakeRegularRewardSheet.csv
Labels: Extra Small

#1149 Avoid LoadPlainValueInternal exception
  Lib9c/Action/HackAndSlash.cs
Labels: Extra Small

#1150 Cherry-pick #1149 to 2022q2
  Lib9c/Action/HackAndSlash.cs
Labels: Extra Small

#1152 Remove throwing InvalidEquipmentException in Grinding
  .Lib9c.Tests/Action/GrindingTest.cs
  Lib9c/Action/Grinding.cs
Labels: Extra Small, CRYSTAL

#1154 Fix attack log parameter
  Lib9c/Model/Skill/Arena/ArenaAttackSkill.cs
Labels: bug, Extra Small

#1157 Update actions and states related to arena
  .Lib9c.Tests/Action/JoinArenaTest.cs
  .Lib9c.Tests/TableData/ArenaSheetTest.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/BattleArena2.cs
  Lib9c/Action/JoinArena.cs
  Lib9c/Action/JoinArena2.cs
  Lib9c/Arena/ArenaHelper.cs
  Lib9c/Model/Arena/ArenaPlayerDigest.cs
  Lib9c/Model/State/ArenaAvatarState.cs
  Lib9c/TableCSV/Arena/ArenaSheet.csv
  Lib9c/TableData/ArenaSheet.cs
Labels: Extra Large

#1168 Fix InvalidStateRootHashException in mainnet
  .Lib9c.Tests/Action/RewardGoldTest.cs
  Lib9c/Action/RewardGold.cs
Labels: bug, Small

#1166 Premium recipe option value rebalancing (115%)
  Lib9c/TableCSV/Item/EquipmentItemOptionSheet.csv
Labels: Extra Large

#1170 Update arena score limits
  Lib9c/Arena/ArenaHelper.cs
Labels: No Changes

#1169 2022q2 crystaldata 100230
  Lib9c/TableCSV/Crystal/CrystalEquipmentGrindingSheet.csv
  Lib9c/TableCSV/Crystal/CrystalFluctuationSheet.csv
  Lib9c/TableCSV/Crystal/CrystalMaterialCostSheet.csv
  Lib9c/TableCSV/Crystal/CrystalMonsterCollectionMultiplierSheet.csv
  Lib9c/TableCSV/Crystal/CrystalRandomBuffSheet.csv
  Lib9c/TableCSV/Crystal/CrystalStageBuffGachaSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
  Lib9c/TableCSV/Skill/BuffSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/WorldAndStage/WorldUnlockSheet.csv
Labels: Extra Large

#1171 2022q2 arenadata 100230
  Lib9c/TableCSV/Arena/ArenaSheet.csv
  Lib9c/TableCSV/GameConfigSheet.csv
Labels: Extra Large

#1167 Block previous actions without ArenaSheet
  .Lib9c.Tests/Action/HackAndSlash13Test.cs
  .Lib9c.Tests/Action/HackAndSlashSweepTest3.cs
  .Lib9c.Tests/Action/HackAndSlashTest.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlash13.cs
  Lib9c/Action/HackAndSlashSweep.cs
  Lib9c/Action/HackAndSlashSweep3.cs
Labels: Small

#1177 Fix cost formula of joining arena
  Lib9c/Arena/ArenaHelper.cs
Labels: bug, Extra Small

#1178 Added level limit to 'JoinArena' action
  .Lib9c.Tests/Action/BattleArenaTest.cs
  .Lib9c.Tests/Action/JoinArenaTest.cs
  Lib9c/Action/JoinArena.cs
Labels: bug, Small

#1182 Add variable to BattleArena action
  Lib9c/Action/BattleArena.cs
Labels: Extra Small

#1184 Update arena states
  .Lib9c.Tests/Model/Arena/ArenaInformationTest.cs
  Lib9c/Model/Arena/ArenaInformation.cs
  Lib9c/Model/Arena/ArenaScore.cs
Labels: Extra Small

#1180 Prevent renew staking with same amount
  .Lib9c.Tests/Action/StakeTest.cs
  Lib9c/Action/Stake.cs
Labels: bug, Extra Small

#1191 Fix Arena exception handling for InvalidBlockStateRootHashException
  Lib9c/Action/RankingBattle.cs
Labels: bug, Extra Small

#1192 Fixed to update arena HP*2 when buff stats change
  .Lib9c.Tests/Model/ArenaSimulatorTest.cs
  Lib9c/Action/BattleArena1.cs
  Lib9c/Arena/ArenaSimulator.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Skill/Arena/ArenaAreaAttack.cs
  Lib9c/Model/Skill/Arena/ArenaBlowAttack.cs
  Lib9c/Model/Skill/Arena/ArenaBuffSkill.cs
  Lib9c/Model/Skill/Arena/ArenaDoubleAttack.cs
  Lib9c/Model/Skill/Arena/ArenaHealSkill.cs
  Lib9c/Model/Skill/Arena/ArenaNormalAttack.cs
  Lib9c/Model/Skill/Arena/ArenaSkill.cs
Labels: bug, Large
