Repository planetarium/lib9c, pull requests merged in 2022-03, with the labels that each got.

#871 Improve `9c-tools state` subcommands
  .Lib9c.DevExtensions.Tests/Data/TableCSV/Cost/EnhancementCostSheet.csv
  .Lib9c.DevExtensions.Tests/Data/TableCSV/GameConfigSheet.csv
  .Lib9c.DevExtensions.Tests/Lib9c.DevExtensions.Tests.csproj
  .Lib9c.Tests/Lib9c.Tests.csproj
  .Lib9c.Tools.Tests/Lib9c.Tools.Tests.csproj
  .Lib9c.Tools/SubCommand/State.cs
  Lib9c.DevExtensions/Utils.cs
Labels: bug, enhancement, Medium

#861 Conditional serialize avatar in RankingBattle
  .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
  .Lib9c.Tests/Action/RankingBattleTest.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/Buy.cs
  Lib9c/Action/Buy8.cs
  Lib9c/Action/Buy9.cs
  Lib9c/Action/ChargeActionPoint.cs
  Lib9c/Action/CombinationConsumable.cs
  Lib9c/Action/CombinationConsumable6.cs
  Lib9c/Action/CombinationConsumable7.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlash10.cs
  Lib9c/Action/HackAndSlash6.cs
  Lib9c/Action/HackAndSlash7.cs
  Lib9c/Action/HackAndSlash8.cs
  Lib9c/Action/HackAndSlash9.cs
  Lib9c/Action/MimisbrunnrBattle.cs
  Lib9c/Action/MimisbrunnrBattle4.cs
  Lib9c/Action/MimisbrunnrBattle5.cs
  Lib9c/Action/MimisbrunnrBattle6.cs
  Lib9c/Action/MimisbrunnrBattle7.cs
  Lib9c/Action/RankingBattle.cs
  Lib9c/Action/RankingBattle5.cs
  Lib9c/Action/RankingBattle6.cs
  Lib9c/Action/RankingBattle7.cs
  Lib9c/Action/RankingBattle8.cs
  Lib9c/Action/RankingBattle9.cs
  Lib9c/Action/RedeemCode.cs
  Lib9c/Action/RedeemCode2.cs
  Lib9c/Action/SellCancellation.cs
  Lib9c/Action/SellCancellation7.cs
  Lib9c/Action/SellCancellation8.cs
  Lib9c/Action/UpdateSell.cs
  Lib9c/Action/UpdateSell0.cs
Labels: Small

#864 Merge the `feature/arena-season-2` branch into the `development` branch
  .Lib9c.Tests/Action/ClaimMonsterCollectionReward2Test.cs
  .Lib9c.Tests/Action/ClaimMonsterCollectionRewardTest.cs
  .Lib9c.Tests/Model/Mail/MonsterCollectMailTest.cs
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
  Lib9c/TableCSV/MonsterCollectionRewardSheet.csv
  Lib9c/TableCSV/WeeklyArenaRewardSheet.csv
Labels: Small

#878 Delete unused Result field
  .Lib9c.Tests/Action/RankingBattleTest.cs
  Lib9c/Action/RankingBattle.cs
Labels: Extra Small

#880 chore: add permissioned miners
  Lib9c/Policy/PermanentBlockPolicySource.cs
Labels: Small

#882 dev Rc v100130
  .Lib9c.Tests/Action/RankingBattleTest.cs
  Lib9c/Action/RankingBattle.cs
Labels: Extra Small

#873 Feature/use get states in hack and slash
  .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
  .Lib9c.Tests/Action/ExceptionTest.cs
  .Lib9c.Tests/Extensions/SheetsExtensionsTest.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/FailedLoadSheetException.cs
  Lib9c/Action/FailedLoadStateException.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Extensions/SheetsExtensions.cs
Labels: Extra Large

#875 Introduce EnemyPlayerDigest
  .Lib9c.Tests/Action/RankingBattleTest.cs
  .Lib9c.Tests/Battle/EnemyPlayerDigestTest.cs
  Lib9c/Action/RankingBattle.cs
  Lib9c/Battle/EnemyPlayerDigest.cs
  Lib9c/Battle/RankingSimulator.cs
  Lib9c/Battle/Simulator.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Character/EnemyPlayer.cs
  Lib9c/Model/Character/Player.cs
Labels: Large

#892 EquipmentItemRecipeSheet 999 data edited
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
Labels: Medium

#886 Arena Season2 Close - WeeklyArenaRewardSheet, MaterialItemSheet
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
  Lib9c/TableCSV/WeeklyArenaRewardSheet.csv
Labels: Small

#893 Using GetSheets in RankingBattle action
  Lib9c/Action/RankingBattle.cs
Labels: Extra Small

#898 Release automation
  .github/workflows/main.yml
Labels: ci

#899 revomon ear&tail costumeitemsheet data added
  Lib9c/TableCSV/Item/CostumeItemSheet.csv
Labels: Extra Small

#900 Merge rc-v100150 into development
  .github/workflows/main.yml
Labels: Extra Small

#902 Update target index by v100160 release date
  Lib9c/Action/RankingBattle.cs
Labels: Extra Small
