Repository planetarium/lib9c, pull requests merged in 2022-08, with the labels that each got.

#1234 Introduce `RaidSimulator`.
  .Lib9c.Tests/Action/RaidTest.cs
  .Lib9c.Tests/Model/RaidSimulatorTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/Raid.cs
  Lib9c/Battle/CPHelper.cs
  Lib9c/Battle/RaidBoss.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Character/Enemy.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Model/Stat/CharacterStats.cs
  Lib9c/TableCSV/RuneSheet.csv.meta
  Lib9c/TableCSV/RuneWeightSheet.csv
  Lib9c/TableCSV/Skill/EnemySkillSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv.meta
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossRankRewardSheet.csv
  Lib9c/TableData/Character/WorldBossCharacterSheet.cs
  Lib9c/TableData/SimulatorSheets.cs
Labels: Extra Large

#1238 Introduce `ISimulator` and `IStageSimulator` interface
  Lib9c/Battle/ISimulator.cs
  Lib9c/Battle/IStageSimulator.cs
  Lib9c/Battle/Simulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Battle/Wave.cs
  Lib9c/Model/Character/Enemy.cs
  Lib9c/Model/State/AvatarState.cs
Labels: Small

#1243 Add WorldBossKillRewardSheet meta file
  Lib9c/TableCSV/WorldBoss/WorldBossKillRewardSheet.csv.meta
Labels: Extra Small

#1245 [bugfix] Clone enemy model on spawn event in simulator.
  Lib9c/Battle/RaidBoss.cs
  Lib9c/Battle/RaidSimulator.cs
Labels: Extra Small

#1244 Refactor `StageSimulator` and `MimisbrunnrBattle`
  .Lib9c.Tests/Action/HackAndSlashTest.cs
  .Lib9c.Tests/Model/BattleLogTest.cs
  .Lib9c.Tests/Model/PlayerTest.cs
  .Lib9c.Tests/Model/Skill/NormalAttackTest.cs
  .Lib9c.Tests/Model/StageSimulatorTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/MimisbrunnrBattle.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/TableData/SimulatorSheets.cs
Labels: Medium

#1242 claim kill reward in Raid action
  .Lib9c.Tests/Action/RaidTest.cs
  Lib9c/Action/Raid.cs
  Lib9c/Helper/WorldBossHelper.cs
  Lib9c/Model/State/RaiderState.cs
  Lib9c/Model/State/WorldBossKillRewardRecord.cs
Labels: Large

#1248 Refactor StageSimulator
  .Lib9c.Tests/Action/HackAndSlashTest.cs
  .Lib9c.Tests/Model/BattleLogTest.cs
  .Lib9c.Tests/Model/PlayerTest.cs
  .Lib9c.Tests/Model/Skill/NormalAttackTest.cs
  .Lib9c.Tests/Model/StageSimulatorTest.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/MimisbrunnrBattle.cs
  Lib9c/Battle/StageSimulator.cs
Labels: Medium

#1249 Introduce WorldBossRankingRewardSheet
  .Lib9c.Tests/TableData/WorldBossRankingRewardSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/TableCSV/WorldBoss/WorldBossRankingRewardSheet.csv
  Lib9c/TableData/WorldBossRankingRewardSheet.cs
Labels: Medium

#1255 Add sheet meta file (WorldBossRankingRewardSheet)
  Lib9c/TableCSV/WorldBoss/WorldBossRankingRewardSheet.csv.meta
Labels: Extra Small

#1226 Introduce `EventConsumableItemCrafts` action
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/EventConsumableItemCraftsTest.cs
  .Lib9c.Tests/Action/EventDungeonBattleTest.cs
  .Lib9c.Tests/TableData/Event/EventConsumableItemRecipeSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/EventConsumableItemCrafts.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Action/NotEnoughClearedStageLevelException.cs
  Lib9c/Extensions/CombinationSlotStateExtensions.cs
  Lib9c/Extensions/EventRecipeExtensions.cs
  Lib9c/Extensions/EventScheduleExtensions.cs
  Lib9c/Extensions/MaterialItemSheetExtensions.cs
  Lib9c/Extensions/WorldInformationExtensions.cs
  Lib9c/Model/State/CombinationSlotState.cs
  Lib9c/TableCSV/Event/EventConsumableItemRecipeSheet.csv
  Lib9c/TableCSV/Event/EventConsumableItemRecipeSheet.csv.meta
  Lib9c/TableData/Event/EventConsumableItemRecipeSheet.cs
Labels: Extra Large

#1256 Introduce `HammerPointState` for new feature of combination
  .Lib9c.Tests/Model/State/HammerPointStateTest.cs
  Lib9c/Addresses.cs
  Lib9c/Model/State/HammerPointState.cs
Labels: Small

#1253 Implement Raid boss attack pattern.
  .Lib9c.Tests/Action/RaidTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/Raid.cs
  Lib9c/Battle/RaidBoss.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/TableCSV/Skill/EnemySkillSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossActionPatternSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossActionPatternSheet.csv.meta
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
  Lib9c/TableData/Character/WorldBossCharacterSheet.cs
  Lib9c/TableData/SimulatorSheets.cs
  Lib9c/TableData/WorldBossActionPatternSheet.cs
Labels: Large

#1260 Add food in testbed
  Lib9c.DevExtensions/Data/TestbedCreateAvatar.json
  Lib9c.DevExtensions/Model/TestbedCreateAvatar.cs
  Lib9c/Action/CreateAvatar0.cs
Labels: Extra Small

#1257 Introduce CrystalHammerPointSheet
  .Lib9c.Tests/Model/State/HammerPointStateTest.cs
  .Lib9c.Tests/TableData/Crystal/CrystalHammerPointSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Model/State/HammerPointState.cs
  Lib9c/TableCSV/Crystal/CrystalHammerPointSheet.csv
  Lib9c/TableCSV/Crystal/CrystalHammerPointSheet.csv.meta
  Lib9c/TableData/Crystal/CrystalHammerPointSheet.cs
Labels: Large

#1266 Update game config
  Lib9c/Action/Raid.cs
  Lib9c/GameConfig.cs
Labels: Extra Small

#1268 Fix broken sheet data
  .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
  .Lib9c.Tests/Action/ClaimWorldBossKillRewardTest.cs
  .Lib9c.Tests/Action/RaidTest.cs
  .Lib9c.Tests/TableData/WorldBossRankingRewardSheetTest.cs
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
Labels: Extra Small

#1269 Fix simulate call without level check
  .Lib9c.Tests/Action/RaidTest.cs
  Lib9c/Action/Raid.cs
Labels: Small

#1271 2022q3 worldboss
  .Lib9c.Tests/Action/RaidTest.cs
  Lib9c/Action/Raid.cs
Labels: Small

#1273 Fix Raid action serialize
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  Lib9c/Action/Raid.cs
Labels: Extra Small

#1274 2022q3 worldboss
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  Lib9c/Action/Raid.cs
Labels: Extra Small

#1278 Fix dependecny conflict in headless
  .Lib9c.Tests/Lib9c.Tests.csproj
Labels: Extra Small

#1280 Delete duplicate dependecy
  .Lib9c.Tests/Lib9c.Tests.csproj
Labels: Extra Small

#1281 Apply equipments on raid battle simulation.
  Lib9c/Action/Raid.cs
Labels: Extra Small

#1282 Cherry pick commits related to dependencies
  .Lib9c.Tests/Lib9c.Tests.csproj
Labels: bug, Extra Small

#1284 Delete mint NCG
  .Lib9c.Tests/Action/CreateAvatarTest.cs
  Lib9c/Action/CreateAvatar.cs
Labels: Extra Small

#1283 20220810 merge worldboss into internal test
  .Lib9c.Tests/Lib9c.Tests.csproj
  Lib9c/Action/Raid.cs
Labels: Extra Small

#1286 Update initialize avatar state
  .Lib9c.Tests/Action/CreateAvatarTest.cs
  Lib9c/Action/CreateAvatar.cs
Labels: Extra Small

#1290 Fix deserialize action
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  Lib9c/Action/ClaimRaidReward.cs
  Lib9c/Action/ClaimWordBossKillReward.cs
Labels: bug, Extra Small

#1291 2022q3 worldboss
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  Lib9c/Action/ClaimRaidReward.cs
  Lib9c/Action/ClaimWordBossKillReward.cs
Labels: Extra Small

#1212 fix action evaluation results in `v100240`
  Lib9c/Action/Buy11.cs
  Lib9c/Action/CombinationEquipment11.cs
  Lib9c/Action/HackAndSlash13.cs
  Lib9c/Action/HackAndSlashSweep4.cs
  Lib9c/Action/ItemEnhancement10.cs
  Lib9c/Action/RankingBattle.cs
  Lib9c/Action/RapidCombination6.cs
Labels: bug, Extra Small

#1285 feat: buy ticket if needed on `EventDungeonBattle`
  .Lib9c.Tests/Action/EventDungeonBattleTest.cs
  .Lib9c.Tests/Extensions/EventScheduleExtensionsTest.cs
  .Lib9c.Tests/Lib9c.Tests.csproj
  .Lib9c.Tests/Model/Event/EventDungeonInfoTest.cs
  .Lib9c.Tests/TableData/Event/EventScheduleSheetTest.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Addresses.cs
  Lib9c/Extensions/EventScheduleExtensions.cs
  Lib9c/Model/Event/EventDungeonInfo.cs
  Lib9c/TableCSV/Event/EventScheduleSheet.csv
  Lib9c/TableData/Event/EventScheduleSheet.cs
Labels: Large

#1289 Introduce `Lib9c.Tools action list`
  .Lib9c.Tools/Program.cs
  .Lib9c.Tools/SubCommand/Action.cs
  .github/workflows/main.yml
Labels: suggestion, Small

#1292 Feature/optional admin state
  .Lib9c.Tests/Action/InitializeStatesTest.cs
  Lib9c/Action/InitializeStates.cs
  Lib9c/BlockHelper.cs
Labels: enhancement, Medium

#1299 Rc v100270 to development
  .Lib9c.Tests/Lib9c.Tests.csproj
Labels: Extra Small

#1302 Fix data of event dungeon sheets
  .Lib9c.Tests/Action/EventDungeonBattleTest.cs
  Lib9c/TableCSV/Event/EventDungeonSheet.csv
  Lib9c/TableCSV/Event/EventDungeonStageSheet.csv
  Lib9c/TableCSV/Event/EventScheduleSheet.csv
Labels: Extra Small

#1304 Merge `feature/event-dungeons` into `development`
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/EventConsumableItemCraftsTest.cs
  .Lib9c.Tests/Action/EventDungeonBattleTest.cs
  .Lib9c.Tests/Action/ExceptionTest.cs
  .Lib9c.Tests/Extensions/EventDungeonExtensionsTest.cs
  .Lib9c.Tests/Extensions/EventScheduleExtensionsTest.cs
  .Lib9c.Tests/Lib9c.Tests.csproj
  .Lib9c.Tests/Model/Event/EventDungeonInfoTest.cs
  .Lib9c.Tests/TableData/Event/EventConsumableItemRecipeSheetTest.cs
  .Lib9c.Tests/TableData/Event/EventDungeonSheetTest.cs
  .Lib9c.Tests/TableData/Event/EventDungeonStageSheetTest.cs
  .Lib9c.Tests/TableData/Event/EventDungeonStageWaveSheetTest.cs
  .Lib9c.Tests/TableData/Event/EventScheduleSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c.sln.DotSettings
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/EventConsumableItemCrafts.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Action/FailedLoadStateException.cs
  Lib9c/Action/NotEnoughClearedStageLevelException.cs
  Lib9c/Action/StageClearedException.cs
  Lib9c/Addresses.cs
  Lib9c/Exceptions/InvalidActionFieldException.cs
  Lib9c/Exceptions/NotEnoughEventDungeonTicketsException.cs
  Lib9c/Extensions/CombinationSlotStateExtensions.cs
  Lib9c/Extensions/EventDungeonExtensions.cs
  Lib9c/Extensions/EventRecipeExtensions.cs
  Lib9c/Extensions/EventScheduleExtensions.cs
  Lib9c/Extensions/MaterialItemSheetExtensions.cs
  Lib9c/Extensions/WorldInformationExtensions.cs
  Lib9c/Model/Elemental/ElementalType.cs
  Lib9c/Model/Event/EventDungeonInfo.cs
  Lib9c/Model/State/AvatarState.cs
  Lib9c/Model/State/CombinationSlotState.cs
  Lib9c/TableCSV/Event.meta
  Lib9c/TableCSV/Event/EventConsumableItemRecipeSheet.csv
  Lib9c/TableCSV/Event/EventConsumableItemRecipeSheet.csv.meta
  Lib9c/TableCSV/Event/EventDungeonSheet.csv
  Lib9c/TableCSV/Event/EventDungeonSheet.csv.meta
  Lib9c/TableCSV/Event/EventDungeonStageSheet.csv
  Lib9c/TableCSV/Event/EventDungeonStageSheet.csv.meta
  Lib9c/TableCSV/Event/EventDungeonStageWaveSheet.csv
  Lib9c/TableCSV/Event/EventDungeonStageWaveSheet.csv.meta
  Lib9c/TableCSV/Event/EventScheduleSheet.csv
  Lib9c/TableCSV/Event/EventScheduleSheet.csv.meta
  Lib9c/TableCSV/Item/ConsumableItemSheet.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
  Lib9c/TableData/Event/EventConsumableItemRecipeSheet.cs
  Lib9c/TableData/Event/EventDungeonSheet.cs
  Lib9c/TableData/Event/EventDungeonStageSheet.cs
  Lib9c/TableData/Event/EventDungeonStageWaveSheet.cs
  Lib9c/TableData/Event/EventScheduleSheet.cs
  Lib9c/TableData/Exceptions.cs
  Lib9c/TableData/WorldAndStage/StageWaveSheet.cs
Labels: Extra Large

#1233 ArenaSheet data updated
  .Lib9c.Tests/Action/ArenahelperTest.cs
  .Lib9c.Tests/Action/JoinArenaTest.cs
  Lib9c/TableCSV/Arena/ArenaSheet.csv
Labels: Extra Small

#1272 Update StageBuffSkill
  Lib9c/TableCSV/Crystal/CrystalRandomBuffSheet.csv
  Lib9c/TableCSV/Skill/BuffSheet.csv
Labels: Medium

#1305 Update CrystalHammerPointSheet.csv
  Lib9c/TableCSV/Crystal/CrystalHammerPointSheet.csv
Labels: Small

#1247 Introduce PrepareRewardAssets
  .Lib9c.Tests/Action/PrepareRewardAssetsTest.cs
  Lib9c/Action/PrepareRewardAssets.cs
Labels: Small

#1311 Block super craft with mimis recipe
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  Lib9c/Action/CombinationEquipment.cs
Labels: Extra Small

#1320 Fix serialize, deserialize PrepareRewardAssets
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  Lib9c/Action/PrepareRewardAssets.cs
Labels: Extra Small

#1325 Improve/create avatar
  .Lib9c.Tests/Action/CreateAvatarTest.cs
  Lib9c/Action/CreateAvatar.cs
  Lib9c/Policy/BlockPolicySource.cs
Labels: Small

#1327 Add Discord invitation buttons
  README.md
Labels: Extra Small

#1326 Introduce enrage in raid battle.
  Lib9c/Battle/RaidBoss.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Model/BattleStatus/AreaAttack.cs
  Lib9c/Model/BattleStatus/BlowAttack.cs
  Lib9c/Model/BattleStatus/BuffSkill.cs
  Lib9c/Model/BattleStatus/DoubleAttack.cs
  Lib9c/Model/BattleStatus/HealSkill.cs
  Lib9c/Model/BattleStatus/NormalAttack.cs
  Lib9c/Model/BattleStatus/Skill.cs
  Lib9c/Model/IStage.cs
  Lib9c/Model/Skill/AreaAttack.cs
  Lib9c/Model/Skill/BlowAttack.cs
  Lib9c/Model/Skill/BuffSkill.cs
  Lib9c/Model/Skill/DoubleAttack.cs
  Lib9c/Model/Skill/HealSkill.cs
  Lib9c/Model/Skill/NormalAttack.cs
  Lib9c/TableCSV/Skill/BuffSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossActionPatternSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
  Lib9c/TableData/Character/WorldBossCharacterSheet.cs
  Lib9c/TableData/WorldBossActionPatternSheet.cs
Labels: Medium

#1329 Merge 2022q3-worldboss into `worldboss-internal-test`
  Lib9c/Battle/RaidBoss.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Model/BattleStatus/AreaAttack.cs
  Lib9c/Model/BattleStatus/BlowAttack.cs
  Lib9c/Model/BattleStatus/BuffSkill.cs
  Lib9c/Model/BattleStatus/DoubleAttack.cs
  Lib9c/Model/BattleStatus/HealSkill.cs
  Lib9c/Model/BattleStatus/NormalAttack.cs
  Lib9c/Model/BattleStatus/Skill.cs
  Lib9c/Model/IStage.cs
  Lib9c/Model/Skill/AreaAttack.cs
  Lib9c/Model/Skill/BlowAttack.cs
  Lib9c/Model/Skill/BuffSkill.cs
  Lib9c/Model/Skill/DoubleAttack.cs
  Lib9c/Model/Skill/HealSkill.cs
  Lib9c/Model/Skill/NormalAttack.cs
  Lib9c/TableCSV/Skill/BuffSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossActionPatternSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
  Lib9c/TableData/Character/WorldBossCharacterSheet.cs
  Lib9c/TableData/WorldBossActionPatternSheet.cs
Labels: Medium

#1328 Introduce `BuffRemovalAttack`.
  Lib9c/Model/BattleStatus/Arena/ArenaBuffRemovalAttack.cs
  Lib9c/Model/BattleStatus/BuffRemovalAttack.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/IArena.cs
  Lib9c/Model/IStage.cs
  Lib9c/Model/Skill/Arena/ArenaBuffRemovalAttack.cs
  Lib9c/Model/Skill/BuffRemovalAttack.cs
  Lib9c/Model/Skill/SkillCategory.cs
  Lib9c/Model/Skill/SkillFactory.cs
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossActionPatternSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
Labels: Medium

#1332 Introduce new debuff `bleed`.
  .Lib9c.Tests/Action/ClaimRaidRewardTest.cs
  .Lib9c.Tests/Action/RaidTest.cs
  .Lib9c.Tests/Model/RaidSimulatorTest.cs
  .Lib9c.Tests/Model/Skill/NormalAttackTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/Raid.cs
  Lib9c/Battle/RaidBoss.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/Simulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Battle/StageSimulatorV1.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/Model/BattleStatus/TickDamage.cs
  Lib9c/Model/Buff/ActionBuff.cs
  Lib9c/Model/Buff/AttackBuff.cs
  Lib9c/Model/Buff/Bleed.cs
  Lib9c/Model/Buff/Buff.cs
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/Model/Buff/CriticalBuff.cs
  Lib9c/Model/Buff/DefenseBuff.cs
  Lib9c/Model/Buff/HPBuff.cs
  Lib9c/Model/Buff/HitBuff.cs
  Lib9c/Model/Buff/SpeedBuff.cs
  Lib9c/Model/Buff/StatBuff.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/IStage.cs
  Lib9c/Model/Skill/ActionBuffType.cs
  Lib9c/Model/Skill/Arena/ArenaBuffRemovalAttack.cs
  Lib9c/Model/Skill/Arena/ArenaSkill.cs
  Lib9c/Model/Skill/BuffRemovalAttack.cs
  Lib9c/Model/Skill/Skill.cs
  Lib9c/Model/Stat/CharacterStats.cs
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv.meta
  Lib9c/TableCSV/Skill/SkillActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillActionBuffSheet.csv.meta
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv.meta
  Lib9c/TableCSV/WorldBoss/WorldBossActionPatternSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
  Lib9c/TableData/SimulatorSheets.cs
  Lib9c/TableData/Skill/ActionBuffSheet.cs
  Lib9c/TableData/Skill/SkillActionBuffSheet.cs
  Lib9c/TableData/Skill/StatBuffSheet.cs
Labels: Extra Large

#1339 Fix compile error in CombinationEquipment13Test
  .Lib9c.Tests/Action/CombinationEquipment13Test.cs
Labels: Extra Small

#1340 Merge 2022q3-worldboss into worldboss-internal-test
  .Lib9c.Tests/Action/ClaimRaidRewardTest.cs
  .Lib9c.Tests/Action/RaidTest.cs
  .Lib9c.Tests/Model/RaidSimulatorTest.cs
  .Lib9c.Tests/Model/Skill/NormalAttackTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/Raid.cs
  Lib9c/Battle/RaidBoss.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/Simulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Battle/StageSimulatorV1.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/Model/BattleStatus/Arena/ArenaBuffRemovalAttack.cs
  Lib9c/Model/BattleStatus/BuffRemovalAttack.cs
  Lib9c/Model/BattleStatus/TickDamage.cs
  Lib9c/Model/Buff/ActionBuff.cs
  Lib9c/Model/Buff/AttackBuff.cs
  Lib9c/Model/Buff/Bleed.cs
  Lib9c/Model/Buff/Buff.cs
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/Model/Buff/CriticalBuff.cs
  Lib9c/Model/Buff/DefenseBuff.cs
  Lib9c/Model/Buff/HPBuff.cs
  Lib9c/Model/Buff/HitBuff.cs
  Lib9c/Model/Buff/SpeedBuff.cs
  Lib9c/Model/Buff/StatBuff.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/IArena.cs
  Lib9c/Model/IStage.cs
  Lib9c/Model/Skill/ActionBuffType.cs
  Lib9c/Model/Skill/Arena/ArenaBuffRemovalAttack.cs
  Lib9c/Model/Skill/Arena/ArenaSkill.cs
  Lib9c/Model/Skill/BuffRemovalAttack.cs
  Lib9c/Model/Skill/Skill.cs
  Lib9c/Model/Skill/SkillCategory.cs
  Lib9c/Model/Skill/SkillFactory.cs
  Lib9c/Model/Stat/CharacterStats.cs
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv.meta
  Lib9c/TableCSV/Skill/SkillActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillActionBuffSheet.csv.meta
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv.meta
  Lib9c/TableCSV/WorldBoss/WorldBossActionPatternSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossRankRewardSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossRankingRewardSheet.csv
  Lib9c/TableData/SimulatorSheets.cs
  Lib9c/TableData/Skill/ActionBuffSheet.cs
  Lib9c/TableData/Skill/SkillActionBuffSheet.cs
  Lib9c/TableData/Skill/StatBuffSheet.cs
Labels: Extra Large

#1341 Implement raid battle reward
  .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
  .Lib9c.Tests/Action/ClaimRaidRewardTest.cs
  .Lib9c.Tests/Action/ClaimWorldBossKillRewardTest.cs
  .Lib9c.Tests/Action/RaidTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/ClaimRaidReward.cs
  Lib9c/Action/ClaimWordBossKillReward.cs
  Lib9c/Action/Raid.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/Helper/RuneHelper.cs
  Lib9c/Helper/WorldBossHelper.cs
  Lib9c/TableCSV/WorldBoss/WorldBossBattleRewardSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossBattleRewardSheet.csv.meta
  Lib9c/TableData/SimulatorSheets.cs
  Lib9c/TableData/WorldBossBattleRewardSheet.cs
Labels: Large

#1303 Make staking able to claim stake reward at static reward interval
  .Lib9c.Tests/Model/State/StakeStateTest.cs
  Lib9c/Model/State/StakeState.cs
Labels: bug, Extra Small

#1343 Fix `OnPostSkill` order
  Lib9c/Battle/RaidBoss.cs
  Lib9c/Helper/RuneHelper.cs
  Lib9c/Model/Character/CharacterBase.cs
Labels: Small

#1344 Merge 2022q3-worldboss into internal test branch
  .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
  .Lib9c.Tests/Action/ClaimRaidRewardTest.cs
  .Lib9c.Tests/Action/ClaimWorldBossKillRewardTest.cs
  .Lib9c.Tests/Action/RaidTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/ClaimRaidReward.cs
  Lib9c/Action/ClaimWordBossKillReward.cs
  Lib9c/Action/Raid.cs
  Lib9c/Battle/RaidBoss.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/Helper/RuneHelper.cs
  Lib9c/Helper/WorldBossHelper.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/TableCSV/WorldBoss/WorldBossBattleRewardSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossBattleRewardSheet.csv.meta
  Lib9c/TableData/SimulatorSheets.cs
  Lib9c/TableData/WorldBossBattleRewardSheet.cs
Labels: Large

#1345 Update Validator.ValidateForHackAndSlash to using costAp argument
  .Lib9c.Tests/Action/HackAndSlashTest.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Helper/Validator.cs
Labels: Small
