Repository planetarium/lib9c, pull requests merged in 2022-07, with the labels that each got.

#1187 feat(#1087): introduce useful `IActionContext` extensions
  .Lib9c.Tests/Action/ActionContextExtensionsTest.cs
  Lib9c/Action/ActionContextExtensions.cs
Labels: Small

#1193 [Bug Fix] Add case for `ItemEnhancement9`
  Lib9c/Extensions/CombinationSlotStateExtensions.cs
Labels: Extra Small

#1199 Validate sheet data in tx command
  .Lib9c.Tools/SubCommand/Tx.cs
Labels: Extra Small

#1203 Explicitly initialize variables with value types
  Lib9c/Extensions/CombinationSlotStateExtensions.cs
Labels: Extra Small

#1207 Introduce Raid MVP
  .Lib9c.Tests/Action/RaidTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/Raid.cs
  Lib9c/Addresses.cs
  Lib9c/Model/State/RaiderState.cs
  Lib9c/Model/State/WorldBossState.cs
  Lib9c/TableCSV/WorldBoss.meta
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv.meta
  Lib9c/TableData/WorldBossListSheet.cs
Labels: Large

#1211 Introduce event dungeon sheets
  .Lib9c.Tests/Lib9c.Tests.csproj
  .Lib9c.Tests/TableData/Event/EventDungeonSheetTest.cs
  .Lib9c.Tests/TableData/Event/EventDungeonStageSheetTest.cs
  .Lib9c.Tests/TableData/Event/EventDungeonStageWaveSheetTest.cs
  .Lib9c.Tests/TableData/Event/EventScheduleSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/TableCSV/Event.meta
  Lib9c/TableCSV/Event/EventDungeonSheet.csv
  Lib9c/TableCSV/Event/EventDungeonSheet.csv.meta
  Lib9c/TableCSV/Event/EventDungeonStageSheet.csv
  Lib9c/TableCSV/Event/EventDungeonStageSheet.csv.meta
  Lib9c/TableCSV/Event/EventDungeonStageWaveSheet.csv
  Lib9c/TableCSV/Event/EventDungeonStageWaveSheet.csv.meta
  Lib9c/TableCSV/Event/EventScheduleSheet.csv
  Lib9c/TableCSV/Event/EventScheduleSheet.csv.meta
  Lib9c/TableData/Event/EventDungeonSheet.cs
  Lib9c/TableData/Event/EventDungeonStageSheet.cs
  Lib9c/TableData/Event/EventDungeonStageWaveSheet.cs
  Lib9c/TableData/Event/EventScheduleSheet.cs
  Lib9c/TableData/WorldAndStage/StageSheet.cs
  Lib9c/TableData/WorldAndStage/StageWaveSheet.cs
  Lib9c/TableData/WorldAndStage/WorldSheet.cs
Labels: Large

#1214 Merge `rc-v100250` into `main`
  .Lib9c.Tools/SubCommand/Tx.cs
  Lib9c/Extensions/CombinationSlotStateExtensions.cs
Labels: Extra Small

#1213 Introduce `EventDungeonInfo`
  .Lib9c.Tests/Model/Event/EventDungeonInfoTest.cs
  Lib9c/Model/Event/EventDungeonInfo.cs
Labels: Medium

#1209 ClaimRaidReward MVP
  .Lib9c.Tests/Action/ClaimRaidRewardTest.cs
  .Lib9c.Tests/Action/RuneHelperTest.cs
  .Lib9c.Tests/TableData/RuneWeightSheetTest.cs
  .Lib9c.Tests/TableData/WorldBossListSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/ClaimRaidReward.cs
  Lib9c/Action/NotEnoughRankException.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/Helper/RuneHelper.cs
  Lib9c/Helper/WorldBossHelper.cs
  Lib9c/Model/State/RaiderState.cs
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
  Lib9c/TableCSV/RuneWeightSheet.csv
  Lib9c/TableCSV/RuneWeightSheet.csv.meta
  Lib9c/TableCSV/WorldBoss/WorldBossRankRewardSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossRankRewardSheet.csv.meta
  Lib9c/TableData/RuneWeightSheet.cs
  Lib9c/TableData/WorldBossRankRewardSheet.cs
Labels: Large

#1208 Rename `ArenaPlayerDigest` to `PlayerDigest`.
  .Lib9c.Tests/Model/Arena/PlayerDigestTest.cs
  .Lib9c.Tests/Model/ArenaSimulatorTest.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/BattleArena1.cs
  Lib9c/Arena/ArenaSimulator.cs
  Lib9c/Arena/ArenaSimulator2.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/EnemyPlayer.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Model/Character/PlayerDigest.cs
Labels: Medium

#1219 Improve Raid action
  .Lib9c.Tests/Action/RaidTest.cs
  .Lib9c.Tests/Action/WorldBossHelperTest.cs
  .Lib9c.Tests/TableData/WorldBossListSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/Raid.cs
  Lib9c/Arena/ArenaHelper.cs
  Lib9c/Helper/CrystalCalculator.cs
  Lib9c/Helper/WorldBossHelper.cs
  Lib9c/Model/State/RaiderState.cs
  Lib9c/Model/State/WorldBossState.cs
  Lib9c/TableCSV/RuneWeightSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossGlobalHpSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossGlobalHpSheet.csv.meta
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossRankRewardSheet.csv
  Lib9c/TableData/TableExtensions.cs
  Lib9c/TableData/WorldBossGlobalHPSheet.cs
  Lib9c/TableData/WorldBossListSheet.cs
Labels: Large
