Repository planetarium/lib9c, pull requests merged in 2022-04, with the labels that each got.

#907 Add Revomon costume
  Lib9c/TableCSV/Item/CostumeItemSheet.csv
Labels: Extra Small

#908 Add contidional value change `ActionsInMimisbrunnr`
  Lib9c/GameConfig.cs
Labels: Extra Small

#905 Bug fix/check equipment is mimisbrunnr
  .Lib9c.Tests/Extensions/EquipmentExtensionsTest.cs
  Lib9c/Extensions/EquipmentExtensions.cs
Labels: bug, Large

#910 Improve/item requirement sheet setting for debug
  Lib9c/TableData/Item/ItemRequirementSheet.cs
Labels: Extra Small

#914 Update block index for previewnet
  Lib9c/Action/RankingBattle.cs
Labels: Extra Small

#915 Fix up Git submodules
  .gitmodules
Labels: dependencies, Extra Small

#918 Fix rc bugs
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  Lib9c/Extensions/EquipmentExtensions.cs
  Lib9c/Model/State/AvatarState.cs
Labels: bug, Extra Small

#920 Trigger Submodule Updater on every push to rc-v* branches
  .github/workflows/main.yml
Labels: ci, Extra Small

#922 improve mimisbrunnr check logic
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  Lib9c/Extensions/EquipmentExtensions.cs
Labels: bug, Extra Small

#928 Merge the `rc-v100171` branch into the `main` branch
  .Lib9c.Tests/Action/RankingBattleTest.cs
  Lib9c/Action/HackAndSlash10.cs
  Lib9c/Action/MimisbrunnrBattle7.cs
  Lib9c/Action/RankingBattle.cs
  Lib9c/Policy/BlockPolicySource.cs
Labels: Extra Small

#929 Merge the `rc-v100171` branch into the `development` branch
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  .Lib9c.Tests/Action/RankingBattleTest.cs
  .github/workflows/main.yml
  Lib9c/Action/HackAndSlash10.cs
  Lib9c/Action/MimisbrunnrBattle7.cs
  Lib9c/Action/RankingBattle.cs
  Lib9c/Extensions/EquipmentExtensions.cs
  Lib9c/Model/State/AvatarState.cs
  Lib9c/Policy/BlockPolicySource.cs
Labels: Small

#931 Introduce grinding MVP
  .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/CreateAvatar3Test.cs
  .Lib9c.Tests/Action/CreateAvatar6Test.cs
  .Lib9c.Tests/Action/CreateAvatarTest.cs
  .Lib9c.Tests/Action/ExceptionTest.cs
  .Lib9c.Tests/Action/GrindingTest.cs
  .Lib9c.Tests/Model/Mail/GrindingMailTest.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/ClaimMonsterCollectionReward.cs
  Lib9c/Action/ClaimMonsterCollectionReward2.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Action/CombinationEquipment6.cs
  Lib9c/Action/CombinationEquipment7.cs
  Lib9c/Action/CombinationEquipment8.cs
  Lib9c/Action/CombinationEquipment9.cs
  Lib9c/Action/DailyReward.cs
  Lib9c/Action/DailyReward4.cs
  Lib9c/Action/DailyReward5.cs
  Lib9c/Action/Grinding.cs
  Lib9c/Action/InvalidEquipmentException.cs
  Lib9c/Action/ItemEnhancement.cs
  Lib9c/Action/ItemEnhancement7.cs
  Lib9c/Action/ItemEnhancement8.cs
  Lib9c/Action/RapidCombination.cs
  Lib9c/Action/RapidCombination4.cs
  Lib9c/Action/RapidCombination5.cs
  Lib9c/Action/Sell.cs
  Lib9c/Action/Sell7.cs
  Lib9c/Action/Sell8.cs
  Lib9c/Action/Sell9.cs
  Lib9c/Model/Mail/GrindingMail.cs
  Lib9c/Model/Mail/IMail.cs
  Lib9c/Model/Mail/Mail.cs
Labels: Large

#933 Update CRYSTAL decimalPlaces
  .Lib9c.Tests/Action/GrindingTest.cs
  .Lib9c.Tests/Model/Mail/GrindingMailTest.cs
  Lib9c/Action/Grinding.cs
Labels: Extra Small

#936 Check grinding equipment count
  .Lib9c.Tests/Action/GrindingTest.cs
  Lib9c/Action/Grinding.cs
Labels: Extra Small, CRYSTAL

#935 Introduce UnlockEquipmentRecipe MVP
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/ExceptionTest.cs
  .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
  Lib9c/Action/AlreadyRecipeUnlockedException.cs
  Lib9c/Action/InvalidRecipeIdException.cs
  Lib9c/Action/UnlockEquipmentRecipe.cs
Labels: Large, CRYSTAL

#943 Calculate cost using sheet data
  .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
  .Lib9c.Tests/CrystalCalculatorTest.cs
  .Lib9c.Tests/TableData/Item/EquipmentItemRecipeSheetTest.cs
  Lib9c/Action/UnlockEquipmentRecipe.cs
  Lib9c/Helper/CrystalCalculator.cs
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
  Lib9c/TableData/Item/EquipmentItemRecipeSheet.cs
Labels: Large, CRYSTAL

#942 Introduce CalculateCrystal
  .Lib9c.Tests/Action/GrindingTest.cs
  .Lib9c.Tests/TableData/Crystal/CrystalEquipmentGrindingSheetTest.cs
  .Lib9c.Tests/TableData/Crystal/CrystalMonsterCollectionMultiplierSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/Grinding.cs
  Lib9c/TableCSV/Crystal/CrystalEquipmentGrindingSheet.csv
  Lib9c/TableCSV/Crystal/CrystalMonsterCollectionMultiplierSheet.csv
  Lib9c/TableData/Crystal/CrystalEquipmentGrindingSheet.cs
  Lib9c/TableData/Crystal/CrystalMonsterCollectionMultiplierSheet.cs
Labels: Large, CRYSTAL

#939 CombinationEquipment Check CRYSTAL unlock
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  .Lib9c.Tests/Action/Scenario/CombinationAndRapidCombinationTest.cs
  Lib9c/Action/CombinationEquipment.cs
Labels: Large, CRYSTAL

#945 Fix extra fields of `RankingBattle`
  .Lib9c.Tests/Action/RankingBattleTest.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/RankingBattle.cs
  Lib9c/Model/State/ArenaInfo.cs
Labels: Medium

#944 Add empty recipe id case
  .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
  Lib9c/Action/UnlockEquipmentRecipe.cs
Labels: bug, Extra Small, CRYSTAL

#950 Merge `v100180` into the `development` branch
  .Lib9c.Tests/Action/RankingBattleTest.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/RankingBattle.cs
  Lib9c/Model/State/ArenaInfo.cs
Labels: Medium

#911 Remove proof-tx for permissioned mining
  .Lib9c.Tests/MinerTest.cs
  .Lib9c.Tests/Policy/BlockPolicyTest.cs
  Lib9c/Miner.cs
  Lib9c/Policy/BlockPolicySource.Utils.cs
  Lib9c/Policy/BlockPolicySource.cs
Labels: Medium

#948 Change grinding formula and push meta files of TableSheets.
  Lib9c/Action/Grinding.cs
  Lib9c/TableCSV/Crystal.meta
  Lib9c/TableCSV/Crystal/CrystalEquipmentGrindingSheet.csv.meta
  Lib9c/TableCSV/Crystal/CrystalMonsterCollectionMultiplierSheet.csv
  Lib9c/TableCSV/Crystal/CrystalMonsterCollectionMultiplierSheet.csv.meta
Labels: Extra Small, CRYSTAL

#947 Check previous recipe id by ItemSubType
  .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
  Lib9c/Action/UnlockEquipmentRecipe.cs
Labels: bug, Extra Small, CRYSTAL

#955 Transfer CRYSTAL instead of burn
  .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
  .Lib9c.Tests/Action/UnlockWorldTest.cs
  Lib9c/Action/UnlockEquipmentRecipe.cs
  Lib9c/Action/UnlockWorld.cs
  Lib9c/Addresses.cs
Labels: Extra Small, CRYSTAL

#952 Introduce `Stake` action
  .Lib9c.Tests/Action/StakeTest.cs
  .Lib9c.Tests/Model/State/StakeStateTest.cs
  .Lib9c.Tests/TableData/StakeAchievementRewardSheetTest.cs
  .Lib9c.Tests/TableData/StakeRegularRewardSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/Stake.cs
  Lib9c/Model/State/StakeState.cs
  Lib9c/SerializeKeys.cs
  Lib9c/TableCSV/StakeAchievementRewardSheet.csv
  Lib9c/TableCSV/StakeRegularRewardSheet.csv
  Lib9c/TableData/StakeAchievementRewardSheet.cs
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: Extra Large

#954 Filter inactive ArenaInfo when prepare next arena
  .Lib9c.Tests/Action/RewardGoldTest.cs
  Lib9c/Action/RewardGold.cs
Labels: Medium

#961 Fix previous recipe unlock check.
  .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
  .Lib9c.Tests/TableData/Item/EquipmentItemRecipeSheetTest.cs
  Lib9c/Action/UnlockEquipmentRecipe.cs
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
  Lib9c/TableData/Item/EquipmentItemRecipeSheet.cs
Labels: Extra Large, CRYSTAL

#958 Add summary to all of latest actions
  Lib9c/Action/Buy.cs
  Lib9c/Action/BuyMultiple.cs
  Lib9c/Action/CancelMonsterCollect.cs
  Lib9c/Action/ChargeActionPoint.cs
  Lib9c/Action/ClaimMonsterCollectionReward.cs
  Lib9c/Action/CombinationConsumable.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Action/CreateAvatar.cs
  Lib9c/Action/CreatePendingActivation.cs
  Lib9c/Action/CreatePendingActivations.cs
  Lib9c/Action/DailyReward.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/InitializeStates.cs
  Lib9c/Action/ItemEnhancement.cs
  Lib9c/Action/MigrationAvatarState.cs
  Lib9c/Action/MigrationLegacyShop.cs
  Lib9c/Action/MimisbrunnrBattle.cs
  Lib9c/Action/MonsterCollect.cs
  Lib9c/Action/PatchTableSheet.cs
  Lib9c/Action/RankingBattle.cs
  Lib9c/Action/RapidCombination.cs
  Lib9c/Action/RedeemCode.cs
  Lib9c/Action/RenewAdminState.cs
  Lib9c/Action/RewardGold.cs
  Lib9c/Action/Sell.cs
  Lib9c/Action/SellCancellation.cs
  Lib9c/Action/TransferAsset.cs
  Lib9c/Action/UpdateSell.cs
Labels: No Changes

#959 Obsolete RankingBattle10
  Lib9c/Action/RankingBattle10.cs
Labels: Extra Small

#963 Fix summary of `HackAndSlash`
  Lib9c/Action/HackAndSlash.cs
Labels: No Changes

#953 Fix the invokation order in unit tests
  .Lib9c.Tests/Model/RankingSimulatorTest.cs
Labels: Extra Small

#966 Revert "Merge pull request #952 from moreal/stake"
  .Lib9c.Tests/Action/StakeTest.cs
  .Lib9c.Tests/Model/State/StakeStateTest.cs
  .Lib9c.Tests/TableData/StakeAchievementRewardSheetTest.cs
  .Lib9c.Tests/TableData/StakeRegularRewardSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/Stake.cs
  Lib9c/Model/State/StakeState.cs
  Lib9c/SerializeKeys.cs
  Lib9c/TableCSV/StakeAchievementRewardSheet.csv
  Lib9c/TableCSV/StakeRegularRewardSheet.csv
  Lib9c/TableData/StakeAchievementRewardSheet.cs
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: Extra Large

#970 Add MailType.Grinding
  Lib9c/Model/Mail/GrindingMail.cs
  Lib9c/Model/Mail/Mail.cs
Labels: Extra Small, CRYSTAL

#962 Implement `ClaimStakeReward` action
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Model/State/StakeState.cs
  Lib9c/TableData/StakeAchievementRewardSheet.cs
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: Large
