Repository planetarium/lib9c, pull requests merged in 2022-01, with the labels that each got.

#815 Fix `RenewAdminState`'s deserialization issue
  .Lib9c.Tests/Action/RenewAdminStateTest.cs
  Lib9c/Action/RenewAdminState.cs
Labels: bug

#813 Delete genesis command
  .Lib9c.Tools/Lib9c.Tools.csproj
  .Lib9c.Tools/Program.cs
  .Lib9c.Tools/SubCommand/Account.cs
  .Lib9c.Tools/SubCommand/Genesis.cs
  .Lib9c.Tools/SubCommand/Market.cs
  .Lib9c.Tools/SubCommand/State.cs
  Lib9c.DevExtensions.Tests/Lib9c.DevExtensions.Tests.csproj
  Lib9c.DevExtensions.Tests/UtilsTest.cs
  Lib9c.DevExtensions/Lib9c.DevExtensions.csproj
  Lib9c.DevExtensions/Utils.cs
  Lib9c.sln
Labels: Medium

#825 Ignore DevExtensions.Tests in unity project
  .Lib9c.DevExtensions.Tests/Lib9c.DevExtensions.Tests.csproj
  .Lib9c.DevExtensions.Tests/UtilsTest.cs
  Lib9c.sln
Labels: No Changes

#827 [RC-v100100]Fix headless self contained build
  Lib9c.DevExtensions/Lib9c.DevExtensions.csproj
Labels: Extra Small

#828 [Development]Fix headless self contained build
  Lib9c.DevExtensions/Lib9c.DevExtensions.csproj
Labels: Extra Small

#807 Add `create-activation-keys` command
  .Lib9c.Tools/SubCommand/Tx.cs
Labels: Extra Small
