Repository planetarium/lib9c, pull requests merged in 2022-09, with the labels that each got.

#1347 Update worldboss skill sheets
  .Lib9c.Tests/Action/ClaimRaidRewardTest.cs
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossActionPatternSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossGlobalHpSheet.csv
Labels: Large

#1348 Fix 99 error
  Lib9c/Action/AccountStateDeltaExtensions.cs
Labels: Extra Small

#1349 Merge 2022q3-worldboss into worldboss-internal-test
  .Lib9c.Tests/Action/ClaimRaidRewardTest.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossActionPatternSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossGlobalHpSheet.csv
Labels: Large

#1350 Update World Boss Date
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossActionPatternSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossGlobalHpSheet.csv
Labels: Medium

#1351 Fixed World Boss ticket refill logic
  .Lib9c.Tests/Action/WorldBossHelperTest.cs
  Lib9c/Helper/WorldBossHelper.cs
Labels: Extra Large

#1352 Merge 2022q3 worldboss into worldboss-internal-test
  .Lib9c.Tests/Action/WorldBossHelperTest.cs
  Lib9c/Helper/WorldBossHelper.cs
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossActionPatternSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossGlobalHpSheet.csv
Labels: Medium

#1359 Rc v100290 to development
  .Lib9c.Tests/Action/HackAndSlashTest.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Helper/Validator.cs
Labels: Small

#1360 Check preivous execute block index in `Raid` action.
  .Lib9c.Tests/Action/RaidTest.cs
  Lib9c/Action/Raid.cs
  Lib9c/Model/State/RaiderState.cs
Labels: Small

#1361 Update boss 900001 balance
  .Lib9c.Tests/Action/ClaimRaidRewardTest.cs
  .Lib9c.Tests/Action/RaidTest.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossGlobalHpSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
Labels: Medium

#1362 fix exception handling in Block `#4374126`
  Lib9c/Action/HackAndSlashSweep4.cs
Labels: bug, Extra Small

#1372 Bug fixes in raid
  Lib9c/Action/Raid.cs
  Lib9c/Battle/RaidSimulator.cs
Labels: Extra Small

#1377 World Boss season block setting based on mainnet
  .Lib9c.Tests/Action/ClaimRaidRewardTest.cs
  .Lib9c.Tests/Action/RaidTest.cs
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
Labels: Extra Small

#1382 Introduce RequiredBlockIntervalException for render client exc
  .Lib9c.Tests/Action/ExceptionTest.cs
  .Lib9c.Tests/Action/RaidTest.cs
  Lib9c/Action/Raid.cs
  Lib9c/Action/RequiredBlockIntervalException.cs
Labels: Extra Small

#1383 Fix inventory notification
  .Lib9c.Tests/Model/ItemNotificationTest.cs
  Lib9c/Extensions/EquipmentExtensions.cs
  Lib9c/Model/Item/Inventory.cs
Labels: Medium

#1204 Improve `HackAndSlashTest` about selecting crystal random buff
  .Lib9c.Tests/Action/HackAndSlashTest.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Model/State/CrystalRandomSkillState.cs
Labels: Small

#1365 Add csv
  .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
  Lib9c/TableCSV/Character/CharacterSheet.csv
  Lib9c/TableCSV/Crystal/CrystalEquipmentGrindingSheet.csv
  Lib9c/TableCSV/Crystal/CrystalStageBuffGachaSheet.csv
  Lib9c/TableCSV/Item/ConsumableItemRecipeSheet.csv
  Lib9c/TableCSV/Item/ConsumableItemSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemOptionSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemSubRecipeSheetV2.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
  Lib9c/TableCSV/Quest/WorldQuestSheet.csv
  Lib9c/TableCSV/Skill/EnemySkillSheet.csv
  Lib9c/TableCSV/SweepRequiredCPSheet.csv
  Lib9c/TableCSV/WeeklyArenaRewardSheet.csv
  Lib9c/TableCSV/WorldAndStage/StageDialogSheet.csv
  Lib9c/TableCSV/WorldAndStage/StageSheet.csv
  Lib9c/TableCSV/WorldAndStage/StageWaveSheet.csv
  Lib9c/TableCSV/WorldAndStage/WorldSheet.csv
  Lib9c/TableCSV/WorldAndStage/WorldUnlockSheet.csv
Labels: Extra Large

#1387 Resolving test code errors
  .Lib9c.Tests/Action/ClaimRaidRewardTest.cs
  .Lib9c.Tests/Action/RaidTest.cs
Labels: Extra Small

#1388 Merge v100300 into development
  .Lib9c.Tests/Action/ClaimRaidRewardTest.cs
  .Lib9c.Tests/Action/ExceptionTest.cs
  .Lib9c.Tests/Action/RaidTest.cs
  Lib9c/Action/Raid.cs
  Lib9c/Action/RequiredBlockIntervalException.cs
Labels: Extra Small

#1389 Prevent adding duplicated dead log in battle.
  Lib9c/Model/Character/CharacterBase.cs
Labels: Extra Small

#1386 Support prepare reward asssets
  .Lib9c.Tools/SubCommand/Tx.cs
Labels: Extra Small

#1396 Fix world boss challenge refill interval
  .Lib9c.Tests/Action/WorldBossHelperTest.cs
  Lib9c/Helper/WorldBossHelper.cs
Labels: Extra Small

#1398 Development merge v100301
  .Lib9c.Tests/Action/WorldBossHelperTest.cs
  .Lib9c.Tools/SubCommand/Tx.cs
  Lib9c/Helper/WorldBossHelper.cs
Labels: Extra Small

#1407 Make `transfer_asset*` actions implement common interface
  Lib9c/Action/ITransferAsset.cs
  Lib9c/Action/TransferAsset.cs
  Lib9c/Action/TransferAsset0.cs
  Lib9c/Action/TransferAsset2.cs
Labels: Extra Small

#1408 Obsolete Lib9c.tools with warning message
  .Lib9c.Tools/Program.cs
  .Lib9c.Tools/SubCommand/Account.cs
  .Lib9c.Tools/SubCommand/Action.cs
  .Lib9c.Tools/SubCommand/Market.cs
  .Lib9c.Tools/SubCommand/State.cs
  .Lib9c.Tools/SubCommand/Tx.cs
Labels: enhancement, Extra Small

#1403 Fix InvalidBlockStateRootHashException
  .Lib9c.Tests/Action/BattleArena4Test.cs
  .Lib9c.Tests/Action/EventDungeonBattleTest.cs
  .Lib9c.Tests/Action/EventDungeonBattleV1Test.cs
  .Lib9c.Tests/Action/HackAndSlash12Test.cs
  .Lib9c.Tests/Action/HackAndSlash13Test.cs
  .Lib9c.Tests/Action/HackAndSlash15Test.cs
  .Lib9c.Tests/Action/HackAndSlash16Test.cs
  .Lib9c.Tests/Action/HackAndSlash17Test.cs
  .Lib9c.Tests/Action/HackAndSlashTest.cs
  .Lib9c.Tests/Action/MimisbrunnrBattleTest.cs
  .Lib9c.Tests/Action/RankingBattle10Test.cs
  .Lib9c.Tests/Action/RankingBattle11Test.cs
  .Lib9c.Tests/Action/RankingBattleTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/ActionBase.cs
  Lib9c/Action/BattleArena1.cs
  Lib9c/Action/BattleArena2.cs
  Lib9c/Action/BattleArena3.cs
  Lib9c/Action/BattleArena4.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Action/EventDungeonBattleV1.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlash12.cs
  Lib9c/Action/HackAndSlash13.cs
  Lib9c/Action/HackAndSlash14.cs
  Lib9c/Action/HackAndSlash15.cs
  Lib9c/Action/HackAndSlash16.cs
  Lib9c/Action/HackAndSlash17.cs
  Lib9c/Action/MimisbrunnrBattle.cs
  Lib9c/Action/RankingBattle.cs
  Lib9c/Action/RankingBattle10.cs
  Lib9c/Action/RankingBattle11.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/Policy/BlockPolicySource.cs
  Lib9c/TableCSV/Skill/BuffSheet.csv
  Lib9c/TableData/SimulatorSheetsV100291.cs
  Lib9c/TableData/Skill/BuffSheet.cs
Labels: Extra Large

#1200 Suggestion: Snapshot Testing
  .Lib9c.Tests/Action/Snapshot/ActionUtils.cs
  .Lib9c.Tests/Action/Snapshot/TransferAsset0SnapshotTest.cs
  .Lib9c.Tests/Action/Snapshot/transfer_asset.PlainValue.verified.txt
  .Lib9c.Tests/Action/Snapshot/transfer_asset.TransferCrystal.verified.txt
  .Lib9c.Tests/Action/Snapshot/transfer_asset.TransferWithMemo.verified.txt
  .Lib9c.Tests/Lib9c.Tests.csproj
Labels: Large
