Repository planetarium/lib9c, pull requests merged in 2022-10, with the labels that each got.

#1414 main Rc v100302
  .Lib9c.Tests/Action/BattleArena4Test.cs
  .Lib9c.Tests/Action/EventDungeonBattleTest.cs
  .Lib9c.Tests/Action/EventDungeonBattleV1Test.cs
  .Lib9c.Tests/Action/HackAndSlash12Test.cs
  .Lib9c.Tests/Action/HackAndSlash13Test.cs
  .Lib9c.Tests/Action/HackAndSlash15Test.cs
  .Lib9c.Tests/Action/HackAndSlash16Test.cs
  .Lib9c.Tests/Action/HackAndSlash17Test.cs
  .Lib9c.Tests/Action/HackAndSlashTest.cs
  .Lib9c.Tests/Action/MimisbrunnrBattleTest.cs
  .Lib9c.Tests/Action/RankingBattle10Test.cs
  .Lib9c.Tests/Action/RankingBattle11Test.cs
  .Lib9c.Tests/Action/RankingBattleTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/ActionBase.cs
  Lib9c/Action/BattleArena1.cs
  Lib9c/Action/BattleArena2.cs
  Lib9c/Action/BattleArena3.cs
  Lib9c/Action/BattleArena4.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Action/EventDungeonBattleV1.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlash12.cs
  Lib9c/Action/HackAndSlash13.cs
  Lib9c/Action/HackAndSlash14.cs
  Lib9c/Action/HackAndSlash15.cs
  Lib9c/Action/HackAndSlash16.cs
  Lib9c/Action/HackAndSlash17.cs
  Lib9c/Action/MimisbrunnrBattle.cs
  Lib9c/Action/RankingBattle.cs
  Lib9c/Action/RankingBattle10.cs
  Lib9c/Action/RankingBattle11.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/Policy/BlockPolicySource.cs
  Lib9c/TableCSV/Skill/BuffSheet.csv
  Lib9c/TableData/SimulatorSheetsV100291.cs
  Lib9c/TableData/Skill/BuffSheet.cs
Labels: Extra Large

#1416 Fix/valid validators policy
  Lib9c/Policy/BlockPolicySource.cs
Labels: Extra Small, pbft

#1417 Merge v100302 into dev
  .Lib9c.Tests/Action/BattleArena4Test.cs
  .Lib9c.Tests/Action/EventDungeonBattleTest.cs
  .Lib9c.Tests/Action/EventDungeonBattleV1Test.cs
  .Lib9c.Tests/Action/HackAndSlash12Test.cs
  .Lib9c.Tests/Action/HackAndSlash13Test.cs
  .Lib9c.Tests/Action/HackAndSlash15Test.cs
  .Lib9c.Tests/Action/HackAndSlash16Test.cs
  .Lib9c.Tests/Action/HackAndSlash17Test.cs
  .Lib9c.Tests/Action/HackAndSlashTest.cs
  .Lib9c.Tests/Action/MimisbrunnrBattleTest.cs
  .Lib9c.Tests/Action/RankingBattle10Test.cs
  .Lib9c.Tests/Action/RankingBattle11Test.cs
  .Lib9c.Tests/Action/RankingBattleTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/ActionBase.cs
  Lib9c/Action/BattleArena1.cs
  Lib9c/Action/BattleArena2.cs
  Lib9c/Action/BattleArena3.cs
  Lib9c/Action/BattleArena4.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Action/EventDungeonBattleV1.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlash12.cs
  Lib9c/Action/HackAndSlash13.cs
  Lib9c/Action/HackAndSlash14.cs
  Lib9c/Action/HackAndSlash15.cs
  Lib9c/Action/HackAndSlash16.cs
  Lib9c/Action/HackAndSlash17.cs
  Lib9c/Action/MimisbrunnrBattle.cs
  Lib9c/Action/RankingBattle.cs
  Lib9c/Action/RankingBattle10.cs
  Lib9c/Action/RankingBattle11.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/Policy/BlockPolicySource.cs
  Lib9c/TableCSV/Skill/BuffSheet.csv
  Lib9c/TableData/SimulatorSheetsV100291.cs
  Lib9c/TableData/Skill/BuffSheet.cs
Labels: Extra Large

#1424 Minimize permission to handle states
  .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
  .Lib9c.Tests/Action/AccountStateViewExtensionsTest.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/AccountStateViewExtensions.cs
Labels: suggestion, Extra Large

#1420 Update debug log for `InvalidBlockStateRootHashException` debugging
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/Buy.cs
  Lib9c/Action/BuyMultiple.cs
  Lib9c/Action/CancelMonsterCollect.cs
  Lib9c/Action/ChargeActionPoint.cs
  Lib9c/Action/ClaimMonsterCollectionReward.cs
  Lib9c/Action/ClaimRaidReward.cs
  Lib9c/Action/CombinationConsumable.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Action/CreateAvatar.cs
  Lib9c/Action/DailyReward.cs
  Lib9c/Action/Grinding.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlashRandomBuff.cs
  Lib9c/Action/HackAndSlashSweep.cs
  Lib9c/Action/ItemEnhancement.cs
  Lib9c/Action/JoinArena.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Action/MimisbrunnrBattle.cs
  Lib9c/Action/MonsterCollect.cs
  Lib9c/Action/Raid.cs
  Lib9c/Action/RankingBattle.cs
  Lib9c/Action/RapidCombination.cs
  Lib9c/Action/RedeemCode.cs
  Lib9c/Action/RewardGold.cs
  Lib9c/Action/Sell.cs
  Lib9c/Action/SellCancellation.cs
  Lib9c/Action/Stake.cs
  Lib9c/Action/TransferAsset.cs
  Lib9c/Action/TransferAsset2.cs
  Lib9c/Action/UnlockEquipmentRecipe.cs
  Lib9c/Action/UnlockWorld.cs
  Lib9c/Action/UpdateSell.cs
Labels: Medium

#1429 Add BuffSheet.csv.meta
  Lib9c/TableCSV/Skill/BuffSheet.csv.meta
Labels: Extra Small

#1427 Update Patch Table 2022-10-14
  .Lib9c.Tests/Action/ArenahelperTest.cs
  .Lib9c.Tests/TableData/ArenaSheetTest.cs
  Lib9c/TableCSV/Arena/ArenaSheet.csv
  Lib9c/TableCSV/WorldAndStage/StageSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
Labels: Medium

#1430 championship 1 ranker title added
  Lib9c/TableCSV/Item/CostumeItemSheet.csv
  Lib9c/TableCSV/Item/CostumeStatSheet.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
Labels: Extra Small

#1439 Test validator key and policy added
  Lib9c/Policy/BlockPolicySource.cs
  Lib9c/Policy/ValidatorsPolicy.cs
Labels: Extra Small

#1442 fix GetHighestRankSkill
  Lib9c/Model/State/CrystalRandomSkillState.cs
Labels: Extra Small

#1445 Update `V100310ObsoleteIndex`
  Lib9c/Policy/BlockPolicySource.cs
Labels: Extra Small

#1448 Handling v100302~v100310/Simulator
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/MimisbrunnrBattle.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Policy/BlockPolicySource.cs
Labels: Small

#1446 Use GPL v3.0 LICENSE
  LICENSE
Labels: Extra Large

#1449 Merge rc-v100311 to main
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/MimisbrunnrBattle.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Policy/BlockPolicySource.cs
Labels: Small

#1450 Introduce RuneEnhancement
  .Lib9c.Tests/Action/RuneEnhancementTest.cs
  .Lib9c.Tests/TableData/RuneCostSheetTest.cs
  .Lib9c.Tests/TableData/RuneListSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/RuneEnhancement.cs
  Lib9c/Addresses.cs
  Lib9c/Helper/RuneHelper.cs
  Lib9c/Model/EnumType/Grade.cs
  Lib9c/Model/EnumType/RuneType.cs
  Lib9c/Model/EnumType/RuneUsePlace.cs
  Lib9c/Model/Rune/RuneExceptions.cs
  Lib9c/Model/State/RuneState.cs
  Lib9c/TableCSV/RuneCostSheet.csv
  Lib9c/TableCSV/RuneCostSheet.csv.meta
  Lib9c/TableCSV/RuneListSheet.csv
  Lib9c/TableCSV/RuneListSheet.csv.meta
  Lib9c/TableCSV/RuneSheet.csv
  Lib9c/TableData/RuneCostSheet.cs
  Lib9c/TableData/RuneListSheet.cs
Labels: Extra Large

#1453 Introduce rune slot content
  .Lib9c.Tests/Action/EquipRuneTest.cs
  .Lib9c.Tests/Action/RuneEnhancementTest.cs
  .Lib9c.Tests/Model/Rune/RuneSlotTest.cs
  .Lib9c.Tests/Model/RuneSlotStateTest.cs
  Lib9c/Action/EquipRune.cs
  Lib9c/Action/RuneSlotInfo.cs
  Lib9c/Helper/RuneHelper.cs
  Lib9c/Model/EnumType/BattleType.cs
  Lib9c/Model/EnumType/RuneSlotType.cs
  Lib9c/Model/Rune/RuneExceptions.cs
  Lib9c/Model/Rune/RuneSlot.cs
  Lib9c/Model/State/RuneSlotState.cs
Labels: Extra Large
