Repository planetarium/lib9c, pull requests merged in 2022-02, with the labels that each got.

#832 Optimize miner to append block
  Lib9c/Miner.cs
Labels: Extra Small

#839 Add additional actions
  Lib9c/BlockHelper.cs
Labels: Extra Small

#842 Added functions for item level system
  Lib9c/Model/Elemental/ElementalType.cs
  Lib9c/Model/Stat/CharacterStats.cs
Labels: Extra Small

#848 update Secp256k1 to support arm64
  Lib9c/Lib9c.csproj
Labels: Extra Small

#849 Revert 842
  Lib9c/Model/Elemental/ElementalType.cs
  Lib9c/Model/Stat/CharacterStats.cs
Labels: Extra Small

#850 Use `IAccountStateDelta.GetStates(addresses)` in action
  Lib9c/Action/AccountStateDeltaExtensions.cs
Labels: Extra Small

#851 item-level-system-data
  .Lib9c.Tests/Action/Common/Doomfist.cs
  .Lib9c.Tests/Action/HackAndSlash10Test.cs
  .Lib9c.Tests/Action/HackAndSlash11Test.cs
  .Lib9c.Tests/Action/HackAndSlash7Test.cs
  .Lib9c.Tests/Action/HackAndSlash8Test.cs
  .Lib9c.Tests/Action/HackAndSlash9Test.cs
  .Lib9c.Tests/Action/HackAndSlashTest.cs
  .Lib9c.Tests/Action/MimisbrunnrBattleTest.cs
  .Lib9c.Tests/Action/RankingBattleTest.cs
  .Lib9c.Tests/Action/Scenario/WorldUnlockScenarioTest.cs
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
Labels: Extra Large

#816 test: create pending activations with renew admin state
  .Lib9c.Tests/Action/RenewAdminStateTest.cs
Labels: Extra Small

#854 [Bot] Merge rc-v100110 to development
  Lib9c/Model/Elemental/ElementalType.cs
  Lib9c/Model/Stat/CharacterStats.cs
Labels: Extra Small

#855 Change specification of `IsMadeWithMimisbrunnrRecipe`
  Lib9c/Extensions/EquipmentExtensions.cs
Labels: Extra Small

#833 Weekly arena raw dict
  Lib9c/Action/RankingBattle.cs
Labels: Extra Small

#859 Weekly arena raw dict
  Lib9c/Action/RankingBattle.cs
Labels: Extra Small

#858 Revert "Weekly arena raw dict"
  Lib9c/Action/RankingBattle.cs
Labels: Extra Small

#862 arena season2 data
  .Lib9c.Tests/Action/ClaimMonsterCollectionReward2Test.cs
  .Lib9c.Tests/Action/ClaimMonsterCollectionRewardTest.cs
  .Lib9c.Tests/Model/Mail/MonsterCollectMailTest.cs
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
  Lib9c/TableCSV/MonsterCollectionRewardSheet.csv
  Lib9c/TableCSV/WeeklyArenaRewardSheet.csv
Labels: Small
