Repository planetarium/lib9c, pull requests merged in 2022-05, with the labels that each got.

#977 Revert "Merge pull request #962 from moreal/claim-stake-reward"
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Model/State/StakeState.cs
  Lib9c/TableData/StakeAchievementRewardSheet.cs
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: Large

#975 Merge main(`v100190`) to development
  .Lib9c.Tests/Action/StakeTest.cs
  .Lib9c.Tests/Model/State/StakeStateTest.cs
  .Lib9c.Tests/TableData/StakeAchievementRewardSheetTest.cs
  .Lib9c.Tests/TableData/StakeRegularRewardSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/Stake.cs
  Lib9c/Model/State/StakeState.cs
  Lib9c/Policy/MinTransactionsPerBlockPolicy.cs
  Lib9c/SerializeKeys.cs
  Lib9c/TableCSV/StakeAchievementRewardSheet.csv
  Lib9c/TableCSV/StakeRegularRewardSheet.csv
  Lib9c/TableData/StakeAchievementRewardSheet.cs
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: Extra Large

#976 Restore #952 from moreal/stake
  .Lib9c.Tests/Action/StakeTest.cs
  .Lib9c.Tests/Model/State/StakeStateTest.cs
  .Lib9c.Tests/TableData/StakeAchievementRewardSheetTest.cs
  .Lib9c.Tests/TableData/StakeRegularRewardSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/Stake.cs
  Lib9c/Model/State/StakeState.cs
  Lib9c/SerializeKeys.cs
  Lib9c/TableCSV/StakeAchievementRewardSheet.csv
  Lib9c/TableCSV/StakeRegularRewardSheet.csv
  Lib9c/TableData/StakeAchievementRewardSheet.cs
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: Extra Large

#978 Restore `moreal/claim-stake-reward`
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Model/State/StakeState.cs
  Lib9c/TableData/StakeAchievementRewardSheet.cs
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: Large

#974 charge ap in Grinding action
  .Lib9c.Tests/Action/GrindingTest.cs
  Lib9c/Action/Grinding.cs
  Lib9c/Model/Item/Inventory.cs
Labels: Small, CRYSTAL

#980 Restore IsAuthorizedMinerTransactionRaw
  Lib9c/Policy/BlockPolicySource.Utils.cs
  Lib9c/Policy/BlockPolicySource.cs
Labels: Extra Small

#982 Merge rc-v100192 to main
  Lib9c/Policy/BlockPolicySource.Utils.cs
  Lib9c/Policy/BlockPolicySource.cs
Labels: Extra Small

#985 Merge v100192 to development
  Lib9c/Policy/BlockPolicySource.Utils.cs
  Lib9c/Policy/BlockPolicySource.cs
Labels: Extra Small

#979 Introduce CrystalMaterialCostSheet
  .Lib9c.Tests/TableData/Crystal/CrystalMaterialCostSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/TableCSV/Crystal/CrystalMaterialCostSheet.csv
  Lib9c/TableData/Crystal/CrystalMaterialCostSheet.cs
Labels: Medium, CRYSTAL

#991 pay CRYSTAL instead of material in CombinationEquipment
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Addresses.cs
  Lib9c/TableCSV/Crystal/CrystalMaterialCostSheet.csv
Labels: Medium, CRYSTAL

#973 More tests to check `Stake` & `ClaimStakeReward` not registered yet
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
Labels: Extra Small

#984 Remove benchmark CI
  .github/workflows/benchmark.yml
Labels: Extra Small

#969 Move to .NET 6
  .Lib9c.Benchmarks/Lib9c.Benchmarks.csproj
  .Lib9c.DevExtensions.Tests/Lib9c.DevExtensions.Tests.csproj
  .Lib9c.Tests/Lib9c.Tests.csproj
  .Lib9c.Tools.Tests/Lib9c.Tools.Tests.csproj
  .Lib9c.Tools/Lib9c.Tools.csproj
  .github/workflows/main.yml
  .github/workflows/publish.yml
  global.json
Labels: enhancement, suggestion, ci, Extra Small

#983 Introduce `MigrateMonsterCollection` action
  .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
  Lib9c/Action/MigrateMonsterCollection.cs
Labels: Medium

#1001 Revert pull requests related to `Stake` for splitting branch
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
  .Lib9c.Tests/Model/State/StakeStateTest.cs
  .Lib9c.Tests/TableData/StakeAchievementRewardSheetTest.cs
  .Lib9c.Tests/TableData/StakeRegularRewardSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Action/Stake.cs
  Lib9c/Model/State/StakeState.cs
  Lib9c/SerializeKeys.cs
  Lib9c/TableCSV/StakeAchievementRewardSheet.csv
  Lib9c/TableCSV/StakeRegularRewardSheet.csv
  Lib9c/TableData/StakeAchievementRewardSheet.cs
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: Extra Large

#998 Fix crystal summary of enchanted equipment
  .Lib9c.Tests/Action/GrindingTest.cs
  .Lib9c.Tests/Action/ItemEnhancementTest.cs
  .Lib9c.Tests/CrystalCalculatorTest.cs
  Lib9c/Helper/CrystalCalculator.cs
  Lib9c/Lib9c.csproj
  Lib9c/Lib9c.ruleset
  Lib9c/TableCSV/Crystal/CrystalEquipmentGrindingSheet.csv
  Lib9c/TableData/Crystal/CrystalEquipmentGrindingSheet.cs
Labels: Large, CRYSTAL

#1003 Merge staking features to 2022q2
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
  .Lib9c.Tests/Model/State/StakeStateTest.cs
  .Lib9c.Tests/TableData/StakeAchievementRewardSheetTest.cs
  .Lib9c.Tests/TableData/StakeRegularRewardSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Action/Stake.cs
  Lib9c/Model/State/StakeState.cs
  Lib9c/SerializeKeys.cs
  Lib9c/TableCSV/StakeAchievementRewardSheet.csv
  Lib9c/TableCSV/StakeRegularRewardSheet.csv
  Lib9c/TableData/StakeAchievementRewardSheet.cs
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: Extra Large

#1010 Make stake actions polymorphic
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
  Lib9c/Action/ClaimMonsterCollectionReward.cs
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Action/MonsterCollect.cs
  Lib9c/Action/Stake.cs
Labels: Extra Small

#1012 Fix sonar warning
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/Buy5Test.cs
  .Lib9c.Tests/Action/Buy6Test.cs
  .Lib9c.Tests/Action/Buy7Test.cs
  .Lib9c.Tests/Action/Buy8Test.cs
  .Lib9c.Tests/Action/Buy9Test.cs
  .Lib9c.Tests/Action/BuyMultipleTest.cs
  .Lib9c.Tests/Action/BuyTest.cs
  .Lib9c.Tests/Action/Common/Doomfist.cs
  .Lib9c.Tests/Action/DailyReward5Test.cs
  .Lib9c.Tests/Action/RankingBattle0Test.cs
  .Lib9c.Tests/Action/RankingBattle10Test.cs
  .Lib9c.Tests/Action/RankingBattle11Test.cs
  .Lib9c.Tests/Action/RankingBattle4Test.cs
  .Lib9c.Tests/Action/RankingBattle5Test.cs
  .Lib9c.Tests/Action/RankingBattle6Test.cs
  .Lib9c.Tests/Action/RankingBattle7Test.cs
  .Lib9c.Tests/Action/RankingBattle8Test.cs
  .Lib9c.Tests/Action/RankingBattle9Test.cs
  .Lib9c.Tests/Action/RankingBattleTest.cs
  .Lib9c.Tests/Action/State.cs
Labels: Extra Small

#1020 Introduce `BlockPolicySource.GetDefaultPolicy()` method
  Lib9c/Policy/BlockPolicySource.cs
Labels: Extra Small

#1019 Introduce CRYSTAL price fluctuation MVP
  .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  .Lib9c.Tests/CrystalCalculatorTest.cs
  .Lib9c.Tests/Model/State/CrystalCostStateTest.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Addresses.cs
  Lib9c/Helper/CrystalCalculator.cs
  Lib9c/Model/State/CrystalCostState.cs
Labels: Large, CRYSTAL

#1023 fix zero division inconsistency between amd and arm architecture
  Lib9c/Helper/AvatarStateExtensions.cs
Labels: Extra Small

#1027 Introduce JoinArena action
  .Lib9c.Tests/Action/JoinArenaTest.cs
  .Lib9c.Tests/Model/Arena/ArenaAvatarStateTest.cs
  .Lib9c.Tests/Model/Arena/ArenaInformationTest.cs
  .Lib9c.Tests/Model/Arena/ArenaParticipantsTest.cs
  .Lib9c.Tests/Model/Arena/ArenaScoreTest.cs
  .Lib9c.Tests/TableData/ArenaSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/JoinArena.cs
  Lib9c/Action/NotEnoughMedalException.cs
  Lib9c/Addresses.cs
  Lib9c/Arena/ArenaHelper.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/Helper/AvatarStateExtensions.cs
  Lib9c/Model/Arena/ArenaExceptions.cs
  Lib9c/Model/Arena/ArenaInformation.cs
  Lib9c/Model/Arena/ArenaParticipants.cs
  Lib9c/Model/Arena/ArenaScore.cs
  Lib9c/Model/EnumType/ArenaType.cs
  Lib9c/Model/State/ArenaAvatarState.cs
  Lib9c/TableCSV/Arena.meta
  Lib9c/TableCSV/Arena/ArenaSheet.csv
  Lib9c/TableCSV/Arena/ArenaSheet.csv.meta
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
  Lib9c/TableData/ArenaSheet.cs
  Lib9c/TableData/Exceptions.cs
  Lib9c/TableData/SimulatorSheets.cs
Labels: Extra Large

#1025 Fix first stage sweep bug
  .Lib9c.Tests/Action/HackAndSlashSweepTest.cs
  .Lib9c.Tests/Action/HackAndSlashSweepTest3.cs
  Lib9c/Action/HackAndSlashSweep.cs
Labels: bug, Small

#986 Make `ClaimStakeReward` give accumulated staking rewards
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Action/Stake.cs
  Lib9c/Model/State/StakeState.cs
  Lib9c/TableCSV/StakeRegularRewardSheet.csv
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: Extra Large

#1033 Fix StakeAchievementRewardSheet.FindLevel minimum required gold case
  .Lib9c.Tests/TableData/StakeAchievementRewardSheetTest.cs
  Lib9c/TableData/StakeAchievementRewardSheet.cs
Labels: bug, Extra Small

#1034 pull stake
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
  .Lib9c.Tests/TableData/StakeAchievementRewardSheetTest.cs
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Action/Stake.cs
  Lib9c/Model/State/StakeState.cs
  Lib9c/TableCSV/StakeRegularRewardSheet.csv
  Lib9c/TableData/StakeAchievementRewardSheet.cs
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: Extra Large

#1032 arena-season3-costume data added
  Lib9c/TableCSV/Item/CostumeItemSheet.csv
  Lib9c/TableCSV/Item/CostumeStatSheet.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
Labels: Extra Small

#1035 Add new permissioned miners in `Previewnet`
  Lib9c/Policy/PermanentBlockPolicySource.cs
Labels: Extra Small

#1038 Introduce `HackAndSlashBuffState`
  .Lib9c.Tests/CrystalCalculatorTest.cs
  .Lib9c.Tests/Model/State/HackAndSlashBuffStateTest.cs
  .Lib9c.Tests/TableData/Crystal/CrystalRandomBuffSheetTest.cs
  .Lib9c.Tests/TableData/Crystal/CrystalStageBuffGachaSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Helper/CrystalCalculator.cs
  Lib9c/Model/State/HackAndSlashBuffState.cs
  Lib9c/TableCSV/Crystal/CrystalRandomBuffSheet.csv
  Lib9c/TableCSV/Crystal/CrystalRandomBuffSheet.csv.meta
  Lib9c/TableCSV/Crystal/CrystalStageBuffGachaSheet.csv
  Lib9c/TableCSV/Crystal/CrystalStageBuffGachaSheet.csv.meta
  Lib9c/TableData/Crystal/CrystalRandomBuffSheet.cs
  Lib9c/TableData/Crystal/CrystalStageBuffGachaSheet.cs
Labels: Extra Large, CRYSTAL

#1046 MonsterCollection RegularRewardSheet updated
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/TableCSV/StakeRegularRewardSheet.csv
Labels: Extra Small

#1049 Clean up useless check in `ClaimStakeRewardTest`
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
Labels: Extra Small

#1050 Merge `features/stake` into `2022q2`
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
Labels: Extra Small

#1029 Introduce BattleArena action
  .Lib9c.Tests/Action/BattleArenaTest.cs
  .Lib9c.Tests/Model/Arena/ArenaPlayerDigestTest.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Arena/ArenaHelper.cs
  Lib9c/Arena/ArenaSimulator.cs
  Lib9c/Model/Arena/ArenaInformation.cs
  Lib9c/Model/Arena/ArenaPlayerDigest.cs
  Lib9c/Model/Character/EnemyPlayer.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Model/State/AvatarState.cs
  Lib9c/SerializeKeys.cs
  Lib9c/TableData/ArenaSheet.cs
Labels: Extra Large

#1053 Bugfix/find level balance
  .Lib9c.Tests/TableData/StakeAchievementRewardSheetTest.cs
  .Lib9c.Tests/TableData/StakeRegularRewardSheetTest.cs
  Lib9c/Action/Stake.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/TableData/IStakeRewardRow.cs
  Lib9c/TableData/IStakeRewardSheet.cs
  Lib9c/TableData/StakeAchievementRewardSheet.cs
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: bug, Medium

#1057 Do not fetch unused sheet
  Lib9c/Action/Stake.cs
Labels: bug, Extra Small

#1058 Merge `2022q2` to `previewnet`
  Lib9c/Action/Stake.cs
Labels: Extra Small

#1043 Arena-season3-costume ItemRequirementSheet additional added
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
Labels: Extra Small

#1042 Update RedeemRewardSheet for Arena season3
  Lib9c/TableCSV/RedeemRewardSheet.csv
Labels: Extra Small

#1061 Add `CalculateMaterialCost` to 2022q2
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  .Lib9c.Tests/CrystalCalculatorTest.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Helper/CrystalCalculator.cs
  Lib9c/TableCSV/Crystal/CrystalMaterialCostSheet.csv.meta
  Lib9c/TableCSV/StakeAchievementRewardSheet.csv.meta
  Lib9c/TableCSV/StakeRegularRewardSheet.csv.meta
Labels: Small, CRYSTAL

#1063 Make `MigrateMonsterCollection` action as polymorphic
  .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
  Lib9c/Action/MigrateMonsterCollection.cs
Labels: bug, Extra Small

#1064 Make `MigrateMonsterCollection` action as polymorphic
  .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
  Lib9c/Action/MigrateMonsterCollection.cs
Labels: bug, Extra Small

#1065 Merge `2022q2` to `previewnet`
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
  .Lib9c.Tests/CrystalCalculatorTest.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Helper/CrystalCalculator.cs
  Lib9c/TableCSV/Crystal/CrystalMaterialCostSheet.csv.meta
  Lib9c/TableCSV/StakeAchievementRewardSheet.csv.meta
  Lib9c/TableCSV/StakeRegularRewardSheet.csv.meta
Labels: Small

#1062 Update arena avatar state level in BattleArena action
  Lib9c/Action/BattleArena.cs
Labels: Extra Small

#1056 Added reboot arena scenario test
  .Lib9c.Tests/Action/BattleArenaTest.cs
  .Lib9c.Tests/Action/Scenario/ArenaScenarioTest.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Arena/ArenaHelper.cs
  Lib9c/Battle/HitHelper.cs
  Lib9c/TableCSV/Arena/ArenaSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
Labels: Large

#1066 Improve ArenaSheet
  .Lib9c.Tests/Action/BattleArenaTest.cs
  .Lib9c.Tests/Action/JoinArenaTest.cs
  .Lib9c.Tests/Action/Scenario/ArenaScenarioTest.cs
  .Lib9c.Tests/TableData/ArenaSheetTest.cs
  .Lib9c.Tests/TableSheetsImporter.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/JoinArena.cs
  Lib9c/Arena/ArenaHelper.cs
  Lib9c/TableCSV/Arena/ArenaSheet.csv
  Lib9c/TableData/ArenaSheet.cs
Labels: Large

#1071 Version up GetLevelAndExp()
  .Lib9c.Tests/Action/HackAndSlashSweepTest1.cs
  .Lib9c.Tests/Action/HackAndSlashSweepTest2.cs
  .Lib9c.Tests/Action/HackAndSlashSweepTest3.cs
  Lib9c/Action/HackAndSlashSweep1.cs
  Lib9c/Action/HackAndSlashSweep2.cs
  Lib9c/Action/HackAndSlashSweep3.cs
  Lib9c/Helper/AvatarStateExtensions.cs
Labels: bug, Extra Small

#1070 Update Lib9c.DevExtensions.csproj
  Lib9c.DevExtensions/Lib9c.DevExtensions.csproj
Labels: Extra Small

#1072 revomon costume data removed
  Lib9c/TableCSV/Item/CostumeItemSheet.csv
Labels: Extra Small

#1073 Avoid to add items with zero count
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  Lib9c/Action/ClaimStakeReward.cs
Labels: bug

#1068 Improve/grinding check staking state
  .Lib9c.Tests/Action/GrindingTest.cs
  .Lib9c.Tests/Action/ItemEnhancementTest.cs
  .Lib9c.Tests/Action/JoinArenaTest.cs
  .Lib9c.Tests/CrystalCalculatorTest.cs
  .Lib9c.Tests/Extensions/SheetsExtensionsTest.cs
  Lib9c/Action/Grinding.cs
  Lib9c/Action/ItemEnhancement.cs
  Lib9c/Helper/CrystalCalculator.cs
Labels: Large, CRYSTAL

#1074 Feature/crystal price fluctuation sheet
  .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  .Lib9c.Tests/CrystalCalculatorTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Helper/CrystalCalculator.cs
  Lib9c/Model/State/CrystalCostState.cs
  Lib9c/TableCSV/Crystal/CrystalFluctuationSheet.csv
  Lib9c/TableData/Crystal/CrystalFluctuationSheet.cs
Labels: Small
