Repository planetarium/lib9c, pull requests merged in 2022-11, with the labels that each got.

#1465 Use `ByteArray` instead of `ToByteArray()` when appropriate
  Lib9c/Model/State/StateExtensions.cs
Labels: Extra Small

#1444 Merge v100310 into dev
  Lib9c/Model/State/CrystalRandomSkillState.cs
Labels: Extra Small

#1464 Hardfork BattleArena to "battle_arena6"
  .Lib9c.Tests/Action/ArenahelperTest.cs
  .Lib9c.Tests/Action/BattleArena2Test.cs
  .Lib9c.Tests/Action/BattleArena3Test.cs
  .Lib9c.Tests/Action/BattleArena4Test.cs
  .Lib9c.Tests/Action/BattleArena5Test.cs
  .Lib9c.Tests/Action/BattleArenaTest.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/BattleArena2.cs
  Lib9c/Action/BattleArena3.cs
  Lib9c/Action/BattleArena4.cs
  Lib9c/Action/BattleArena5.cs
  Lib9c/Arena/ArenaHelper.cs
  Lib9c/Model/Arena/ArenaExceptions.cs
  Lib9c/Model/Arena/ArenaInformation.cs
  Lib9c/Policy/BlockPolicySource.cs
  Lib9c/TableCSV/Arena/ArenaSheet.csv
  Lib9c/TableData/ArenaSheet.cs
Labels: Large

#1468 add Rune Skill Stat Buff
  Lib9c/TableCSV/Rune/RuneStatSheet.csv
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableData/Rune/RuneStatSheet.cs
Labels: Extra Small

#1457 Attach skills on rune
  .Lib9c.Tests/Action/EventDungeonBattleV2Test.cs
  .Lib9c.Tests/Action/HackAndSlash18Test.cs
  .Lib9c.Tests/Action/MimisbrunnrBattle10Test.cs
  .Lib9c.Tests/Action/MimisbrunnrBattle8Test.cs
  .Lib9c.Tests/Action/Raid1Test.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateViewExtensions.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Character/EnemyPlayer.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Model/Character/Skills.cs
  Lib9c/Model/EnumType/StatReferenceType.cs
  Lib9c/TableCSV/Rune/RuneSkillSheet.csv
  Lib9c/TableCSV/Rune/RuneSkillSheet.csv.meta
  Lib9c/TableCSV/Rune/RuneStatSheet.csv
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableData/Rune/RuneSkillSheet.cs
  Lib9c/TableData/SimulatorSheets.cs
Labels: Large

#1469 Bump .NET 6
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  Lib9c.DevExtensions/Lib9c.DevExtensions.csproj
  Lib9c/Action/ActionBase.cs
  Lib9c/Action/ByteSerializer.cs
  Lib9c/Formatters/ExceptionFormatter.cs
  Lib9c/Lib9c.csproj
  Lib9c/Model/State/AvatarState.cs
  Lib9c/Model/State/State.cs
Labels: Medium

#1472 Merge `RuneSkillSheet` into `RuneStatSheet`.
  .Lib9c.Tests/Action/EventDungeonBattleV2Test.cs
  .Lib9c.Tests/Action/HackAndSlash18Test.cs
  .Lib9c.Tests/Action/MimisbrunnrBattle10Test.cs
  .Lib9c.Tests/Action/Raid1Test.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AccountStateViewExtensions.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv.meta
  Lib9c/TableCSV/Rune/RuneSkillSheet.csv
  Lib9c/TableCSV/Rune/RuneSkillSheet.csv.meta
  Lib9c/TableCSV/Rune/RuneStatSheet.csv
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableData/Rune/RuneOptionSheet.cs
  Lib9c/TableData/Rune/RuneSkillSheet.cs
  Lib9c/TableData/Rune/RuneStatSheet.cs
  Lib9c/TableData/SimulatorSheets.cs
Labels: Large

#1486 Add value type for rune skill power
  Lib9c/Model/Character/Player.cs
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableData/Rune/RuneOptionSheet.cs
Labels: Extra Small

#1476 add txid to action evaluation
  Lib9c/Action/ActionBase.cs
  Lib9c/Renderer/ActionRenderer.cs
Labels: Extra Small

#1478 Separate miner as another package
  .Lib9c.Tests/Policy/BlockPolicyTest.cs
  Lib9c.Miner/Lib9c.Miner.csproj
  Lib9c.Miner/Miner.cs
  Lib9c.Miner/ReorgMiner.cs
  Lib9c.sln
  Lib9c/InvalidMinerException.cs
  Lib9c/Lib9c.csproj
Labels: Extra Small

#1483 Separate `Secp256K1CryptoBackend` as an independent package
  .Lib9c.Benchmarks/Lib9c.Benchmarks.csproj
  Lib9c.sln
  Lib9c/Lib9c.csproj
  Libplanet.Crypto.Secp256k1/Libplanet.Crypto.Secp256k1.csproj
  Libplanet.Crypto.Secp256k1/Secp256K1CryptoBackend.cs
Labels: Extra Small

#1484 Separate logics related to `MessagePack`
  .Lib9c.Tests/Lib9c.Tests.csproj
  Lib9c.MessagePack/Action/NCActionEvaluation.cs
  Lib9c.MessagePack/Formatters/AccountStateDeltaFormatter.cs
  Lib9c.MessagePack/Formatters/AddressFormatter.cs
  Lib9c.MessagePack/Formatters/BencodexFormatter.cs
  Lib9c.MessagePack/Formatters/ExceptionFormatter.cs
  Lib9c.MessagePack/Formatters/FungibleAssetValueFormatter.cs
  Lib9c.MessagePack/Formatters/NCActionFormatter.cs
  Lib9c.MessagePack/Formatters/NineChroniclesResolver.cs
  Lib9c.MessagePack/Formatters/NineChroniclesResolverGetFormatterHelper.cs
  Lib9c.MessagePack/Formatters/PublicKeyFormatter.cs
  Lib9c.MessagePack/Lib9c.MessagePack.csproj
  Lib9c.sln
  Lib9c/Lib9c.csproj
Labels: Extra Small

#1485 Replace `JetBrains.Annotations` with .NET nullable refernce check
  Lib9c.MessagePack/Action/NCActionEvaluation.cs
  Lib9c/Helper/RuneHelper.cs
  Lib9c/Lib9c.csproj
  Lib9c/Model/BattleStatus/Arena/ArenaSkill.cs
  Lib9c/Model/BattleStatus/Skill.cs
  Lib9c/Model/State/ArenaAvatarState.cs
  Lib9c/Model/State/CrystalCostState.cs
  Lib9c/TableData/Sheet.cs
Labels: Small

#1494 Introduce item preset
  .Lib9c.Tests/Action/EquipRuneTest.cs
  .Lib9c.Tests/Model/Rune/RuneSlotTest.cs
  Lib9c/Battle/CPHelper.cs
  Lib9c/Model/Character/ArenaPlayerDigest.cs
  Lib9c/Model/Rune/RuneSlot.cs
  Lib9c/Model/State/ItemSlotState.cs
  Lib9c/Model/State/RuneSlotState.cs
Labels: Medium

#1488 Rune test data
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/SweepRequiredCPSheet.csv
Labels: Extra Large

#1497 Introduce UnlockRuneSlot action
  .Lib9c.Tests/Action/UnlockRuneSlotTest.cs
  Lib9c/Action/UnlockRuneSlot.cs
  Lib9c/Model/Rune/RuneExceptions.cs
  Lib9c/Model/State/GameConfigState.cs
  Lib9c/TableCSV/GameConfigSheet.csv
Labels: Large

#1500 Update Rune Balance Data
  .Lib9c.Tests/Action/RuneEnhancementTest.cs
  Lib9c/Action/RuneEnhancement.cs
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/RuneCostSheet.csv
  Lib9c/TableCSV/RuneListSheet.csv
  Lib9c/TableCSV/RuneSheet.csv
Labels: Extra Large

#1499 Remove `Jetbrains.Annotations` using
  Lib9c/Helper/RuneHelper.cs
Labels: bug

#1504 Update Rune List Grade Change
  Lib9c/TableCSV/RuneListSheet.csv
Labels: Extra Small

#1505 Remove EquipRune action
  .Lib9c.Tests/Action/EquipRuneTest.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/EquipRune.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/JoinArena.cs
  Lib9c/Action/MimisbrunnrBattle.cs
  Lib9c/Action/Raid.cs
Labels: Large

#1508 Match RuneId & RuneStoneId
  .Lib9c.Tests/TableData/RuneCostSheetTest.cs
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/RuneCostSheet.csv
  Lib9c/TableCSV/RuneListSheet.csv
  Lib9c/TableData/RuneCostSheet.cs
Labels: Extra Large

#1498 Introduce `BattleGrandFinale` action
  .Lib9c.Tests/Action/BattleGrandFinaleTest.cs
  .Lib9c.Tests/Model/GrandFinale/GrandFinaleInformationTest.cs
  .Lib9c.Tests/StagePolicyTest.cs
  .Lib9c.Tests/TableData/GrandFinale/GrandFinaleParticipantsSheetTest.cs
  .Lib9c.Tests/TableData/GrandFinale/GrandFinaleScheduleSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  .Lib9c.Tests/TestHelper/BlockChainHelper.cs
  Lib9c/Action/BattleGrandFinale.cs
  Lib9c/Exceptions/AlreadyFoughtAvatarException.cs
  Lib9c/Model/GrandFinale/GrandFinaleInformation.cs
  Lib9c/SerializeKeys.cs
  Lib9c/TableCSV/GrandFinale.meta
  Lib9c/TableCSV/GrandFinale/GrandFinaleParticipantsSheet.csv
  Lib9c/TableCSV/GrandFinale/GrandFinaleParticipantsSheet.csv.meta
  Lib9c/TableCSV/GrandFinale/GrandFinaleScheduleSheet.csv
  Lib9c/TableCSV/GrandFinale/GrandFinaleScheduleSheet.csv.meta
  Lib9c/TableData/GrandFinale/GrandFinaleParticipantsSheet.cs
  Lib9c/TableData/GrandFinale/GrandFinaleScheduleSheet.cs
Labels: Extra Large

#1513 Fix argument type of `NCActionEvaluation`
  Lib9c.MessagePack/Action/NCActionEvaluation.cs
Labels: Extra Small

#1512 Apply new hit correction method on raid
  Lib9c/Battle/HitHelper.cs
  Lib9c/Battle/RaidBoss.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/RaidSimulatorV1.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
Labels: Extra Small

#1510 Update rune balance
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/RuneCostSheet.csv
  Lib9c/TableCSV/RuneListSheet.csv
  Lib9c/TableCSV/RuneSheet.csv
Labels: Extra Large

#1516 Update rune slot states
  Lib9c/Action/RuneEnhancement.cs
  Lib9c/Model/EnumType/BattleType.cs
  Lib9c/Model/State/RuneSlotState.cs
Labels: Extra Small

#1514 Seperate Score from `GrandFinaleInformation`
  .Lib9c.Tests/Action/BattleGrandFinaleTest.cs
  .Lib9c.Tests/Model/GrandFinale/GrandFinaleInformationTest.cs
  Lib9c/Action/BattleGrandFinale.cs
  Lib9c/Model/GrandFinale/GrandFinaleInformation.cs
Labels: Extra Small

#1518 2022q4 rune
  .Lib9c.Tests/Action/EquipRuneTest.cs
  .Lib9c.Tests/Action/RuneEnhancementTest.cs
  .Lib9c.Tests/Action/RuneSlotInfoTest.cs
  .Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs
  .Lib9c.Tests/TableData/RuneCostSheetTest.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/EquipRune.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/JoinArena.cs
  Lib9c/Action/MimisbrunnrBattle.cs
  Lib9c/Action/Raid.cs
  Lib9c/Action/RuneEnhancement.cs
  Lib9c/Action/RuneSlotInfo.cs
  Lib9c/Battle/HitHelper.cs
  Lib9c/Battle/RaidBoss.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/RaidSimulatorV1.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/EnumType/BattleType.cs
  Lib9c/Model/State/RuneSlotState.cs
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/RuneCostSheet.csv
  Lib9c/TableCSV/RuneListSheet.csv
  Lib9c/TableCSV/RuneSheet.csv
  Lib9c/TableData/RuneCostSheet.cs
Labels: Extra Large

#1506 Prepare test
  .Lib9c.Tests/Action/BattleArena1Test.cs
  .Lib9c.Tests/Action/BattleArena2Test.cs
  .Lib9c.Tests/Action/BattleArena3Test.cs
  .Lib9c.Tests/Action/BattleArena4Test.cs
  .Lib9c.Tests/Action/BattleArena5Test.cs
  .Lib9c.Tests/Action/BattleArena6Test.cs
  .Lib9c.Tests/Action/BattleArena7Test.cs
  .Lib9c.Tests/Action/CreateAvatarTest.cs
  .Lib9c.Tests/Action/JoinArena0Test.cs
  .Lib9c.Tests/Action/JoinArena2Test.cs
  .Lib9c.Tests/Action/Raid0Test.cs
  .Lib9c.Tests/Action/Raid1Test.cs
  .Lib9c.Tests/Action/Raid2Test.cs
  .Lib9c.Tests/Action/Raid3Test.cs
  .Lib9c.Tests/Policy/BlockPolicyTest.cs
  .Lib9c.Tests/TableData/ArenaSheetTest.cs
  Lib9c/Action/CreateAvatar.cs
  Lib9c/BlockHelper.cs
  Lib9c/TableCSV/Arena/ArenaSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
Labels: Extra Large

#1496 Add action eventmaterialitemcrafts
  .Lib9c.Tests/Action/EventMaterialItemCraftsTest.cs
  .Lib9c.Tests/Model/Mail/MaterialCraftMailTest.cs
  .Lib9c.Tests/TableData/Event/EventMaterialItemRecipeSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/EventMaterialItemCrafts.cs
  Lib9c/Exceptions/InvalidMaterialCountException.cs
  Lib9c/Extensions/EventRecipeExtensions.cs
  Lib9c/Model/Mail/IMail.cs
  Lib9c/Model/Mail/Mail.cs
  Lib9c/Model/Mail/MaterialCraftMail.cs
  Lib9c/TableCSV/Event/EventMaterialItemRecipeSheet.csv
  Lib9c/TableCSV/Event/EventMaterialItemRecipeSheet.csv.meta
  Lib9c/TableCSV/Event/EventScheduleSheet.csv
  Lib9c/TableData/Event/EventMaterialItemRecipeSheet.cs
Labels: Extra Large

#1527 Fix Table sheet
  Lib9c/TableCSV/Event/EventMaterialItemRecipeSheet.csv
  Lib9c/TableCSV/Event/EventScheduleSheet.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
Labels: Extra Small

#1529 Update staking rune id
  .Lib9c.Tests/TableData/StakeRegularRewardSheetTest.cs
  Lib9c/TableCSV/StakeRegularRewardSheet.csv
Labels: Extra Small

#1523 Update Arens Season Data & Arens Reward Costume And Title
  .Lib9c.Tests/TableData/ArenaSheetTest.cs
  Lib9c/TableCSV/Arena/ArenaSheet.csv
  Lib9c/TableCSV/Item/CostumeItemSheet.csv
  Lib9c/TableCSV/Item/CostumeStatSheet.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
Labels: Medium

#1530 Introduce `IClaimStakeReward` interface and apply to actions
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Action/ClaimStakeReward1.cs
  Lib9c/Action/ClaimStakeReward3.cs
  Lib9c/Action/IClaimStakeReward.cs
Labels: Extra Small

#1534 Introduce TransferAssets
  .Lib9c.Tests/Action/TransferAssetsTest.cs
  Lib9c/Action/ITransferAssets.cs
  Lib9c/Action/TransferAssets.cs
Labels: Extra Large

#1532 Fix state related to rune
  .Lib9c.Tests/Action/RuneSlotInfoTest.cs
  .Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs
  .Lib9c.Tests/Model/Arena/PlayerDigestTest.cs
  .Lib9c.Tests/Model/Rune/RuneSlotTest.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlashSweep.cs
  Lib9c/Action/JoinArena.cs
  Lib9c/Action/MimisbrunnrBattle.cs
  Lib9c/Action/Raid.cs
  Lib9c/Action/RuneEnhancement.cs
  Lib9c/Action/RuneSlotInfo.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/ArenaPlayerDigest.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Model/Rune/RuneExceptions.cs
  Lib9c/Model/Rune/RuneSlot.cs
  Lib9c/Model/State/RuneSlotState.cs
Labels: Large

#1538 TransferAssets set recipients capacity
  .Lib9c.Tests/Action/TransferAssetsTest.cs
  Lib9c/Action/TransferAssets.cs
Labels: Extra Small

#1543 Merge `main` to `development`
  .Lib9c.Tests/Action/TransferAssetsTest.cs
  Lib9c/Action/TransferAssets.cs
Labels: Extra Small

#1545 ♻️ [PBFT] Remove unnecessary policies
  .Lib9c.Benchmarks/Program.cs
  .Lib9c.Tests/Policy/BlockPolicyTest.cs
  Lib9c/Policy/AuthorizedMinersPolicy.cs
  Lib9c/Policy/BlockPolicySource.Utils.cs
  Lib9c/Policy/BlockPolicySource.cs
  Lib9c/Policy/PermissionedMinersPolicy.cs
Labels: Extra Large

#1540 Add daily rune reward
  .Lib9c.Tests/Action/DailyRewardTest.cs
  Lib9c/Action/DailyReward.cs
  Lib9c/Helper/RuneHelper.cs
  Lib9c/Model/State/GameConfigState.cs
  Lib9c/TableCSV/GameConfigSheet.csv
Labels: Extra Small

#1537 Update StakingRune Balance, Rune id change
  .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
  .Lib9c.Tests/Action/ClaimWorldBossKillRewardTest.cs
  .Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs
  .Lib9c.Tests/TableData/WorldBossRankingRewardSheetTest.cs
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/RuneCostSheet.csv
  Lib9c/TableCSV/RuneListSheet.csv
  Lib9c/TableCSV/RuneSheet.csv
  Lib9c/TableCSV/RuneWeightSheet.csv
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossRankingRewardSheet.csv
Labels: Medium
