Repository planetarium/lib9c, pull requests merged in 2023-07, with the labels that each got.

#1992 🧹 Removed unsupported render methods.
  Lib9c.Renderers/Renderers/ActionRenderer.cs
  Lib9c.Renderers/Renderers/BlockRenderer.cs
Labels: Small

#1994 🧹 Rewrite attribute checking logic
  .Lib9c.Tests/Action/Factory/ClaimStakeRewardFactoryTest.cs
  .Lib9c.Tests/Action/Scenario/MeadScenarioTest.cs
  .Lib9c.Tests/Action/Snapshot/ActionUtils.cs
  .Lib9c.Tools/SubCommand/Action.cs
  Lib9c/Action/ActionObsoleteAttribute.cs
Labels: Extra Small

#1996 ✨ Added `MockState` for testing
  .Lib9c.DevExtensions.Tests/Action/FaucetCurrencyTest.cs
  .Lib9c.Tests/Action/ActivateAccount0Test.cs
  .Lib9c.Tests/Action/AddActivatedAccount0Test.cs
  .Lib9c.Tests/Action/AddActivatedAccountTest.cs
  .Lib9c.Tests/Action/AddRedeemCodeTest.cs
  .Lib9c.Tests/Action/CreatePendingActivationTest.cs
  .Lib9c.Tests/Action/CreatePendingActivationsTest.cs
  .Lib9c.Tests/Action/MigrationActivatedAccountsStateTest.cs
  .Lib9c.Tests/Action/MigrationAvatarStateTest.cs
  .Lib9c.Tests/Action/MockState.cs
  .Lib9c.Tests/Action/MockStateDelta.cs
  .Lib9c.Tests/Action/PatchTableSheetTest.cs
  .Lib9c.Tests/Action/RenewAdminStateTest.cs
  .Lib9c.Tests/Action/SecureMiningRewardTest.cs
  .Lib9c.Tests/Action/TransferAsset2Test.cs
  .Lib9c.Tests/Action/TransferAsset3Test.cs
  .Lib9c.Tests/Action/TransferAssetTest.cs
  .Lib9c.Tests/Action/TransferAssetTest0.cs
  .Lib9c.Tests/Action/TransferAssets0Test.cs
  .Lib9c.Tests/Action/TransferAssetsTest.cs
  .Lib9c.Tests/Action/ValidatorSetOperateTest.cs
Labels: Extra Large

#1997 ♻️ Modernize `MockStateDelta`
  .Lib9c.Tests/Action/AddActivatedAccount0Test.cs
  .Lib9c.Tests/Action/AddActivatedAccountTest.cs
  .Lib9c.Tests/Action/MockStateDelta.cs
  .Lib9c.Tests/Action/Snapshot/transfer_asset.TransferCrystal.summary.verified.txt
  .Lib9c.Tests/Action/Snapshot/transfer_asset.TransferWithMemo.summary.verified.txt
Labels: Large

#1998 Do not wipe out empty garage to null
  .Lib9c.Tests/Action/Garages/DeliverToOthersGaragesTest.cs
  .Lib9c.Tests/Action/Garages/UnloadFromMyGaragesTest.cs
  .Lib9c.Tests/Model/Garages/FungibleItemGarageTest.cs
  Lib9c/Model/Garages/FungibleItemGarage.cs
Labels: enhancement, Small

#2001 fix: delete `CostKind` column
  .Lib9c.Tests/TableData/Garages/LoadIntoMyGaragesCostSheetTest.cs
  Lib9c/TableCSV/Garages/LoadIntoMyGaragesCostSheet.csv
  Lib9c/TableData/Garages/LoadIntoMyGaragesCostSheet.cs
Labels: Small

#2003 2023q2-iap to development
  .Lib9c.Tests/Action/ExceptionTest.cs
  .Lib9c.Tests/Action/Garages/DeliverToOthersGaragesTest.cs
  .Lib9c.Tests/Action/Garages/LoadIntoMyGaragesTest.cs
  .Lib9c.Tests/Action/Garages/UnloadFromMyGaragesTest.cs
  .Lib9c.Tests/CurrenciesTest.cs
  .Lib9c.Tests/Model/Garages/FungibleItemGarageTest.cs
  .Lib9c.Tests/Model/Mail/UnloadFromMyGaragesRecipientMailTest.cs
  .Lib9c.Tests/Model/State/AvatarStateTest.cs
  .Lib9c.Tests/TableData/Garages/LoadIntoMyGaragesCostSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c.Abstractions/IDeliverToOthersGaragesV1.cs
  Lib9c.Abstractions/ILoadIntoMyGaragesV1.cs
  Lib9c.Abstractions/IUnloadFromMyGaragesV1.cs
  Lib9c.sln.DotSettings
  Lib9c/Action/AccountStateExtensions.cs
  Lib9c/Action/CreateAvatar.cs
  Lib9c/Action/Garages/DeliverToOthersGarages.cs
  Lib9c/Action/Garages/GarageUtils.cs
  Lib9c/Action/Garages/LoadIntoMyGarages.cs
  Lib9c/Action/Garages/UnloadFromMyGarages.cs
  Lib9c/Action/HackAndSlash3.cs
  Lib9c/Action/MimisbrunnrBattle0.cs
  Lib9c/Action/PetEnhancement.cs
  Lib9c/Addresses.cs
  Lib9c/Currencies.cs
  Lib9c/Exceptions/InvalidActionFieldException.cs
  Lib9c/Exceptions/ItemNotFoundException.cs
  Lib9c/Exceptions/NotEnoughItemException.cs
  Lib9c/Exceptions/StateNullException.cs
  Lib9c/Model/Garages/FungibleItemGarage.cs
  Lib9c/Model/Garages/IFungibleItemGarage.cs
  Lib9c/Model/Garages/IGarage.cs
  Lib9c/Model/Item/Inventory.cs
  Lib9c/Model/Item/ItemBase.cs
  Lib9c/Model/Item/Material.cs
  Lib9c/Model/Mail/IMail.cs
  Lib9c/Model/Mail/Mail.cs
  Lib9c/Model/Mail/UnloadFromMyGaragesRecipientMail.cs
  Lib9c/Model/State/AvatarState.cs
  Lib9c/TableCSV/Garages.meta
  Lib9c/TableCSV/Garages/LoadIntoMyGaragesCostSheet.csv
  Lib9c/TableCSV/Garages/LoadIntoMyGaragesCostSheet.csv.meta
  Lib9c/TableData/Garages/LoadIntoMyGaragesCostSheet.cs
Labels: enhancement, Extra Large

#2005 fix: apply `Libplanet` changes inside of `UNITY_EDITOR` constants
  Lib9c/Action/CreateAvatar8.cs
Labels: Extra Small

#2006 [CI] Apply auto find options
  .github/workflows/main.yml
Labels: Extra Small

#2012 ♻️ Use valid `MockStateDelta`
  .Lib9c.DevExtensions.Tests/Action/ManipulateStateTest.cs
  .Lib9c.Tests/Action/CombinationEquipment10Test.cs
  .Lib9c.Tests/Action/CombinationEquipment11Test.cs
  .Lib9c.Tests/Action/CombinationEquipment12Test.cs
  .Lib9c.Tests/Action/CombinationEquipment13Test.cs
  .Lib9c.Tests/Action/CombinationEquipment14Test.cs
  .Lib9c.Tests/Action/CombinationEquipment15Test.cs
  .Lib9c.Tests/Action/CombinationEquipment8Test.cs
  .Lib9c.Tests/Action/CombinationEquipment9Test.cs
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  .Lib9c.Tests/Action/EventDungeonBattleV1Test.cs
  .Lib9c.Tests/Action/EventDungeonBattleV2Test.cs
  .Lib9c.Tests/Action/EventDungeonBattleV3Test.cs
  .Lib9c.Tests/Action/EventDungeonBattleV4Test.cs
  .Lib9c.Tests/Action/EventDungeonBattleV5Test.cs
  .Lib9c.Tests/Action/GrindingTest.cs
  .Lib9c.Tests/Action/InitializeStatesTest.cs
  .Lib9c.Tests/Action/JoinArena1Test.cs
  .Lib9c.Tests/Action/JoinArena2Test.cs
  .Lib9c.Tests/Action/JoinArena3Test.cs
  .Lib9c.Tests/Action/MockStateDelta.cs
  .Lib9c.Tests/Action/PetEnhancement0Test.cs
  .Lib9c.Tests/Action/RuneEnhancement0Test.cs
  .Lib9c.Tests/Action/RuneEnhancementTest.cs
  .Lib9c.Tests/Action/UnlockWorld1Test.cs
  .Lib9c.Tests/Action/UnlockWorldTest.cs
  .Lib9c.Tests/Util/InitializeUtil.cs
Labels: Large

#2014 🔧 Implement valid `Delta` for `Lib9c.Formatters.AccountStatedelta`
  Lib9c.MessagePack/AccountStateDelta.cs
Labels: Small

#2016 Fix invalid crystal mint 600000 -> 200000
  .Lib9c.Tests/Action/CreateAvatarTest.cs
  Lib9c/Action/CreateAvatar.cs
Labels: Extra Small

#2017 Update submodule updater
  .github/workflows/main.yml
Labels: Extra Small

#2020 Set obsolete create_avatar8
  Lib9c/Action/CreateAvatar8.cs
  Lib9c/ActionObsoleteConfig.cs
Labels: Extra Small

#2021 fix: mail type of `UnloadFromMyGaragesRecipientMail` to `Auction`
  Lib9c/Model/Mail/UnloadFromMyGaragesRecipientMail.cs
Labels: Extra Small

#2018 Optimize HackAndSlash.Execute #1
  .Lib9c.Tests/Action/HitHelperTest.cs
  .Lib9c.Tests/Model/Skill/CombatTest.cs
  .Lib9c.Tests/Model/Skill/NormalAttackTest.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Battle/AttackCountHelper.cs
  Lib9c/Battle/HitHelper.cs
  Lib9c/Battle/ISimulator.cs
  Lib9c/Battle/RaidBoss.cs
  Lib9c/Battle/Simulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Battle/StageSimulatorV1.cs
  Lib9c/Battle/StageSimulatorV2.cs
  Lib9c/Battle/StageSimulatorV3.cs
  Lib9c/Battle/Wave.cs
  Lib9c/Model/BattleStatus/Skill.cs
  Lib9c/Model/Buff/Bleed.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Model/Quest/CollectQuest.cs
  Lib9c/Model/Quest/CombinationEquipmentQuest.cs
  Lib9c/Model/Quest/CombinationQuest.cs
  Lib9c/Model/Quest/GeneralQuest.cs
  Lib9c/Model/Quest/GoldQuest.cs
  Lib9c/Model/Quest/ItemEnhancementQuest.cs
  Lib9c/Model/Quest/ItemGradeQuest.cs
  Lib9c/Model/Quest/ItemTypeCollectQuest.cs
  Lib9c/Model/Quest/MonsterQuest.cs
  Lib9c/Model/Quest/Quest.cs
  Lib9c/Model/Quest/TradeQuest.cs
  Lib9c/Model/Skill/AreaAttack.cs
  Lib9c/Model/Skill/AttackSkill.cs
  Lib9c/Model/Skill/BlowAttack.cs
  Lib9c/Model/Skill/BuffRemovalAttack.cs
  Lib9c/Model/Skill/BuffSkill.cs
  Lib9c/Model/Skill/DoubleAttack.cs
  Lib9c/Model/Skill/HealSkill.cs
  Lib9c/Model/Skill/NormalAttack.cs
  Lib9c/Model/Skill/Skill.cs
  Lib9c/Model/State/RedeemCodeState.cs
Labels: Extra Large

#2028 Fix client render when use buff, heal skills
  .Lib9c.Tests/Model/Skill/CombatTest.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Model/Skill/AreaAttack.cs
  Lib9c/Model/Skill/BlowAttack.cs
  Lib9c/Model/Skill/BuffRemovalAttack.cs
  Lib9c/Model/Skill/BuffSkill.cs
  Lib9c/Model/Skill/DoubleAttack.cs
  Lib9c/Model/Skill/HealSkill.cs
  Lib9c/Model/Skill/NormalAttack.cs
  Lib9c/Model/Skill/Skill.cs
Labels: Small

#2032 Log HAS Playcount, Remove Debug log
  Lib9c/Action/AccountStateExtensions.cs
  Lib9c/Action/HackAndSlash.cs
Labels: Extra Small

#2033 ci(gh-actions): check typos in GitHub Actions
  .github/workflows/lint.yml
  Lib9c.Policy/Policy/IVariableSubPolicy.cs
  Lib9c/Action/EventMaterialItemCrafts.cs
  Lib9c/Action/ValidatorSetOperate.cs
  _typos.toml
Labels: ci, Extra Small

#2037 feat: introduce `Lib9c.StateService`
  .Lib9c.StateService.Shared/Lib9c.StateService.Shared.csproj
  .Lib9c.StateService.Shared/RemoteEvaluationRequest.cs
  .Lib9c.StateService.Shared/RemoteEvaluationResponse.cs
  .Lib9c.StateService/Controllers/RemoteEvaluationController.cs
  .Lib9c.StateService/Lib9c.StateService.csproj
  .Lib9c.StateService/Program.cs
  .Lib9c.StateService/Properties/launchSettings.json
  .Lib9c.StateService/appsettings-schema.json
  .Lib9c.StateService/appsettings.Development.json
  .Lib9c.StateService/appsettings.json
  .Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests/ActionEvaluationSerializerTest.cs
  .Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests/Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests.csproj
  .Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests/Usings.cs
  .Libplanet.Extensions.ActionEvaluatorCommonComponents/AccountDelta.cs
  .Libplanet.Extensions.ActionEvaluatorCommonComponents/AccountStateDelta.cs
  .Libplanet.Extensions.ActionEvaluatorCommonComponents/AccountStateDeltaMarshaller.cs
  .Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionContext.cs
  .Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionContextMarshaller.cs
  .Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionEvaluation.cs
  .Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionEvaluationMarshaller.cs
  .Libplanet.Extensions.ActionEvaluatorCommonComponents/Libplanet.Extensions.ActionEvaluatorCommonComponents.csproj
  .Libplanet.Extensions.ActionEvaluatorCommonComponents/PreEvaluationBlockMarshaller.cs
  .Libplanet.Extensions.ActionEvaluatorCommonComponents/Random.cs
  .Libplanet.Extensions.ActionEvaluatorCommonComponents/TransactionMarshaller.cs
  .Libplanet.Extensions.RemoteActionEvaluator.Tests/Libplanet.Extensions.RemoteActionEvaluator.Tests.csproj
  .Libplanet.Extensions.RemoteActionEvaluator.Tests/Usings.cs
  .Libplanet.Extensions.RemoteActionEvaluator/AssemblyInfo.cs
  .Libplanet.Extensions.RemoteActionEvaluator/Libplanet.Extensions.RemoteActionEvaluator.csproj
  .Libplanet.Extensions.RemoteActionEvaluator/RemoteActionEvaluator.cs
  .Libplanet.Extensions.RemoteBlockChainStates/Libplanet.Extensions.RemoteBlockChainStates.csproj
  .Libplanet.Extensions.RemoteBlockChainStates/RemoteBlockChainStates.cs
  .Libplanet.Extensions.RemoteBlockChainStates/RemoteBlockState.cs
  Lib9c.sln
Labels: Extra Large

#2034 Add blockindex to has total log
  Lib9c/Action/HackAndSlash.cs
Labels: Small

#2039 ci(gh-actions): build Docker image
  .github/workflows/push_docker_image.yaml
  Dockerfile.amd64
  Dockerfile.arm64v8
Labels: ci, Medium

#2041 Optimize HackAndSlash.Execute #2
  .Lib9c.Tests/Action/BuyMultipleTest.cs
  .Lib9c.Tests/Model/Item/ArmorTest.cs
  .Lib9c.Tests/Model/Item/BeltTest.cs
  .Lib9c.Tests/Model/Item/ConsumableTest.cs
  .Lib9c.Tests/Model/Item/EquipmentTest.cs
  .Lib9c.Tests/Model/Item/InventoryTest.cs
  .Lib9c.Tests/Model/Item/NecklaceTest.cs
  .Lib9c.Tests/Model/Item/ShopItemTest.cs
  .Lib9c.Tests/Model/ItemGradeQuestTest.cs
  .Lib9c.Tests/Model/ItemTypeCollectQuestTest.cs
  .Lib9c.Tests/Model/QuestRewardTest.cs
  Lib9c/Action/AccountStateExtensions.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Model/Item/ItemBase.cs
  Lib9c/Model/Item/ItemUsable.cs
  Lib9c/Model/Mail/Mail.cs
  Lib9c/Model/Quest/CombinationEquipmentQuest.cs
  Lib9c/Model/Quest/CombinationQuest.cs
  Lib9c/Model/Quest/GoldQuest.cs
  Lib9c/Model/Quest/ItemEnhancementQuest.cs
  Lib9c/Model/Quest/Quest.cs
  Lib9c/Model/Quest/QuestReward.cs
  Lib9c/Model/Quest/TradeQuest.cs
  Lib9c/Model/State/AvatarState.cs
Labels: Extra Large
