Repository planetarium/lib9c, pull requests merged in 2023-01, with the labels that each got.

#1612 Fix `ToLong()` extension method
  .Lib9c.Tests/Model/State/StateExtensionsTest.cs
  Lib9c/Model/State/StateExtensions.cs
Labels: bug, Small

#1626 Update World Boss 2 Data draft
  Lib9c/TableCSV/RuneListSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossBattleRewardSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossKillRewardSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossRankRewardSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossRankingRewardSheet.csv
Labels: Small

#1624 Add handling about negative count at `Inventory.RemoveFungibleItem()`
  Lib9c/Model/Item/Inventory.cs
Labels: Extra Small

#1627 ⬆️ [PBFT] Updated policy to include additional external validatros
  Lib9c/Policy/BlockPolicySource.cs
  Lib9c/Policy/ValidatorsPolicy.cs
Labels: Extra Small

#1632 Improve raid test
  .Lib9c.Tests/Action/Raid0Test.cs
  .Lib9c.Tests/Action/Raid1Test.cs
  .Lib9c.Tests/Action/Raid2Test.cs
  .Lib9c.Tests/Action/Raid3Test.cs
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
Labels: Large

#1630 Update Serumnir Skill Id & Patten
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossActionPatternSheet.csv
Labels: Extra Small

#1633 Fix syntax to make compilable in 9c client.
  Lib9c.DevExtensions/Action/FaucetRune.cs
  Lib9c.DevExtensions/Action/Interface/IFaucetCurrency.cs
  Lib9c.DevExtensions/Action/Interface/IFaucetRune.cs
Labels: Small

#1619 Implement critical damage (CDMG)
  .Lib9c.Tests/Model/Skill/CombatTest.cs
  Lib9c/Battle/CPHelper.cs
  Lib9c/Battle/CriticalHelper.cs
  Lib9c/Battle/TestSimulator.cs
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/Model/Buff/CriticalDamageBuff.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Skill/Arena/ArenaAttackSkill.cs
  Lib9c/Model/Skill/AttackSkill.cs
  Lib9c/Model/Skill/SkillCategory.cs
  Lib9c/Model/Stat/CharacterStats.cs
  Lib9c/Model/Stat/IStats.cs
  Lib9c/Model/Stat/StatType.cs
  Lib9c/Model/Stat/Stats.cs
  Lib9c/Model/Stat/StatsMap.cs
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
Labels: Large

#1636 Bump worldboss 230109
  .Lib9c.DevExtensions.Tests/Action/FaucetCurrencyTest.cs
  .Lib9c.DevExtensions.Tests/Action/FaucetRuneTest.cs
  Lib9c/Action/Factory/FaucetFactory.cs
  Lib9c/Action/FaucetCurrency.cs
  Lib9c/Action/FaucetRune.cs
  Lib9c/Action/Interface/IFaucetCurrency.cs
  Lib9c/Action/Interface/IFaucetRune.cs
  Lib9c/Lib9c.csproj
Labels: Medium

#1638 Update Rune Cost Data Draft
  Lib9c/TableCSV/RuneCostSheet.csv
Labels: Extra Large

#1641 Update World Buff CDMG add, Rune Option Draft Add
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
Labels: Extra Small

#1643 Update CDMG Buff Value Change
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
Labels: Extra Large

#1606 [DevExtensions]CreateOrReplaceAvatar
  .Lib9c.DevExtensions.Tests/Action/CreateOrReplaceAvatarTest.cs
  .Lib9c.DevExtensions.Tests/Action/Factory/CreateOrReplaceAvatarFactoryTest.cs
  .Lib9c.DevExtensions.Tests/Lib9c.DevExtensions.Tests.csproj
  .Lib9c.DevExtensions.Tests/TableSheetsImporter.cs
  .Lib9c.Tests/TableSheetsImporter.cs
  Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
  Lib9c.DevExtensions/Action/Factory/CreateOrReplaceAvatarFactory.cs
  Lib9c.DevExtensions/Action/Interface/ICreateOrReplaceAvatar.cs
  Lib9c.MessagePack/Formatters/NineChroniclesResolverGetFormatterHelper.cs
  Lib9c.MessagePack/Lib9c.MessagePack.csproj
Labels: Extra Large

#1646 Revert "Merge pull request #1618 from moreal/revert-1580"
  Lib9c.Abstractions/IActivateAccount.cs
  Lib9c.Abstractions/Lib9c.Abstractions.csproj
  Lib9c.Miner/Miner.cs
  Lib9c.sln
  Lib9c/Action/ActivateAccount.cs
  Lib9c/Action/ActivateAccount0.cs
  Lib9c/Lib9c.csproj
  Lib9c/Policy/BlockPolicySource.Utils.cs
  Lib9c/Policy/BlockPolicySource.cs
Labels: Medium

#1644 Add runes on `CreateAvatar` when executing on editor mode.
  Lib9c/Action/CreateAvatar.cs
  Lib9c/Action/CreateAvatar0.cs
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
Labels: Extra Small

#1647 Edit project settings
  Lib9c.Abstractions/Lib9c.Abstractions.csproj
  Lib9c.MessagePack/Formatters/NineChroniclesResolverGetFormatterHelper.cs
  Lib9c.MessagePack/Lib9c.MessagePack.csproj
  Lib9c.Miner/Lib9c.Miner.csproj
  Libplanet.Crypto.Secp256k1/Libplanet.Crypto.Secp256k1.csproj
Labels: Small

#1650 Correct assebmly's path
  Lib9c/Policy/BlockPolicySource.cs
Labels: bug, Extra Small

#1651 Load plain value when loading `activate_account` actions
  Lib9c/Policy/BlockPolicySource.cs
Labels: bug, Extra Small

#1652 bug fix about HAS20
  .Lib9c.Tests/Action/HackAndSlash20Test.cs
  Lib9c/Action/HackAndSlash.cs
Labels: Small

#1659 Ban account in stage policy level
  Lib9c/StagePolicy.cs
Labels: Extra Small

#1657 2023q1 worldboss serumnir balance
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/RuneCostSheet.csv
  Lib9c/TableCSV/RuneListSheet.csv
  Lib9c/TableCSV/RuneSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossGlobalHpSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossKillRewardSheet.csv
Labels: Extra Large

#1661 Update Character Level Exp Change
  Lib9c/TableCSV/Character/CharacterLevelSheet.csv
Labels: Large

#1590 Apply interface and factory pattern to `HackAndSlash` action
  .Lib9c.Tests/Action/Factory/HackAndSlashFactoryTest.cs
  Lib9c/Action/Factory/HackAndSlashFactory.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlash18.cs
  Lib9c/Action/HackAndSlash19.cs
  Lib9c/Action/Interface/IHackAndSlash.cs
Labels: enhancement, Extra Large, hardfork

#1664 Update Skill & WorldBossAction Change
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossActionPatternSheet.csv
Labels: Extra Small

#1666 Update multistrike hitcount
  Lib9c/TableCSV/Skill/SkillSheet.csv
Labels: Extra Small

#1667 Merge 2023q1 serimnir to development
  .Lib9c.Tests/Action/Raid1Test.cs
  .Lib9c.Tests/Action/Raid2Test.cs
  .Lib9c.Tests/Action/Raid3Test.cs
  .Lib9c.Tests/Action/Raid4Test.cs
  .Lib9c.Tests/Model/Skill/CombatTest.cs
  Lib9c/Action/CreateAvatar.cs
  Lib9c/Action/CreateAvatar0.cs
  Lib9c/Battle/CPHelper.cs
  Lib9c/Battle/CriticalHelper.cs
  Lib9c/Battle/TestSimulator.cs
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/Model/Buff/CriticalDamageBuff.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Skill/Arena/ArenaAttackSkill.cs
  Lib9c/Model/Skill/AttackSkill.cs
  Lib9c/Model/Skill/SkillCategory.cs
  Lib9c/Model/Stat/CharacterStats.cs
  Lib9c/Model/Stat/IStats.cs
  Lib9c/Model/Stat/StatType.cs
  Lib9c/Model/Stat/Stats.cs
  Lib9c/Model/Stat/StatsMap.cs
  Lib9c/TableCSV/Character/CharacterLevelSheet.csv
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/RuneCostSheet.csv
  Lib9c/TableCSV/RuneListSheet.csv
  Lib9c/TableCSV/RuneSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossActionPatternSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossBattleRewardSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossGlobalHpSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossKillRewardSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossRankRewardSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossRankingRewardSheet.csv
Labels: Extra Large

#1649 Edit arena off season
  .Lib9c.Tests/Action/BattleArena7Test.cs
  .Lib9c.Tests/Action/BattleArena8Test.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/BattleArena3.cs
  Lib9c/Action/BattleArena4.cs
  Lib9c/Action/BattleArena5.cs
  Lib9c/Action/BattleArena6.cs
  Lib9c/Action/BattleArena7.cs
  Lib9c/Arena/ArenaHelper.cs
  Lib9c/Model/Arena/ArenaExceptions.cs
Labels: Medium

#1669 Update Rune Name Change
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/RuneCostSheet.csv
  Lib9c/TableCSV/RuneListSheet.csv
  Lib9c/TableCSV/RuneSheet.csv
Labels: Extra Large

#1662 Enable `EnableDynamicLoading`
  Lib9c/Lib9c.csproj
Labels: Extra Small

#1675 Fix rune slot state
  .Lib9c.Tests/Action/BattleArena8Test.cs
  .Lib9c.Tests/Action/EventDungeonBattleV4Test.cs
  .Lib9c.Tests/Action/HackAndSlash20Test.cs
  .Lib9c.Tests/Action/HackAndSlashSweep9Test.cs
  .Lib9c.Tests/Action/JoinArena3Test.cs
  .Lib9c.Tests/Action/MimisbrunnrBattle12Test.cs
  .Lib9c.Tests/Action/Raid4Test.cs
  Lib9c/Model/State/RuneSlotState.cs
Labels: bug, Small

#1665 Improve solution and project settings for dev extensions
  .Lib9c.DevExtensions.Tests/Lib9c.DevExtensions.Tests.csproj
  .Lib9c.Tests/Lib9c.Tests.csproj
  .Lib9c.Tools/Lib9c.Tools.csproj
  Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
  Lib9c.DevExtensions/Lib9c.DevExtensions.csproj
  Lib9c.MessagePack/Lib9c.MessagePack.csproj
  Lib9c.sln
  Lib9c/Lib9c.csproj
Labels: Medium

#1642 Unstage SetValidator action with invalid validatorAdmin
  Lib9c/Policy/BlockPolicySource.Utils.cs
  Lib9c/Policy/BlockPolicySource.cs
Labels: Extra Small

#1673 Consider `macOS` in `TestbedHelper`
  Lib9c.DevExtensions/TestbedHelper.cs
Labels: Extra Small

#1678 Rename `Debug DevEx` to `DevEx` and fix minor
  .Lib9c.Benchmarks/Lib9c.Benchmarks.csproj
  .Lib9c.Tests/Lib9c.Tests.csproj
  .Lib9c.Tools/Lib9c.Tools.csproj
  Lib9c.DevExtensions/Lib9c.DevExtensions.csproj
  Lib9c.sln
  Lib9c/Lib9c.csproj
Labels: Small

#1677 [DevEx]Bug fix of `CreateOrReplaceAvatar`
  .Lib9c.DevExtensions.Tests/Action/CreateOrReplaceAvatarTest.cs
  Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
  Lib9c.DevExtensions/Action/Interface/ICreateOrReplaceAvatar.cs
Labels: Small

#1680 No warn `xUnit1026` in test project
  .Lib9c.DevExtensions.Tests/Lib9c.DevExtensions.Tests.csproj
Labels: Extra Small

#1676 Introduce model about pet system
  .Lib9c.Tests/Model/State/PetStateTest.cs
  .Lib9c.Tests/TableData/Pet/PetCostSheetTest.cs
  .Lib9c.Tests/TableData/Pet/PetOptionSheetTest.cs
  .Lib9c.Tests/TableData/Pet/PetSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Model/Pet/PetOptionType.cs
  Lib9c/Model/State/PetState.cs
  Lib9c/TableCSV/Pet/PetCostSheet.csv
  Lib9c/TableCSV/Pet/PetOptionSheet.csv
  Lib9c/TableCSV/Pet/PetSheet.csv
  Lib9c/TableData/Pet/PetCostSheet.cs
  Lib9c/TableData/Pet/PetOptionSheet.cs
  Lib9c/TableData/Pet/PetSheet.cs
Labels: Extra Large

#1687 Fix drr formula in arena
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Skill/Arena/ArenaAttackSkill.cs
Labels: Extra Small

#1689 🔀 Add changes made to pow-dynamic-validators
  .Lib9c.Benchmarks/Program.cs
  .Lib9c.Tests/Policy/BlockPolicyTest.cs
  Lib9c/Policy/BlockPolicySource.Utils.cs
  Lib9c/Policy/BlockPolicySource.cs
  Lib9c/Policy/ValidatorAdminPolicy.cs
  Lib9c/Renderer/ActionRenderer.cs
Labels: Large
