Repository planetarium/lib9c, pull requests merged in 2023-12, with the labels that each got.

#2261 Introduce `Stun` : `ActionBuff`
  .Lib9c.Tests/Model/PlayerTest.cs
  Lib9c/Model/BattleStatus/Arena/ArenaTick.cs
  Lib9c/Model/BattleStatus/Tick.cs
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/Model/Buff/Stun.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Skill/ActionBuffType.cs
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
Labels: Large

#2269 🔀 merge release/1.5.1 into development
  .Lib9c.Plugin.Shared/IPluginActionEvaluator.cs
  .Lib9c.Plugin.Shared/IPluginKeyValueStore.cs
  .Lib9c.Plugin.Shared/Lib9c.Plugin.Shared.csproj
  .Lib9c.Plugin/Lib9c.Plugin.csproj
  .Lib9c.Plugin/PluginActionEvaluator.cs
  .Lib9c.Plugin/WrappedKeyValueStore.cs
  Lib9c.Policy/Policy/MaxTransactionsBytesPolicy.cs
  Lib9c.sln
Labels: Small

#2268 🔀 merge release/1.5.1 into main
  .Lib9c.Plugin.Shared/IPluginActionEvaluator.cs
  .Lib9c.Plugin.Shared/IPluginKeyValueStore.cs
  .Lib9c.Plugin.Shared/Lib9c.Plugin.Shared.csproj
  .Lib9c.Plugin/Lib9c.Plugin.csproj
  .Lib9c.Plugin/PluginActionEvaluator.cs
  .Lib9c.Plugin/WrappedKeyValueStore.cs
  .github/workflows/lib9c_plugin_build_and_push_s3.yaml
  Lib9c.sln
Labels: Medium

#2271 🧹 chore: cleanup lib9c service
  .Lib9c.StateService.Shared/Lib9c.StateService.Shared.csproj
  .Lib9c.StateService.Shared/RemoteEvaluationRequest.cs
  .Lib9c.StateService.Shared/RemoteEvaluationResponse.cs
  .Lib9c.StateService/Controllers/RemoteEvaluationController.cs
  .Lib9c.StateService/Lib9c.StateService.csproj
  .Lib9c.StateService/Program.cs
  .Lib9c.StateService/Properties/launchSettings.json
  .Lib9c.StateService/appsettings-schema.json
  .Lib9c.StateService/appsettings.Development.json
  .Lib9c.StateService/appsettings.json
  .Libplanet.Extensions.RemoteActionEvaluator.Tests/Libplanet.Extensions.RemoteActionEvaluator.Tests.csproj
  .Libplanet.Extensions.RemoteActionEvaluator.Tests/Usings.cs
  .Libplanet.Extensions.RemoteActionEvaluator/AssemblyInfo.cs
  .Libplanet.Extensions.RemoteActionEvaluator/Libplanet.Extensions.RemoteActionEvaluator.csproj
  .Libplanet.Extensions.RemoteActionEvaluator/RemoteActionEvaluator.cs
  .github/workflows/lib9c_plugin_build_and_push_s3.yaml
  .github/workflows/publish.yml
  Lib9c.sln
Labels: enhancement, Large

#2273 Update New Rune data Add
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/RuneCostSheet.csv
  Lib9c/TableCSV/RuneListSheet.csv
  Lib9c/TableCSV/RuneSheet.csv
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
Labels: Extra Small

#2276 🔧 fix: add docs for `AccountExtensions.cs`
  .Lib9c.Tests/AccountExtensions.cs
Labels: No Changes

#2279 Keep action type id instead of versioning up
  .Lib9c.Tests/Action/MintAssets0Test.cs
  Lib9c/Action/MintAssets.cs
  Lib9c/Action/MintAssets0.cs
Labels: suggestion, Extra Large

#2278 🧹 cleanup: remove useless BattleArena actions
  .Lib9c.Tests/Action/BattleArena10Test.cs
  .Lib9c.Tests/Action/BattleArena11Test.cs
  .Lib9c.Tests/Action/BattleArena12Test.cs
  .Lib9c.Tests/Action/BattleArena13Test.cs
  .Lib9c.Tests/Action/BattleArena14Test.cs
  .Lib9c.Tests/Action/BattleArena1Test.cs
  .Lib9c.Tests/Action/BattleArena2Test.cs
  .Lib9c.Tests/Action/BattleArena3Test.cs
  .Lib9c.Tests/Action/BattleArena4Test.cs
  .Lib9c.Tests/Action/BattleArena5Test.cs
  .Lib9c.Tests/Action/BattleArena6Test.cs
  .Lib9c.Tests/Action/BattleArena7Test.cs
  .Lib9c.Tests/Action/BattleArena8Test.cs
  .Lib9c.Tests/Action/BattleArena9Test.cs
  .Lib9c.Tests/Action/Scenario/ArenaScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/AuraScenarioTest.cs
  Lib9c/Action/BattleArena1.cs
  Lib9c/Action/BattleArena10.cs
  Lib9c/Action/BattleArena11.cs
  Lib9c/Action/BattleArena12.cs
  Lib9c/Action/BattleArena13.cs
  Lib9c/Action/BattleArena14.cs
  Lib9c/Action/BattleArena2.cs
  Lib9c/Action/BattleArena3.cs
  Lib9c/Action/BattleArena4.cs
  Lib9c/Action/BattleArena5.cs
  Lib9c/Action/BattleArena6.cs
  Lib9c/Action/BattleArena7.cs
  Lib9c/Action/BattleArena8.cs
  Lib9c/Action/BattleArena9.cs
Labels: enhancement, Extra Large

#2274 Introduce `Vampiric` : `ActionBuff`
  .Lib9c.Tests/Model/PlayerTest.cs
  Lib9c/Model/BattleStatus/Arena/ArenaTick.cs
  Lib9c/Model/BattleStatus/Tick.cs
  Lib9c/Model/Buff/ActionBuff.cs
  Lib9c/Model/Buff/Bleed.cs
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/Model/Buff/Stun.cs
  Lib9c/Model/Buff/Vampiric.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/IArena.cs
  Lib9c/Model/IStage.cs
  Lib9c/Model/Skill/ActionBuffType.cs
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
Labels: Large

#2282 change skillInfo.target to cloned character at Vampiric
  Lib9c/Model/Buff/Vampiric.cs
Labels: Extra Small

#2283 cherry-pick commits about `Vampiric` into release/1.6.0
  .Lib9c.Tests/Model/PlayerTest.cs
  Lib9c/Model/BattleStatus/Arena/ArenaTick.cs
  Lib9c/Model/BattleStatus/Tick.cs
  Lib9c/Model/Buff/ActionBuff.cs
  Lib9c/Model/Buff/Bleed.cs
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/Model/Buff/Stun.cs
  Lib9c/Model/Buff/Vampiric.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/IArena.cs
  Lib9c/Model/IStage.cs
  Lib9c/Model/Skill/ActionBuffType.cs
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
Labels: Large

#2280 🧹 cleanup: remove useless `Buy` actions
  .Lib9c.Tests/Action/Buy10Test.cs
  .Lib9c.Tests/Action/Buy11Test.cs
  .Lib9c.Tests/Action/Buy2Test.cs
  .Lib9c.Tests/Action/Buy3Test.cs
  .Lib9c.Tests/Action/Buy4Test.cs
  .Lib9c.Tests/Action/Buy5Test.cs
  .Lib9c.Tests/Action/Buy6Test.cs
  .Lib9c.Tests/Action/Buy8Test.cs
  .Lib9c.Tests/Action/Buy9Test.cs
  .Lib9c.Tools/SubCommand/Market.cs
  Lib9c/Action/Buy0.cs
  Lib9c/Action/Buy10.cs
  Lib9c/Action/Buy11.cs
  Lib9c/Action/Buy2.cs
  Lib9c/Action/Buy3.cs
  Lib9c/Action/Buy4.cs
  Lib9c/Action/Buy5.cs
  Lib9c/Action/Buy6.cs
  Lib9c/Action/Buy8.cs
  Lib9c/Action/Buy9.cs
Labels: Extra Large

#2290 Fix build
  .github/workflows/push_docker_image.yaml
  Dockerfile.amd64
  Dockerfile.arm64v8
Labels: Medium

#2291 fix calculating logic of Vampiric, for avoid int overflow
  .Lib9c.Tests/Model/PlayerTest.cs
  Lib9c/Model/Buff/Vampiric.cs
Labels: Extra Small

#2293 🧹 chore: cleanup sell action
  .Lib9c.Tests/Action/Sell0Test.cs
  .Lib9c.Tests/Action/Sell10Test.cs
  .Lib9c.Tests/Action/Sell11Test.cs
  .Lib9c.Tests/Action/Sell2Test.cs
  .Lib9c.Tests/Action/Sell3Test.cs
  .Lib9c.Tests/Action/Sell4Test.cs
  .Lib9c.Tests/Action/Sell5Test.cs
  .Lib9c.Tests/Action/Sell6Test.cs
  .Lib9c.Tests/Action/Sell7Test.cs
  .Lib9c.Tests/Action/Sell8Test.cs
  .Lib9c.Tests/Action/Sell9Test.cs
  Lib9c/Action/Sell0.cs
  Lib9c/Action/Sell10.cs
  Lib9c/Action/Sell11.cs
  Lib9c/Action/Sell2.cs
  Lib9c/Action/Sell3.cs
  Lib9c/Action/Sell4.cs
  Lib9c/Action/Sell5.cs
  Lib9c/Action/Sell7.cs
  Lib9c/Action/Sell8.cs
  Lib9c/Action/Sell9.cs
Labels: Extra Large

#2294 🧹 chore: cleanup claim action
  .Lib9c.Tests/Action/ClaimMonsterCollectionReward0Test.cs
  .Lib9c.Tests/Action/ClaimMonsterCollectionReward2Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward1Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward2Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward3Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward4Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward5Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward6Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward7Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward8Test.cs
  .Lib9c.Tests/Action/Factory/ClaimStakeRewardFactoryTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeReward2ScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeReward3ScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  .Lib9c.Tests/Lib9c.Tests.csproj
  Lib9c/Action/ClaimMonsterCollectionReward0.cs
  Lib9c/Action/ClaimMonsterCollectionReward2.cs
  Lib9c/Action/ClaimStakeReward1.cs
  Lib9c/Action/ClaimStakeReward3.cs
  Lib9c/Action/ClaimStakeReward4.cs
  Lib9c/Action/ClaimStakeReward5.cs
  Lib9c/Action/ClaimStakeReward6.cs
  Lib9c/Action/ClaimStakeReward7.cs
  Lib9c/Action/ClaimStakeReward8.cs
  Lib9c/Action/Factory/ClaimStakeRewardFactory.cs
  Lib9c/Model/State/StakeState.cs
Labels: Extra Large

#2296 🔨 Correct `RemoteBlockChainStates` implementation
  .Libplanet.Extensions.RemoteBlockChainStates/RemoteBlockChainStates.cs
Labels: bug, Extra Small

#2300 Introduce crystal rune slot
  .Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs
  .Lib9c.Tests/Action/UnlockRuneSlotTest.cs
  .Lib9c.Tests/Model/RuneSlotStateTest.cs
  .gitallowed
  Lib9c/Action/UnlockRuneSlot.cs
  Lib9c/Model/EnumType/RuneSlotType.cs
  Lib9c/Model/State/GameConfigState.cs
  Lib9c/Model/State/RuneSlotState.cs
  Lib9c/TableCSV/GameConfigSheet.csv
Labels: Medium

#2301 🧹 chore: cleanup action
  .Lib9c.Tests/Action/TransferAsset2Test.cs
  .Lib9c.Tests/Action/TransferAsset3Test.cs
  .Lib9c.Tests/Action/TransferAsset4Test.cs
  .Lib9c.Tests/Action/TransferAssetTest0.cs
  .Lib9c.Tests/Action/TransferAssets0Test.cs
  .Lib9c.Tests/Action/TransferAssets2Test.cs
  .Lib9c.Tests/Action/UpdateSell0Test.cs
  .Lib9c.Tests/Action/UpdateSell2Test.cs
  .Lib9c.Tests/Action/UpdateSell3Test.cs
  .Lib9c.Tests/Action/UpdateSell4Test.cs
  Lib9c/Action/TransferAsset2.cs
  Lib9c/Action/TransferAsset4.cs
  Lib9c/Action/TransferAssets0.cs
  Lib9c/Action/TransferAssets2.cs
  Lib9c/Action/UpdateSell0.cs
  Lib9c/Action/UpdateSell2.cs
  Lib9c/Action/UpdateSell3.cs
  Lib9c/Action/UpdateSell4.cs
Labels: Extra Large

#2304 ⏪ Revert "chore: cleanup claim action"
  .Lib9c.Tests/Action/ClaimMonsterCollectionReward0Test.cs
  .Lib9c.Tests/Action/ClaimMonsterCollectionReward2Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward1Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward2Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward3Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward4Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward5Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward6Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward7Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward8Test.cs
  .Lib9c.Tests/Action/Factory/ClaimStakeRewardFactoryTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeReward2ScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeReward3ScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  .Lib9c.Tests/Lib9c.Tests.csproj
  Lib9c/Action/ClaimMonsterCollectionReward0.cs
  Lib9c/Action/ClaimMonsterCollectionReward2.cs
  Lib9c/Action/ClaimStakeReward1.cs
  Lib9c/Action/ClaimStakeReward3.cs
  Lib9c/Action/ClaimStakeReward4.cs
  Lib9c/Action/ClaimStakeReward5.cs
  Lib9c/Action/ClaimStakeReward6.cs
  Lib9c/Action/ClaimStakeReward7.cs
  Lib9c/Action/ClaimStakeReward8.cs
  Lib9c/Action/Factory/ClaimStakeRewardFactory.cs
  Lib9c/Model/State/StakeState.cs
Labels: Extra Large

#2305 ⏪ Revert "chore: cleanup action"
  .Lib9c.Tests/Action/TransferAsset2Test.cs
  .Lib9c.Tests/Action/TransferAsset3Test.cs
  .Lib9c.Tests/Action/TransferAsset4Test.cs
  .Lib9c.Tests/Action/TransferAssetTest0.cs
  .Lib9c.Tests/Action/TransferAssets0Test.cs
  .Lib9c.Tests/Action/TransferAssets2Test.cs
  .Lib9c.Tests/Action/UpdateSell0Test.cs
  .Lib9c.Tests/Action/UpdateSell2Test.cs
  .Lib9c.Tests/Action/UpdateSell3Test.cs
  .Lib9c.Tests/Action/UpdateSell4Test.cs
  Lib9c/Action/TransferAsset2.cs
  Lib9c/Action/TransferAsset4.cs
  Lib9c/Action/TransferAssets0.cs
  Lib9c/Action/TransferAssets2.cs
  Lib9c/Action/UpdateSell0.cs
  Lib9c/Action/UpdateSell2.cs
  Lib9c/Action/UpdateSell3.cs
  Lib9c/Action/UpdateSell4.cs
Labels: Extra Large

#2307 Update testbed code Create Avatar for test
  Lib9c.DevExtensions/Data/TestbedCreateAvatar.json
  Lib9c.DevExtensions/Model/TestbedCreateAvatar.cs
  Lib9c/Action/CreateAvatar.cs
  Lib9c/Action/CreateAvatar0.cs
Labels: Large

#2311 Release/1.7.0
  .Lib9c.Tests/Action/ClaimMonsterCollectionReward0Test.cs
  .Lib9c.Tests/Action/ClaimMonsterCollectionReward2Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward1Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward2Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward3Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward4Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward5Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward6Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward7Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward8Test.cs
  .Lib9c.Tests/Action/Factory/ClaimStakeRewardFactoryTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeReward2ScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeReward3ScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
  .Lib9c.Tests/Action/TransferAsset2Test.cs
  .Lib9c.Tests/Action/TransferAsset3Test.cs
  .Lib9c.Tests/Action/TransferAsset4Test.cs
  .Lib9c.Tests/Action/TransferAssetTest0.cs
  .Lib9c.Tests/Action/TransferAssets0Test.cs
  .Lib9c.Tests/Action/TransferAssets2Test.cs
  .Lib9c.Tests/Action/UpdateSell0Test.cs
  .Lib9c.Tests/Action/UpdateSell2Test.cs
  .Lib9c.Tests/Action/UpdateSell3Test.cs
  .Lib9c.Tests/Action/UpdateSell4Test.cs
  .Lib9c.Tests/Lib9c.Tests.csproj
  Lib9c/Action/ClaimMonsterCollectionReward0.cs
  Lib9c/Action/ClaimMonsterCollectionReward2.cs
  Lib9c/Action/ClaimStakeReward1.cs
  Lib9c/Action/ClaimStakeReward3.cs
  Lib9c/Action/ClaimStakeReward4.cs
  Lib9c/Action/ClaimStakeReward5.cs
  Lib9c/Action/ClaimStakeReward6.cs
  Lib9c/Action/ClaimStakeReward7.cs
  Lib9c/Action/ClaimStakeReward8.cs
  Lib9c/Action/Factory/ClaimStakeRewardFactory.cs
  Lib9c/Action/TransferAsset2.cs
  Lib9c/Action/TransferAsset4.cs
  Lib9c/Action/TransferAssets0.cs
  Lib9c/Action/TransferAssets2.cs
  Lib9c/Action/UpdateSell0.cs
  Lib9c/Action/UpdateSell2.cs
  Lib9c/Action/UpdateSell3.cs
  Lib9c/Action/UpdateSell4.cs
  Lib9c/Model/State/StakeState.cs
Labels: Extra Large

#2313 use concurrent dictionary in stagepolicy
  Lib9c.Policy/NCStagePolicy.cs
Labels: Extra Small

#2315 add txid to messagepack
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  Lib9c.MessagePack/Action/NCActionEvaluation.cs
  Lib9c.MessagePack/Formatters/TxIdFormatter.cs
Labels: Extra Small
