Repository planetarium/lib9c, pull requests merged in 2023-05, with the labels that each got.

#1876 Add stat reference in buff value
  Lib9c/Battle/RaidBoss.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Battle/StageSimulatorV1.cs
  Lib9c/Battle/StageSimulatorV2.cs
  Lib9c/Model/Buff/Bleed.cs
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/Model/Buff/StatBuff.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Character/Enemy.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Model/Character/Skills.cs
  Lib9c/Model/Skill/ISkill.cs
  Lib9c/Model/Skill/SkillFactory.cs
  Lib9c/Model/Stat/CharacterStats.cs
  Lib9c/Model/Stat/Stats.cs
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableData/Skill/StatBuffSheet.cs
Labels: Large

#1884 Remove all subclass of `StatBuff`.
  Lib9c/Model/Buff/AttackBuff.cs
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/Model/Buff/CriticalBuff.cs
  Lib9c/Model/Buff/CriticalDamageBuff.cs
  Lib9c/Model/Buff/DamageReductionBuff.cs
  Lib9c/Model/Buff/DefenseBuff.cs
  Lib9c/Model/Buff/HPBuff.cs
  Lib9c/Model/Buff/HitBuff.cs
  Lib9c/Model/Buff/SpeedBuff.cs
  Lib9c/Model/Buff/StatBuff.cs
Labels: Medium

#1877 Calculate UpdatedAddresses on Lib9c side
  .Lib9c.Tests/Action/ActionBaseExtensionsTest.cs
  Lib9c/Action/ActionBaseExtensions.cs
Labels: Small

#1878 fix `SellCancellation9` invalidstateroothashexception from #6166598
  Lib9c/Action/SellCancellation.cs
Labels: Small

#1888 Update Stage Buff Gacha Date
  Lib9c/TableCSV/Crystal/CrystalStageBuffGachaSheet.csv
Labels: Extra Small

#1894 Update Equipment Item Recipes Draft
  .Lib9c.Tests/Action/CombinationEquipment10Test.cs
  .Lib9c.Tests/Action/CombinationEquipment11Test.cs
  .Lib9c.Tests/Action/CombinationEquipment3Test.cs
  .Lib9c.Tests/Action/CombinationEquipment4Test.cs
  .Lib9c.Tests/Action/CombinationEquipment5Test.cs
  .Lib9c.Tests/Action/CombinationEquipment6Test.cs
  .Lib9c.Tests/Action/CombinationEquipment7Test.cs
  .Lib9c.Tests/Action/CombinationEquipment8Test.cs
  .Lib9c.Tests/Action/CombinationEquipment9Test.cs
  .Lib9c.Tests/Action/UnlockEquipmentRecipe1Test.cs
  .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
  Lib9c/TableCSV/Item/EquipmentItemOptionSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemSubRecipeSheetV2.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
Labels: Extra Large

#1895 Apply bonus damage on skill based on stat
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Skill/Arena/ArenaAttackSkill.cs
  Lib9c/Model/Skill/Arena/ArenaHealSkill.cs
  Lib9c/Model/Skill/AttackSkill.cs
  Lib9c/Model/Skill/HealSkill.cs
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableData/Skill/SkillSheet.cs
  Lib9c/TableData/Skill/StatBuffSheet.cs
Labels: Extra Large

#1899 Update skilll date change
  Lib9c/TableCSV/Item/EquipmentItemOptionSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
Labels: Large

#1898 add IsMimisRecipe to `EquipmentSubRecipeSheetV2` and handling it
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Extensions/EquipmentExtensions.cs
  Lib9c/TableCSV/Item/EquipmentItemSubRecipeSheetV2.csv
  Lib9c/TableData/Item/EquipmentItemRecipeSheet.cs
  Lib9c/TableData/Item/EquipmentItemSubRecipeSheetV2.cs
Labels: Extra Large

#1901 Implement enhancing stat power ratio
  .Lib9c.Tests/Model/Skill/CombatTest.cs
  .Lib9c.Tests/Model/Skill/NormalAttackTest.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Helper/ItemOptionHelper.cs
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Item/Equipment.cs
  Lib9c/Model/Skill/AreaAttack.cs
  Lib9c/Model/Skill/Arena/ArenaAreaAttack.cs
  Lib9c/Model/Skill/Arena/ArenaAttackSkill.cs
  Lib9c/Model/Skill/Arena/ArenaBlowAttack.cs
  Lib9c/Model/Skill/Arena/ArenaBuffRemovalAttack.cs
  Lib9c/Model/Skill/Arena/ArenaBuffSkill.cs
  Lib9c/Model/Skill/Arena/ArenaDoubleAttack.cs
  Lib9c/Model/Skill/Arena/ArenaHealSkill.cs
  Lib9c/Model/Skill/Arena/ArenaNormalAttack.cs
  Lib9c/Model/Skill/Arena/ArenaSkill.cs
  Lib9c/Model/Skill/AttackSkill.cs
  Lib9c/Model/Skill/BlowAttack.cs
  Lib9c/Model/Skill/BuffRemovalAttack.cs
  Lib9c/Model/Skill/BuffSkill.cs
  Lib9c/Model/Skill/DoubleAttack.cs
  Lib9c/Model/Skill/HealSkill.cs
  Lib9c/Model/Skill/ISkill.cs
  Lib9c/Model/Skill/NormalAttack.cs
  Lib9c/Model/Skill/Skill.cs
  Lib9c/Model/Skill/SkillFactory.cs
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableData/Item/EquipmentItemOptionSheet.cs
  Lib9c/TableData/Skill/SkillSheet.cs
Labels: Large

#1903 Update All mimis Recipe Change
  Lib9c/TableCSV/Item/EquipmentItemSubRecipeSheetV2.csv
Labels: Large

#1907 🔧 Fixed activation check
  Lib9c.Policy/Policy/BlockPolicySource.cs
Labels: Extra Small

#1908 Update Balance Date Change
  Lib9c/TableCSV/Character/CharacterSheet.csv
  Lib9c/TableCSV/Skill/EnemySkillSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableCSV/WorldAndStage/StageSheet.csv
Labels: Medium

#1909 Bug fix in applying skill ratio
  .Lib9c.Tests/Action/HackAndSlash18Test.cs
  .Lib9c.Tests/Action/HackAndSlash19Test.cs
  .Lib9c.Tests/Action/HackAndSlash20Test.cs
  .Lib9c.Tests/Model/ItemUsableTest.cs
  .Lib9c.Tests/Model/PlayerTest.cs
  .Lib9c.Tests/Model/SkillsTest.cs
  Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Action/CombinationEquipment0.cs
  Lib9c/Action/CombinationEquipment13.cs
  Lib9c/Action/CombinationEquipment14.cs
  Lib9c/Action/CombinationEquipment15.cs
  Lib9c/Action/CombinationEquipment2.cs
  Lib9c/Action/CombinationEquipment3.cs
  Lib9c/Action/CombinationEquipment4.cs
  Lib9c/Action/CombinationEquipment5.cs
  Lib9c/Action/CombinationEquipment6.cs
  Lib9c/Action/CombinationEquipment7.cs
  Lib9c/Action/CreateAvatar.cs
  Lib9c/Battle/RaidBoss.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Character/Enemy.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Model/Skill/SkillFactory.cs
  Lib9c/Model/State/CrystalRandomSkillState.cs
Labels: Medium

#1913 Update Staking Item Add
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
Labels: Extra Small

#1915 Fix `NotSupportedException` from `.CalculateUpdateAddresses()`
  .Lib9c.Tests/Action/ActionBaseExtensionsTest.cs
  Lib9c/Action/ActionBaseExtensions.cs
Labels: bug, Extra Small

#1917 Prevent state mismatch occured with random
  Lib9c/Action/CombinationEquipment.cs
Labels: Extra Small

#1920 Specify minimum stat values on each StatTypes.
  Lib9c/Model/Stat/CharacterStats.cs
Labels: Extra Small

#1927 Fix state mismatch on Equipment Enhancement
  .Lib9c.DevExtensions.Tests/Action/CreateOrReplaceAvatarTest.cs
  Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
  Lib9c/Model/Item/Equipment.cs
  Lib9c/Model/Stat/StatsMap.cs
Labels: Extra Small

#1926 Rename mead actions
  .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/ApprovePledgeTest.cs
  .Lib9c.Tests/Action/RequestPledgeTest.cs
  .Lib9c.Tests/Action/RewardGoldTest.cs
  .Lib9c.Tests/Action/Scenario/MeadScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/Pet/IncreaseBlockPerHourglassTest.cs
  .Lib9c.Tests/Action/TransferAssetTest.cs
  .Lib9c.Tests/Action/TransferAssetsTest.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/AddressExtension.cs
  Lib9c/Action/ApprovePledge.cs
  Lib9c/Action/EndPledge.cs
  Lib9c/Action/RequestPledge.cs
  Lib9c/Action/RewardGold.cs
Labels: Medium

#1923 ♻️ Remove `PolymorphicAction<T>` and use `ActionBase`
  .Lib9c.Benchmarks/Program.cs
  .Lib9c.Tests/Action/ActionBaseExtensionsTest.cs
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/Coupons/IssueCouponsTest.cs
  .Lib9c.Tests/Action/Coupons/TransferCouponsTest.cs
  .Lib9c.Tests/Action/CreatePendingActivationsTest.cs
  .Lib9c.Tests/Action/RewardGoldTest.cs
  .Lib9c.Tests/Action/Snapshot/transfer_asset.PlainValue.verified.txt
  .Lib9c.Tests/Action/TransferAsset2Test.cs
  .Lib9c.Tests/Action/TransferAssetTest.cs
  .Lib9c.Tests/Action/TransferAssetTest0.cs
  .Lib9c.Tests/Action/TransferAssetsTest.cs
  .Lib9c.Tests/Policy/BlockPolicyTest.cs
  .Lib9c.Tests/StagePolicyTest.cs
  .Lib9c.Tests/TestHelper/BlockChainHelper.cs
  .Lib9c.Tools/SubCommand/Account.cs
  .Lib9c.Tools/SubCommand/Market.cs
  .Lib9c.Tools/SubCommand/State.cs
  .Lib9c.Tools/SubCommand/Tx.cs
  Lib9c.DevExtensions/Action/Loader/NCDevActionLoader.cs
  Lib9c.DevExtensions/Utils.cs
  Lib9c.MessagePack/Action/NCActionEvaluation.cs
  Lib9c.MessagePack/Formatters/NCActionFormatter.cs
  Lib9c.MessagePack/Formatters/NineChroniclesResolverGetFormatterHelper.cs
  Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
  Lib9c.Policy/Policy/BlockPolicySource.cs
  Lib9c.Policy/Policy/NCBlockPolicy.cs
  Lib9c.Renderers/Renderers/ActionRenderer.cs
  Lib9c.Renderers/Renderers/BlockRenderer.cs
  Lib9c.Utils/BlockHelper.cs
  Lib9c/Action/ActionBaseExtensions.cs
  Lib9c/Action/ActivateAccount.cs
  Lib9c/Action/ActivateAccount0.cs
  Lib9c/Action/AddActivatedAccount.cs
  Lib9c/Action/AddActivatedAccount0.cs
  Lib9c/Action/CreatePendingActivation.cs
  Lib9c/Action/CreatePendingActivations.cs
  Lib9c/Action/GameAction.cs
  Lib9c/Action/Loader/NCActionLoader.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Action/PrepareRewardAssets.cs
  Lib9c/Action/SecureMiningReward.cs
  Lib9c/Action/Stake0.cs
  Lib9c/Action/TransferAsset.cs
  Lib9c/Action/TransferAsset0.cs
  Lib9c/Action/TransferAsset2.cs
  Lib9c/Action/TransferAssets.cs
Labels: Extra Large

#1929 Item recipe change
  Lib9c/TableCSV/Crystal/CrystalEquipmentGrindingSheet.csv
Labels: Extra Large

#1933 Release tagged lib9c to github
  .github/bin/constants.sh
  .github/bin/dist-github-release.sh
  .github/bin/dist-pack.sh
  .github/bin/github-release.sh
  .github/workflows/release.yaml
Labels: Medium

#1936 update git index
  .github/bin/constants.sh
  .github/bin/dist-github-release.sh
  .github/bin/dist-pack.sh
  .github/bin/github-release.sh
  .gitignore
Labels: Extra Small

#1937 Add mead contract test cases
  .Lib9c.Tests/Action/ApprovePledgeTest.cs
  .Lib9c.Tests/Action/EndPledgeTest.cs
  .Lib9c.Tests/Action/ExceptionTest.cs
  .Lib9c.Tests/Action/RequestPledgeTest.cs
  .Lib9c.Tests/Action/RewardGoldTest.cs
  Lib9c/Action/AlreadyContractedException.cs
  Lib9c/Action/ApprovePledge.cs
  Lib9c/Action/EndPledge.cs
  Lib9c/Action/RequestPledge.cs
  Lib9c/Action/RewardGold.cs
Labels: Medium

#1939 Add refill mead in contract
  .Lib9c.Tests/Action/ApprovePledgeTest.cs
  .Lib9c.Tests/Action/RequestPledgeTest.cs
  .Lib9c.Tests/Action/RewardGoldTest.cs
  .Lib9c.Tests/Action/Scenario/MeadScenarioTest.cs
  Lib9c/Action/ApprovePledge.cs
  Lib9c/Action/RequestPledge.cs
  Lib9c/Action/RewardGold.cs
Labels: Extra Small

#1941 World7 add balance
  Lib9c/TableCSV/Character/CharacterSheet.csv
  Lib9c/TableCSV/Cost/EnhancementCostSheetV2.csv
  Lib9c/TableCSV/Item/EquipmentItemOptionSheet.csv
  Lib9c/TableCSV/Quest/CombinationEquipmentQuestSheet.csv
  Lib9c/TableCSV/Skill/EnemySkillSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableCSV/WorldAndStage/StageDialogSheet.csv
  Lib9c/TableCSV/WorldAndStage/StageSheet.csv
Labels: Extra Large

#1946 Correct `Lib9c.Tools action list` command
  .Lib9c.Tools/SubCommand/Action.cs
Labels: Extra Small
