Repository planetarium/lib9c, pull requests merged in 2023-11, with the labels that each got.

#2194 add GetTxQuota to ACS
  Lib9c.Policy/AccessControlService/IAccessControlService.cs
  Lib9c.Policy/NCStagePolicy.cs
Labels: Extra Small

#2193 Update 70.2~70.3 Date
  .Lib9c.DevExtensions.Tests/Action/CreateOrReplaceAvatarTest.cs
  .Lib9c.DevExtensions.Tests/Action/Factory/CreateOrReplaceAvatarFactoryTest.cs
  .Lib9c.Tests/Action/CombinationEquipment0Test.cs
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  .Lib9c.Tests/Action/Scenario/CombinationAndRapidCombinationTest.cs
  .Lib9c.Tests/Action/Scenario/Pet/IncreaseBlockPerHourglassTest.cs
  .Lib9c.Tests/Action/UnlockEquipmentRecipe1Test.cs
  .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
  .Lib9c.Tests/CrystalCalculatorTest.cs
  Lib9c/TableCSV/CreateAvatarFavSheet.csv
  Lib9c/TableCSV/CreateAvatarItemSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
  Lib9c/TableCSV/Quest/CombinationEquipmentQuestSheet.csv
  Lib9c/TableCSV/Quest/QuestRewardSheet.csv
  Lib9c/TableCSV/Quest/WorldQuestSheet.csv
Labels: Extra Large

#2197 PDX-19: Add UnloadFromGarages Action
  .Lib9c.Tests/Action/Garages/UnloadFromGaragesTest.cs
  Lib9c.Abstractions/IUnloadFromGaragesV1.cs
  Lib9c/Action/Garages/UnloadFromGarages.cs
Labels: Medium

#2202 Update Latest V200092 Data
  Lib9c/TableCSV/Arena/ArenaSheet.csv
  Lib9c/TableCSV/CreateAvatarItemSheet.csv
  Lib9c/TableCSV/GameConfigSheet.csv
  Lib9c/TableCSV/Item/CostumeItemSheet.csv
  Lib9c/TableCSV/Item/CostumeStatSheet.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
Labels: Extra Large

#2200 PDX-20: Implement execute method of UnloadFromGarages
  Lib9c/Action/Garages/UnloadFromGarages.cs
Labels: Small

#2204 PDX-21: Add test case for testing success case
  .Lib9c.Tests/Action/Garages/UnloadFromGaragesTest.cs
  Lib9c/Action/Garages/UnloadFromGarages.cs
Labels: Small

#2205 PDX-38: Add Mailing feature to build unload from garage action
  .Lib9c.Tests/Action/Garages/UnloadFromGaragesTest.cs
  Lib9c/Action/Garages/UnloadFromGarages.cs
Labels: Extra Small

#2208 Limit ClaimItems.ClaimData's size to 100
  .Lib9c.Tests/Action/ClaimItemsTest.cs
  Lib9c/Action/ClaimItems.cs
Labels: Extra Small

#2207 Rename UnloadFromGarages to BulkUnloadFromGarages
  .Lib9c.Tests/Action/Garages/BulkUnloadFromGaragesTest.cs
  Lib9c.Abstractions/IBulkUnloadFromGaragesV1.cs
  Lib9c/Action/Garages/BulkUnloadFromGarages.cs
Labels: Extra Small

#2210 Move `NCStagePolicy` to `NineChronicles.Headless`
  .Lib9c.Tests/Action/RewardGoldTest.cs
  .Lib9c.Tests/StagePolicyTest.cs
  Lib9c.Policy/AccessControlService/IAccessControlService.cs
  Lib9c.Policy/NCStagePolicy.cs
Labels: Large

#2211 [Feature] Add breakdown logs to register product action
  Lib9c/Action/RegisterProduct.cs
Labels: Extra Small

#2190 Introduce MintAssets & BurnAssets
  .Lib9c.Tests/Action/BurnAssetTest.cs
  .Lib9c.Tests/Action/MintAssetsTest.cs
  Lib9c/Action/BurnAsset.cs
  Lib9c/Action/MintAssets.cs
Labels: Extra Large, Squash Needed

#2196 Add goldCurrency argument to BlockHelper.ProposeBlock()
  Lib9c.Utils/BlockHelper.cs
Labels: Extra Small

#2213 Improve market action exectuion time
  Lib9c/Action/CancelProductRegistration.cs
  Lib9c/Action/CancelProductRegistration0.cs
  Lib9c/Action/ReRegisterProduct.cs
  Lib9c/Action/ReRegisterProduct0.cs
  Lib9c/Action/RegisterProduct.cs
  Lib9c/Action/RegisterProduct0.cs
  Lib9c/Action/RegisterProduct2.cs
Labels: Small

#2215 release 1.5.0 pull development
  .Lib9c.Tests/Action/RewardGoldTest.cs
  .Lib9c.Tests/StagePolicyTest.cs
  Lib9c.Policy/AccessControlService/IAccessControlService.cs
  Lib9c.Policy/NCStagePolicy.cs
  Lib9c/Action/CancelProductRegistration.cs
  Lib9c/Action/CancelProductRegistration0.cs
  Lib9c/Action/ReRegisterProduct.cs
  Lib9c/Action/ReRegisterProduct0.cs
  Lib9c/Action/RegisterProduct.cs
  Lib9c/Action/RegisterProduct0.cs
  Lib9c/Action/RegisterProduct2.cs
Labels: Large

#2216 Replace record with struct
  Lib9c/Action/MintAssets.cs
Labels: Extra Small

#2220 Revert nc stage policy
  .Lib9c.Tests/Action/RewardGoldTest.cs
  .Lib9c.Tests/StagePolicyTest.cs
  Lib9c.Policy/AccessControlService/IAccessControlService.cs
  Lib9c.Policy/NCStagePolicy.cs
Labels: Large

#2218 🧹 Remove GetValue<T>() usage
  .Lib9c.Tests/Model/State/LazyStateTest.cs
  Lib9c/Action/ValidatorSetOperate.cs
  Lib9c/Model/Coupons/Coupon.cs
Labels: Extra Small

#2219 🧹 Use bencodability of `Address`
  .Lib9c.Miner.Tests/CustomActionsDeserializableValidatorTest.cs
  Lib9c.MessagePack/AccountStateDelta.cs
  Lib9c/CurrencyExtensions.cs
Labels: Extra Small

#2221 🧹 Remove forced rehearsal extension method
  .Lib9c.Tests/Action/ActionBaseExtensionsTest.cs
  Lib9c/Action/ActionBaseExtensions.cs
Labels: Medium

#2223 Revert 2210 before v200100 daily build
  .Lib9c.Tests/Action/RewardGoldTest.cs
  .Lib9c.Tests/StagePolicyTest.cs
  Lib9c.Policy/AccessControlService/IAccessControlService.cs
  Lib9c.Policy/NCStagePolicy.cs
Labels: Large

#2217 PDX-69: Repeat add item manually for nonFungibleItem in ClaimItems action
  .Lib9c.Tests/Action/ClaimItemsTest.cs
  Lib9c/Action/ClaimItems.cs
Labels: bug, Extra Small

#2227 Allow empty NCG vault
  .Lib9c.Tests/Action/InitializeStatesTest.cs
  .Lib9c.Tests/Action/RewardGoldTest.cs
  .Lib9c.Tests/Model/State/GoldCurrencyStateTest.cs
  Lib9c/Action/InitializeStates.cs
  Lib9c/Action/RewardGold.cs
  Lib9c/Model/State/GoldCurrencyState.cs
Labels: Small

#2228 PDX-22: Add action: BulkUnloadFromGarages
  .Lib9c.Tests/Action/Garages/BulkUnloadFromGaragesTest.cs
  Lib9c.Abstractions/IBulkUnloadFromGaragesV1.cs
  Lib9c/Action/Garages/BulkUnloadFromGarages.cs
Labels: Large

#2226 Support wrapped fav burn & mint
  .Lib9c.Tests/Action/ClaimItemsTest.cs
  .Lib9c.Tests/CurrenciesTest.cs
  Lib9c/Action/ClaimItems.cs
  Lib9c/Currencies.cs
  Lib9c/Model/Mail/ClaimItemsMail.cs
  Lib9c/Model/Mail/IMail.cs
  Lib9c/Model/Mail/Mail.cs
  Lib9c/SerializeKeys.cs
Labels: Large

#2235 increase MaxTransactionPerBlock to 200
  Lib9c.Policy/Policy/BlockPolicySource.cs
Labels: Extra Small

#2230 Update AuraSummon with Sheet model
  .Lib9c.Tests/Action/Scenario/AuraScenarioTest.cs
  .Lib9c.Tests/Action/Summon/AuraSummonTest.cs
  .Lib9c.Tests/Fixtures/TableCSV/Summon/SummonSheetFixtures.cs
  Lib9c/Action/AuraSummon.cs
  Lib9c/TableCSV/Item/EquipmentItemOptionSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemSubRecipeSheetV2.csv
  Lib9c/TableCSV/Summon/SummonSheet.csv
  Lib9c/TableData/Summon/SummonSheet.cs
Labels: enhancement, Extra Large

#2234 Introduce IssueTokenFromGarage
  .Lib9c.Tests/Action/IssueTokensFromGarageTest.cs
  .Lib9c.Tests/Action/MintAssetsTest.cs
  Lib9c/Action/IssueTokensFromGarage.cs
  Lib9c/Action/MintAssets.cs
  Lib9c/Model/FungibleItemValue.cs
Labels: Large

#2237 Fit `MintAssets` to mail system
  .Lib9c.Tests/Action/MintAssetsTest.cs
  Lib9c/Action/MintAssets.cs
Labels: Medium

#2238 Update v200110 Date
  .Lib9c.Tests/Action/DailyReward5Test.cs
  .Lib9c.Tests/Action/DailyReward6Test.cs
  .Lib9c.Tests/Action/DailyRewardTest.cs
  .Lib9c.Tests/Action/Raid5Test.cs
  .Lib9c.Tests/Action/Raid6Test.cs
  .Lib9c.Tests/Model/PlayerTest.cs
  Lib9c/TableCSV/Arena/ArenaSheet.csv
  Lib9c/TableCSV/Cost/EnhancementCostSheetV3.csv
  Lib9c/TableCSV/CreateAvatarItemSheet.csv
  Lib9c/TableCSV/Crystal/CrystalEquipmentGrindingSheet.csv
  Lib9c/TableCSV/GameConfigSheet.csv
  Lib9c/TableCSV/Item/CostumeItemSheet.csv
  Lib9c/TableCSV/Item/CostumeStatSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemOptionSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemSubRecipeSheetV2.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
  Lib9c/TableCSV/Quest/QuestItemRewardSheet.csv
  Lib9c/TableCSV/Quest/QuestRewardSheet.csv
  Lib9c/TableCSV/Quest/WorldQuestSheet.csv
  Lib9c/TableCSV/RedeemRewardSheet.csv
  Lib9c/TableCSV/Rune/RuneOptionSheet.csv
  Lib9c/TableCSV/RuneCostSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableCSV/Summon/SummonSheet.csv
  Lib9c/TableCSV/WorldAndStage/StageDialogSheet.csv
  Lib9c/TableCSV/WorldAndStage/StageWaveSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
Labels: Extra Large

#2239 AssetMinters to genesis & `MintAssets`
  .Lib9c.Tests/Action/InitializeStatesTest.cs
  .Lib9c.Tests/Action/MintAssetsTest.cs
  Lib9c.Utils/BlockHelper.cs
  Lib9c/Action/InitializeStates.cs
  Lib9c/Action/InvalidMinterException.cs
  Lib9c/Action/MintAssets.cs
  Lib9c/Addresses.cs
Labels: Medium

#2242 Add `BuffFactory.GetBuffsForArena()`
  Lib9c/Action/BattleArena.cs
  Lib9c/Arena/ArenaSimulator.cs
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/Model/Character/ArenaCharacter.cs
Labels: Small

#2241 Update World Boss 1wave Balance
  Lib9c/TableCSV/WorldBoss/WorldBossCharacterSheet.csv
Labels: Extra Small

#2189 Introduce `Planet` and separate the action obsoletions by them
  .Lib9c.Tests/Policy/BlockPolicySourceTest.cs
  Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
  Lib9c/Action/ActionObsoleteAttribute.cs
  Lib9c/Action/ActionObsoleteAttributeExtension.cs
  Lib9c/Planet.cs
  Lib9c/PlanetExtension.cs
Labels: Medium

#2244 Update Equipment Item EXP Value Change
  Lib9c/TableCSV/Item/EquipmentItemSheet.csv
Labels: Medium

#2254 do not call ACS when iterating chain
  Lib9c.Policy/NCStagePolicy.cs
Labels: bug, Extra Small

#2253 🧹 Remove `AccountStateDeltaFormatter`
  Lib9c.MessagePack/Formatters/AccountStateDeltaFormatter.cs
  Lib9c.MessagePack/Formatters/NineChroniclesResolverGetFormatterHelper.cs
Labels: Extra Small

#2252 ♻️ 🧹 Reduce `IAccountDelta` usage
  .Lib9c.Tests/Action/RewardGoldTest.cs
  .Lib9c.Tests/Action/Snapshot/TransferAsset0SnapshotTest.cs
  .Lib9c.Tests/Action/Snapshot/transfer_asset.TransferCrystal.diff.verified.txt
  .Lib9c.Tests/Action/Snapshot/transfer_asset.TransferCrystal.fungibles.verified.txt
  .Lib9c.Tests/Action/Snapshot/transfer_asset.TransferCrystal.summary.verified.txt
  .Lib9c.Tests/Action/Snapshot/transfer_asset.TransferWithMemo.diff.verified.txt
  .Lib9c.Tests/Action/Snapshot/transfer_asset.TransferWithMemo.fungibles.verified.txt
  .Lib9c.Tests/Action/Snapshot/transfer_asset.TransferWithMemo.summary.verified.txt
  .Lib9c.Tools/SubCommand/State.cs
Labels: Medium

#2262 introduce: `IPluginKeyValueStore`
  .Lib9c.Plugin.Shared/IPluginKeyValueStore.cs
  .Libplanet.Extensions.PluginActionEvaluator/PluginRocksDBKeyValueStore.cs
Labels: Extra Small
