Repository planetarium/lib9c, pull requests merged in 2023-03, with the labels that each got.

#1768 obsolete transfer asset2
  .Lib9c.Tests/Action/TransferAsset2Test.cs
  Lib9c/Action/TransferAsset2.cs
Labels: Extra Small

#1767 Add championship for avoid exception
  Lib9c/TableCSV/Arena/ArenaSheet.csv
Labels: Extra Small

#1769 main merge v100371
  .Lib9c.Tests/Action/TransferAsset2Test.cs
  Lib9c/Action/TransferAsset2.cs
Labels: Extra Small

#1757 Check whether the build passed or failed in several configurations and frameworks
  .github/workflows/main.yml
  Lib9c.DevExtensions/Utils.cs
Labels: Extra Small

#1774 Add parameterless constructor for activator
  Lib9c/Action/SecureMiningReward.cs
Labels: bug, Extra Small

#1707 New coupon system to replace existing redeem code
  .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
  .Lib9c.Tests/Action/AccountStateViewExtensionsTest.cs
  .Lib9c.Tests/Action/Coupons/CouponsFixture.cs
  .Lib9c.Tests/Action/Coupons/IssueCouponsTest.cs
  .Lib9c.Tests/Action/Coupons/RedeemCouponTest.cs
  .Lib9c.Tests/Action/Coupons/TransferCouponsTest.cs
  .Lib9c.Tests/Action/TransferAsset2Test.cs
  .Lib9c.Tests/Model/Coupons/CouponTest.cs
  .Lib9c.Tests/Model/Coupons/RewardSetTest.cs
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/AccountStateViewExtensions.cs
  Lib9c/Action/Coupons/IssueCoupons.cs
  Lib9c/Action/Coupons/RedeemCoupon.cs
  Lib9c/Action/Coupons/TransferCoupons.cs
  Lib9c/Action/TransferAsset2.cs
  Lib9c/Model/Coupons/Coupon.cs
  Lib9c/Model/Coupons/RewardSet.cs
  Lib9c/SerializeKeys.cs
Labels: Extra Large

#1776 ci: Remove `DevEx` configuration in build-and-test workflow
  .github/workflows/main.yml
Labels: Extra Small

#1746 Introduce `ManipulateState` action for easier test environment setting
  .Lib9c.DevExtensions.Tests/Action/Craft/UnlocakCraftActionTest.cs
  .Lib9c.DevExtensions.Tests/Action/Craft/UnlockRecipeTest.cs
  .Lib9c.DevExtensions.Tests/Action/ManipulateStateTest.cs
  .Lib9c.DevExtensions.Tests/Action/Stage/ClearStageTest.cs
  .Lib9c.Tests/Util/InitializeUtil.cs
  Lib9c.DevExtensions/Action/Craft/UnlockCraftAction.cs
  Lib9c.DevExtensions/Action/Craft/UnlockRecipe.cs
  Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
  Lib9c.DevExtensions/Action/ManipulateState.cs
  Lib9c.DevExtensions/Action/Stage/ClearStage.cs
  Lib9c/Model/Quest/QuestList.cs
  Lib9c/Model/State/StateExtensions.cs
Labels: enhancement, Extra Large

#1762 Fix project output path and rename directory minor
  Lib9c.Policy/Lib9c.Policy.csproj
  Lib9c.Renderers/Lib9c.Renderers.csproj
  Lib9c.Renderers/Renderers/ActionRenderer.cs
  Lib9c.Renderers/Renderers/BlockRenderer.cs
  Lib9c.Utils/Lib9c.Utils.csproj
Labels: Small

#1780 Remove `Swarm<T>` from `Miner`
  Lib9c.Miner/Miner.cs
  Lib9c.Miner/ReorgMiner.cs
Labels: Small

#1777 Prevent register shop item
  Lib9c/Action/Sell.cs
  Lib9c/Action/UpdateSell.cs
Labels: Extra Small

#1784 Add changes made to pow-dynamic-validators
  .Lib9c.Benchmarks/Program.cs
  .Lib9c.Tests/Policy/BlockPolicyTest.cs
  Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
  Lib9c.Policy/Policy/BlockPolicySource.cs
  Lib9c.Policy/Policy/ValidatorAdminPolicy.cs
  Lib9c.Renderers/Renderer/ActionRenderer.cs
Labels: Large

#1786 Suppress warnings while collecting action type ids
  .github/workflows/main.yml
Labels: bug, ci, Extra Small

#1785 Add ap cost new market action
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/CancelProductRegistrationTest.cs
  .Lib9c.Tests/Action/ReRegisterProductTest.cs
  .Lib9c.Tests/Action/RegisterProductTest.cs
  .Lib9c.Tests/Action/Scenario/MarketScenarioTest.cs
  .Lib9c.Tests/Action/SellCancellationTest.cs
  .Lib9c.Tests/Model/State/AvatarStateTest.cs
  Lib9c/Action/CancelProductRegistration.cs
  Lib9c/Action/ReRegisterProduct.cs
  Lib9c/Action/RegisterProduct.cs
  Lib9c/Model/State/AvatarState.cs
Labels: Medium

#1791 Bug fix on calculating pet effect
  .Lib9c.Tests/Helper/PetHelperTest.cs
  .Lib9c.Tests/TableData/Pet/PetCostSheetTest.cs
  .Lib9c.Tests/TableData/Pet/PetSheetTest.cs
  Lib9c/Action/PetEnhancement.cs
  Lib9c/Helper/PetHelper.cs
  Lib9c/TableData/Pet/PetCostSheet.cs
  Lib9c/TableData/Pet/PetSheet.cs
Labels: Extra Small

#1795 chore: fix API mismatch
  Lib9c.Policy/Policy/BlockPolicySource.cs
Labels: Extra Small, pbft

#1792 prepare v100380 pull market changes
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/CancelProductRegistrationTest.cs
  .Lib9c.Tests/Action/ReRegisterProductTest.cs
  .Lib9c.Tests/Action/RegisterProductTest.cs
  .Lib9c.Tests/Action/Scenario/MarketScenarioTest.cs
  .Lib9c.Tests/Action/SellCancellationTest.cs
  .Lib9c.Tests/Model/State/AvatarStateTest.cs
  Lib9c/Action/CancelProductRegistration.cs
  Lib9c/Action/ReRegisterProduct.cs
  Lib9c/Action/RegisterProduct.cs
  Lib9c/Action/Sell.cs
  Lib9c/Action/UpdateSell.cs
  Lib9c/Model/State/AvatarState.cs
Labels: Medium

#1797 introduce: delay action
  Lib9c/Action/DelayAction.cs
Labels: Extra Small

#1798 Fix burn behavior in SecureMiningReward to transferring
  .Lib9c.Tests/Action/SecureMiningRewardTest.cs
  Lib9c/Action/SecureMiningReward.cs
Labels: Extra Small

#1800 [DevEx] feat: Apply balance list to ManipulateState action
  .Lib9c.DevExtensions.Tests/Action/Craft/UnlocakCraftActionTest.cs
  .Lib9c.DevExtensions.Tests/Action/ManipulateStateTest.cs
  .Lib9c.Tests/Util/InitializeUtil.cs
  Lib9c.DevExtensions/Action/ManipulateState.cs
Labels: Medium

#1802 [DevEx] fix: `PlaneValue` of `ManipulateState`
  .Lib9c.DevExtensions.Tests/Action/ManipulateStateTest.cs
  Lib9c.DevExtensions/Action/ManipulateState.cs
Labels: bug, Small

#1809 Remove applying pet effect on `ItemEnhancement`
  .Lib9c.Tests/Action/ItemEnhancement11Test.cs
  .Lib9c.Tests/Action/ItemEnhancementTest.cs
  .Lib9c.Tests/Action/Scenario/Pet/IncreaseBlockPerHourglassTest.cs
  .Lib9c.Tests/Action/Scenario/Pet/ReduceRequiredBlockTest.cs
  Lib9c/Action/AttachmentActionResult.cs
  Lib9c/Action/ItemEnhancement.cs
  Lib9c/Action/ItemEnhancement11.cs
  Lib9c/Extensions/CombinationSlotStateExtensions.cs
Labels: Extra Large

#1810 Release v100372
  .Lib9c.Tests/Action/SecureMiningRewardTest.cs
  Lib9c/Action/SecureMiningReward.cs
Labels: Extra Small

#1812 Set market actions capacity
  .Lib9c.Tests/Action/BuyProductTest.cs
  .Lib9c.Tests/Action/CancelProductRegistrationTest.cs
  .Lib9c.Tests/Action/ReRegisterProductTest.cs
  .Lib9c.Tests/Action/RegisterProductTest.cs
  Lib9c/Action/BuyProduct.cs
  Lib9c/Action/CancelProductRegistration.cs
  Lib9c/Action/ReRegisterProduct.cs
  Lib9c/Action/RegisterProduct.cs
Labels: Extra Small

#1821 Separate `SetState` duration measurement with serialization duration measurement
  Lib9c/Action/HackAndSlash.cs
Labels: Extra Small

#1824 Parallel loop instead of getStates
  Lib9c/Action/AccountStateViewExtensions.cs
Labels: Small

#1825 Fix bug on getStateSw and add AvatarState deserialization timer
  Lib9c/Action/AccountStateViewExtensions.cs
Labels: Extra Small

#1827 Reduce get state in TryGetAvatarStateV2
  Lib9c/Action/AccountStateViewExtensions.cs
Labels: Extra Small

#1819 [DevEx] Extend `CreateOrReplaceAvatar`
  .Lib9c.DevExtensions.Tests/Action/CreateOrReplaceAvatarTest.cs
  .Lib9c.DevExtensions.Tests/Action/Factory/CreateOrReplaceAvatarFactoryTest.cs
  .Lib9c.DevExtensions.Tests/Lib9c.DevExtensions.Tests.csproj
  Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
  Lib9c.DevExtensions/Action/Factory/CreateOrReplaceAvatarFactory.cs
  Lib9c.DevExtensions/Action/Interface/ICreateOrReplaceAvatar.cs
  Lib9c.DevExtensions/RandomImpl.cs
Labels: Extra Large

#1829 ♻️ Refactor optimize mail and item encoding
  Lib9c/Model/Item/Consumable.cs
  Lib9c/Model/Item/Costume.cs
  Lib9c/Model/Item/Equipment.cs
  Lib9c/Model/Item/Inventory.cs
  Lib9c/Model/Item/ItemUsable.cs
  Lib9c/Model/Item/Material.cs
  Lib9c/Model/Item/ShopItem.cs
  Lib9c/Model/Mail/AttachmentMail.cs
  Lib9c/Model/Mail/CancelOrderMail.cs
  Lib9c/Model/Mail/GrindingMail.cs
  Lib9c/Model/Mail/Mail.cs
  Lib9c/Model/Mail/MaterialCraftMail.cs
  Lib9c/Model/Mail/OrderBuyerMail.cs
  Lib9c/Model/Mail/OrderExpirationMail.cs
  Lib9c/Model/Mail/OrderSellerMail.cs
  Lib9c/Model/Mail/ProductBuyerMail.cs
  Lib9c/Model/Mail/ProductCancelMail.cs
  Lib9c/Model/Mail/ProductSellerMail.cs
Labels: Large

#1835 [DevEx]Refactor `ManipulateState`
  Lib9c.DevExtensions/Action/ManipulateState.cs
Labels: Extra Small

#1840 [DevEx]Extend `CreateOrReplaceAvatar`
  .Lib9c.DevExtensions.Tests/Action/CreateOrReplaceAvatarTest.cs
  .Lib9c.DevExtensions.Tests/Action/Factory/CreateOrReplaceAvatarFactoryTest.cs
  Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
  Lib9c.DevExtensions/Action/Factory/CreateOrReplaceAvatarFactory.cs
  Lib9c.DevExtensions/Action/Interface/ICreateOrReplaceAvatar.cs
  Lib9c.sln.DotSettings
  Lib9c/Addresses.cs
Labels: Large
