Repository planetarium/lib9c, pull requests merged in 2023-04, with the labels that each got.

#1851 Merge v100382-1 to development
  Lib9c.Policy/Policy/MinBlockProtocolVersionPolicy.cs
Labels: Extra Small

#1855 feat: Introduce `Currencies`
  .Lib9c.DevExtensions.Tests/Action/FaucetRuneTest.cs
  .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
  .Lib9c.Tests/Action/ClaimRaidRewardTest.cs
  .Lib9c.Tests/Action/ClaimWorldBossKillRewardTest.cs
  .Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs
  .Lib9c.Tests/CurrenciesTest.cs
  Lib9c.sln.DotSettings
  Lib9c/Currencies.cs
  Lib9c/Helper/CrystalCalculator.cs
  Lib9c/Helper/PetHelper.cs
  Lib9c/Helper/RuneHelper.cs
Labels: Small

#1861 ClaimStakeReward4 action with hard-coded old data
  .Lib9c.Tests/Action/ClaimStakeReward2Test.cs
  .Lib9c.Tests/Action/ClaimStakeReward3Test.cs
  .Lib9c.Tests/Action/Factory/ClaimStakeRewardFactoryTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeReward2ScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeReward3ScenarioTest.cs
  .Lib9c.Tests/Model/State/StakeStateTest.cs
  Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Action/ClaimStakeReward2.cs
  Lib9c/Action/Factory/ClaimStakeRewardFactory.cs
  Lib9c/Model/State/StakeState.cs
Labels: enhancement

#1862 Stake reward update target is fixed
  Lib9c/Model/State/StakeState.cs
Labels: enhancement

#1869 Make old stake reward data to public
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Model/State/StakeState.cs
Labels: bug

#1870 Make old stake reward data to public
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Model/State/StakeState.cs
Labels: bug
