Repository planetarium/lib9c, pull requests merged in 2023-09, with the labels that each got.

#2122 Backmerge 1.0.0 to development
  .Lib9c.Tests/Model/Item/EquipmentTest.cs
  Lib9c/Model/Item/Equipment.cs
Labels: Extra Small

#2123 Add AuraSummon constructor with field data
  .Lib9c.Tests/Action/AuraSummonTest.cs
  Lib9c/Action/AuraSummon.cs
Labels: enhancement, Extra Small

#2130 chore: add comments to StakeStateUtils
  Lib9c/Model/Stake/StakeStateUtils.cs
Labels: No Changes

#2129 Update aura summon
  .Lib9c.Tests/Action/Summon/AuraSummonTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AuraSummon.cs
  Lib9c/Action/Exceptions/InvalidSummonCountException.cs
  Lib9c/Helper/SummonHelper.cs
  Lib9c/TableCSV/Summon/SummonSheet.csv
  Lib9c/TableCSV/Summon/SummonSheet.csv.meta
  Lib9c/TableData/Summon/AuraSummonSheet.cs
  Lib9c/TableData/Summon/SummonSheet.cs
Labels: bug, enhancement, Medium

#2131 Add .gitallowed for git secrets
  .gitallowed
Labels: Extra Small

#2132 chore: work a few unit tests
  .Lib9c.Tests/Model/Stake/ContractTest.cs
  .Lib9c.Tests/Model/Stake/StakeStateV2Test.cs
  Lib9c/Model/Stake/Contract.cs
Labels: Extra Small

#2133 Fix aura duplicate equip
  .Lib9c.Tests/Action/Scenario/AuraScenarioTest.cs
  Lib9c/GameConfig.cs
  Lib9c/Model/State/AvatarState.cs
Labels: Extra Small

#2144 Update Lib9c version to 1.1.0
  Lib9c/Lib9c.csproj
Labels: Extra Small

#2145 add aura slot and equip level limit config
  Lib9c/GameConfig.cs
  Lib9c/Model/State/AvatarState.cs
  Lib9c/TableData/UnlockHelper.cs
Labels: Extra Small

#2142 feat(Dashboard): use 9c-headless instead of empty-chronicle
  Dashboard/src/App.tsx
Labels: Extra Small, Dashboard

#2149 Fix nuget published lib9c dependency
  .github/workflows/publish.yml
Labels: Extra Small

#2151 Update V200080ObsoleteIndex
  Lib9c/ActionObsoleteConfig.cs
Labels: Extra Small

#2147 more unit tests for "stake3" and "claim_stake_reward9"
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimScenarioTest.cs
  .Lib9c.Tests/Action/StakeTest.cs
  .Lib9c.Tests/Fixtures/TableCSV/Stake/StakePolicySheetFixtures.cs
  .Lib9c.Tests/Model/WorldInformationTest.cs
Labels: Extra Large

#2156 fix: remove `IRenderer`s from `BlockPolicySource`
  .Lib9c.Benchmarks/Program.cs
  .Lib9c.Tests/Action/RewardGoldTest.cs
  .Lib9c.Tests/Policy/BlockPolicyTest.cs
  .Lib9c.Tests/StagePolicyTest.cs
  Lib9c.DevExtensions/Utils.cs
  Lib9c.Policy/Policy/BlockPolicySource.cs
  Lib9c.Utils/BlockHelper.cs
Labels: Small

#2148 Add ClaimItems action
  .Lib9c.Tests/Action/ClaimItemsTest.cs
  Lib9c/Action/ClaimItems.cs
  Lib9c/Action/IClaimItems.cs
  Lib9c/SerializeKeys.cs
Labels: Large
