Repository planetarium/lib9c, pull requests merged in 2023-08, with the labels that each got.

#2044 ci(gh-actions): upload lib9c-stateservice build result
  .Lib9c.StateService/Lib9c.StateService.csproj
  .github/workflows/main.yml
  .github/workflows/publish.yml
Labels: ci, Extra Small

#2045 ci(gh-actions): run publish workflow in development branch
  .github/workflows/publish.yml
Labels: Extra Small

#2046 ci(gh-actions): correct GitHub Actions workflow syntax
  .github/workflows/main.yml
  .github/workflows/publish.yml
  .github/workflows/validate-github-actions-workflows.yml
Labels: Extra Small

#2047 ci(gh-actions): specify AWS region
  .github/workflows/publish.yml
Labels: bug, ci, Extra Small

#2049 fix(lib9c-stateservice): rollback single file publish
  .Lib9c.StateService/Lib9c.StateService.csproj
Labels: bug

#2040 chore: specify version for Lib9c package
  Lib9c/Lib9c.csproj
Labels: Extra Small

#2042 Add dashboard providing obsolete action information
  .Lib9c.Tools/SubCommand/Action.cs
  .github/workflows/gh-page.yml
  .github/workflows/main.yml
  Dashboard/.env.example
  Dashboard/.eslintrc.cjs
  Dashboard/.gitignore
  Dashboard/.prettier.config.js
  Dashboard/README.md
  Dashboard/index.html
  Dashboard/package.json
  Dashboard/postcss.config.js
  Dashboard/src/App.tsx
  Dashboard/src/index.css
  Dashboard/src/main.tsx
  Dashboard/src/vite-env.d.ts
  Dashboard/tailwind.config.js
  Dashboard/tsconfig.json
  Dashboard/tsconfig.node.json
  Dashboard/vite.config.ts
  Dashboard/yarn.lock
Labels: Large, Squash Needed

#2052 fix(action-evaluator-common-components): link action evaluation states
  .Libplanet.Extensions.ActionEvaluatorCommonComponents/AccountStateDelta.cs
  .Libplanet.Extensions.RemoteActionEvaluator/RemoteActionEvaluator.cs
Labels: bug, Extra Small

#2060 Prepare 0.5.0
  Lib9c/Lib9c.csproj
Labels: Extra Small

#2057 Optimize HackAndSlash.Execute #3
  Lib9c/Battle/CPHelper.cs
  Lib9c/Model/Buff/ActionBuff.cs
  Lib9c/Model/Buff/Bleed.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Stat/Stats.cs
Labels: Small

#2063 feat: add `Serilog` logger in `StateService`
  .Lib9c.StateService/Lib9c.StateService.csproj
  .Lib9c.StateService/Program.cs
Labels: Extra Small

#2067 Prepare aura equipment
  .Lib9c.Tests/Action/Scenario/AuraScenarioTest.cs
  .Lib9c.Tests/Model/PlayerTest.cs
  Lib9c/Model/Character/EnemyPlayer.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Model/Item/Aura.cs
  Lib9c/Model/Item/ItemFactory.cs
  Lib9c/Model/Item/ItemType.cs
  Lib9c/Model/State/AvatarState.cs
  Lib9c/TableCSV/Item/EquipmentItemSheet.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
Labels: Medium

#2070 equip aura in WorldBoss, Arena
  .Lib9c.Tests/Action/Scenario/AuraScenarioTest.cs
Labels: Large

#2084 Obsolete old ItemEnhancement action
  .Lib9c.Tests/Action/ItemEnhancement11Test.cs
  .Lib9c.Tests/Action/ItemEnhancementTest.cs
  .Lib9c.Tests/Model/Item/EquipmentTest.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Action/ItemEnhancement.cs
  Lib9c/Action/ItemEnhancement11.cs
  Lib9c/Model/Item/Equipment.cs
Labels: Extra Small

#2090 🐛 Fix `ValidatorSetOperate`
  .Lib9c.Tests/Action/ValidatorSetOperateTest.cs
  Lib9c/Action/GameAction.cs
  Lib9c/Action/ValidatorSetOperate.cs
Labels: Small

#2093 Back-merge 0.5.2
  .Lib9c.Tests/Action/ValidatorSetOperateTest.cs
  Lib9c/Action/GameAction.cs
  Lib9c/Action/ValidatorSetOperate.cs
Labels: Small

#2098 Update all avatar related states
  Lib9c/Action/ItemEnhancement.cs
Labels: bug, Extra Small

#2100 Introduce AuraSummon action
  .Lib9c.Tests/Action/AuraSummonTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c.Abstractions/IAuraSummonV1.cs
  Lib9c/Action/AuraSummon.cs
  Lib9c/Model/Mail/IMail.cs
  Lib9c/Model/Mail/Mail.cs
  Lib9c/Model/Mail/SummonMail.cs
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
  Lib9c/TableCSV/Summon/AuraSummonSheet.csv
  Lib9c/TableData/Summon/AuraSummonSheet.cs
Labels: enhancement, Large

#2101 add EnhancementCostSheetV3.csv.meta file
  Lib9c/TableCSV/Cost/EnhancementCostSheetV3.csv.meta
Labels: Extra Small

#2102 Change required block calculation logic
  .Lib9c.Tests/Action/ItemEnhancementTest.cs
  Lib9c/Action/ItemEnhancement.cs
Labels: Extra Small

#2104 Fix GitHub ci
  .github/bin/dist-pack.sh
  .github/workflows/publish.yml
Labels: Extra Small

#2108 Improve claim stake reward8
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Action/ClaimStakeReward7.cs
  Lib9c/ActionObsoleteConfig.cs
  Lib9c/Currencies.cs
Labels: Medium

#2114 Handle enhancement of level 0 to 0 case
  .Lib9c.Tests/Action/ItemEnhancementTest.cs
  .Lib9c.Tests/Model/Item/EquipmentTest.cs
  Lib9c/Action/ItemEnhancement.cs
  Lib9c/Model/Item/Equipment.cs
  Lib9c/TableCSV/Item/EquipmentItemSheet.csv
Labels: bug

#2112 fix trigger conditions of "main" workflow
  .github/workflows/main.yml
Labels: Extra Small

#2115 Introduce Aura Summon action
  .Lib9c.Tests/Action/AuraSummonTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c.Abstractions/IAuraSummonV1.cs
  Lib9c/Action/AuraSummon.cs
  Lib9c/Helper/SummonHelper.cs
  Lib9c/Model/Mail/IMail.cs
  Lib9c/Model/Mail/Mail.cs
  Lib9c/Model/Mail/SummonMail.cs
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
  Lib9c/TableCSV/Summon/AuraSummonSheet.csv
  Lib9c/TableData/Summon/AuraSummonSheet.cs
Labels: enhancement, Large

#2117 Serialize Exp field only when it has positive value
  .Lib9c.Tests/Model/Item/EquipmentTest.cs
  Lib9c/Model/Item/Equipment.cs
Labels: bug, Extra Small

#2116 Aura summon does not create mail
  Lib9c/Action/AuraSummon.cs
  Lib9c/Model/Mail/IMail.cs
  Lib9c/Model/Mail/SummonMail.cs
Labels: enhancement, Extra Small

#2118 Update recipe ID in aura summon sheet
  Lib9c/Action/AuraSummon.cs
  Lib9c/TableCSV/Summon/AuraSummonSheet.csv
Labels: enhancement, Extra Small

#2121 Add options to summoned aura equipment
  .Lib9c.Tests/Action/AuraSummonTest.cs
  Lib9c/Action/AuraSummon.cs
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
Labels: enhancement
