Repository planetarium/lib9c, pull requests merged in 2023-06, with the labels that each got.

#1950 stage tx check patron balance instead of block index
  .Lib9c.Tests/Policy/BlockPolicyTest.cs
  Lib9c.Policy/Policy/BlockPolicySource.cs
  Lib9c.Utils/BlockHelper.cs
  Lib9c/MeadConfig.cs
Labels: Extra Small

#1952 Update TransferAsset gas fee
  Lib9c/Action/TransferAsset.cs
  Lib9c/Action/TransferAssets.cs
Labels: Extra Small

#1955 Add gas fee in old actions
  Lib9c/Action/ActivateAccount.cs
  Lib9c/Action/AddActivatedAccount.cs
  Lib9c/Action/BattleArena8.cs
  Lib9c/Action/BattleGrandFinale1.cs
  Lib9c/Action/Buy11.cs
  Lib9c/Action/ClaimStakeReward1.cs
  Lib9c/Action/CombinationEquipment12.cs
  Lib9c/Action/CombinationEquipment14.cs
  Lib9c/Action/CombinationEquipment15.cs
  Lib9c/Action/CombinationEquipment9.cs
  Lib9c/Action/CreateAvatar6.cs
  Lib9c/Action/CreateAvatar7.cs
  Lib9c/Action/CreatePendingActivation.cs
  Lib9c/Action/CreatePendingActivations.cs
  Lib9c/Action/DailyReward6.cs
  Lib9c/Action/EventDungeonBattleV1.cs
  Lib9c/Action/HackAndSlash15.cs
  Lib9c/Action/HackAndSlash16.cs
  Lib9c/Action/HackAndSlash17.cs
  Lib9c/Action/HackAndSlashSweep6.cs
  Lib9c/Action/ItemEnhancement10.cs
  Lib9c/Action/MigrationLegacyShop.cs
  Lib9c/Action/MimisbrunnrBattle10.cs
  Lib9c/Action/RankingBattle11.cs
  Lib9c/Action/RapidCombination8.cs
  Lib9c/Action/Sell.cs
  Lib9c/Action/Stake0.cs
  Lib9c/Action/TransferAsset3.cs
  Lib9c/Action/TransferAssets0.cs
  Lib9c/Action/UnlockEquipmentRecipe1.cs
  Lib9c/Action/UnlockWorld1.cs
  Lib9c/Action/UpdateSell.cs
Labels: Extra Small

#1954 Set GARAGE currency as a reword of the monster collection system
  .Lib9c.Tests/Action/ClaimStakeReward3Test.cs
  .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeReward3ScenarioTest.cs
  .Lib9c.Tests/Model/State/StakeStateTest.cs
  .Lib9c.Tests/TableData/StakeRegularRewardSheetTest.cs
  .Lib9c.Tests/Util/InitializeUtil.cs
  Lib9c.sln.DotSettings
  Lib9c/Action/AccountStateDeltaExtensions.cs
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Action/ClaimStakeReward1.cs
  Lib9c/Action/ClaimStakeReward2.cs
  Lib9c/Action/Stake.cs
  Lib9c/Action/Stake0.cs
  Lib9c/ActionObsoleteConfig.cs
  Lib9c/Currencies.cs
  Lib9c/Model/State/StakeState.cs
  Lib9c/TableCSV/StakeRegularFixedRewardSheet.csv
  Lib9c/TableCSV/StakeRegularRewardSheet.csv
  Lib9c/TableData/StakeRegularFixedRewardSheet.cs
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: Extra Large

#1959 Introduce `LoadIntoMyGarages` action
  .Lib9c.Tests/Action/ExceptionTest.cs
  .Lib9c.Tests/Action/Garages/LoadIntoMyGaragesTest.cs
  .Lib9c.Tests/CurrenciesTest.cs
  .Lib9c.Tests/Model/Garages/FungibleItemGarageTest.cs
  .Lib9c.Tests/TableData/Garages/LoadIntoMyGaragesCostSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c.Abstractions/ILoadIntoMyGarages.cs
  Lib9c.sln.DotSettings
  Lib9c/Action/AccountStateViewExtensions.cs
  Lib9c/Action/Garages/GarageUtils.cs
  Lib9c/Action/Garages/LoadIntoMyGarages.cs
  Lib9c/Action/PetEnhancement.cs
  Lib9c/Addresses.cs
  Lib9c/Currencies.cs
  Lib9c/Exceptions/InvalidActionFieldException.cs
  Lib9c/Exceptions/ItemNotFoundException.cs
  Lib9c/Exceptions/NotEnoughItemException.cs
  Lib9c/Exceptions/StateNullException.cs
  Lib9c/Model/Garages/FungibleItemGarage.cs
  Lib9c/Model/Garages/IFungibleItemGarage.cs
  Lib9c/Model/Garages/IGarage.cs
  Lib9c/Model/Item/Inventory.cs
  Lib9c/Model/Item/ItemBase.cs
  Lib9c/Model/Item/Material.cs
  Lib9c/TableCSV/Garages/LoadIntoMyGaragesCostSheet.csv
  Lib9c/TableData/Garages/LoadIntoMyGaragesCostSheet.cs
Labels: Extra Large

#1961 Introduce `DeliverToOthersGarages` action
  .Lib9c.Tests/Action/Garages/DeliverToOthersGaragesTest.cs
  Lib9c.Abstractions/IDeliverToOthersGarages.cs
  Lib9c/Action/Garages/DeliverToOthersGarages.cs
Labels: Extra Large

#1962 Introduce `UnloadFromMyGarages` action
  .Lib9c.Tests/Action/Garages/UnloadFromMyGaragesTest.cs
  Lib9c.Abstractions/IUnloadFromMyGarages.cs
  Lib9c/Action/Garages/UnloadFromMyGarages.cs
Labels: Extra Large

#1967 Repair incorrectly modified indexes
  Lib9c/Action/ClaimStakeReward1.cs
  Lib9c/Action/Stake0.cs
Labels: bug, Extra Small

#1968 Make `mimisbrunnr_battle13` obsolete on V200030
  Lib9c/Action/MimisbrunnrBattle.cs
Labels: Extra Small

#1972 Apply "claim_stake_reward4" to `ClaimStakeRewardFactory`
  .Lib9c.Tests/Action/Factory/ClaimStakeRewardFactoryTest.cs
  Lib9c/Action/Factory/ClaimStakeRewardFactory.cs
Labels: Extra Small

#1965 Update WorldBoss 23. 3~4Q List Add
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
Labels: Extra Small

#1973 Fix mimisbrunnr check method on `CreateAvatar` in editor
  Lib9c/Action/CreateAvatar.cs
Labels: Extra Small

#1977 Use Integer type instead of Text
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  Lib9c/Action/CreatePledge.cs
Labels: Extra Small

#1978 update submodule-updater to bump `release/*` branches
  .github/workflows/main.yml
Labels: Extra Small

#1980 Fix duplicate UseGas called
  .Lib9c.Tests/Action/Scenario/MeadScenarioTest.cs
  Lib9c/Action/ActivateAccount.cs
  Lib9c/Action/AddActivatedAccount.cs
  Lib9c/Action/BattleArena8.cs
  Lib9c/Action/BattleGrandFinale1.cs
  Lib9c/Action/Buy11.cs
  Lib9c/Action/ClaimMonsterCollectionReward.cs
  Lib9c/Action/CombinationEquipment12.cs
  Lib9c/Action/CombinationEquipment14.cs
  Lib9c/Action/CombinationEquipment15.cs
  Lib9c/Action/CombinationEquipment9.cs
  Lib9c/Action/CreateAvatar6.cs
  Lib9c/Action/CreateAvatar7.cs
  Lib9c/Action/CreatePendingActivation.cs
  Lib9c/Action/DailyReward6.cs
  Lib9c/Action/EventDungeonBattleV1.cs
  Lib9c/Action/HackAndSlash16.cs
  Lib9c/Action/HackAndSlash17.cs
  Lib9c/Action/HackAndSlashSweep6.cs
  Lib9c/Action/ItemEnhancement10.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Action/MigrationLegacyShop.cs
  Lib9c/Action/MimisbrunnrBattle.cs
  Lib9c/Action/MimisbrunnrBattle10.cs
  Lib9c/Action/RankingBattle11.cs
  Lib9c/Action/RapidCombination8.cs
  Lib9c/Action/Sell.cs
  Lib9c/Action/TransferAsset3.cs
  Lib9c/Action/TransferAssets0.cs
  Lib9c/Action/UnlockEquipmentRecipe1.cs
  Lib9c/Action/UnlockWorld1.cs
  Lib9c/Action/UpdateSell.cs
Labels: Extra Small

#1981 Add new column IsEnhanceable to StatBuffSheet
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableData/Skill/StatBuffSheet.cs
  Lib9c/TableData/TableExtensions.cs
Labels: Large

#1984 Development merge main
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/Scenario/MeadScenarioTest.cs
  Lib9c/Action/ActivateAccount.cs
  Lib9c/Action/AddActivatedAccount.cs
  Lib9c/Action/BattleArena8.cs
  Lib9c/Action/BattleGrandFinale1.cs
  Lib9c/Action/Buy11.cs
  Lib9c/Action/ClaimMonsterCollectionReward.cs
  Lib9c/Action/CombinationEquipment12.cs
  Lib9c/Action/CombinationEquipment14.cs
  Lib9c/Action/CombinationEquipment15.cs
  Lib9c/Action/CombinationEquipment9.cs
  Lib9c/Action/CreateAvatar6.cs
  Lib9c/Action/CreateAvatar7.cs
  Lib9c/Action/CreatePendingActivation.cs
  Lib9c/Action/CreatePledge.cs
  Lib9c/Action/DailyReward6.cs
  Lib9c/Action/EventDungeonBattleV1.cs
  Lib9c/Action/HackAndSlash16.cs
  Lib9c/Action/HackAndSlash17.cs
  Lib9c/Action/HackAndSlashSweep6.cs
  Lib9c/Action/ItemEnhancement10.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Action/MigrationLegacyShop.cs
  Lib9c/Action/MimisbrunnrBattle.cs
  Lib9c/Action/MimisbrunnrBattle10.cs
  Lib9c/Action/RankingBattle11.cs
  Lib9c/Action/RapidCombination8.cs
  Lib9c/Action/Sell.cs
  Lib9c/Action/TransferAsset3.cs
  Lib9c/Action/TransferAssets0.cs
  Lib9c/Action/UnlockEquipmentRecipe1.cs
  Lib9c/Action/UnlockWorld1.cs
  Lib9c/Action/UpdateSell.cs
Labels: Extra Small

#1985 Introduce `UnloadFromMyGaragesRecipientMail`
  .Lib9c.Tests/Action/Garages/DeliverToOthersGaragesTest.cs
  .Lib9c.Tests/Action/Garages/LoadIntoMyGaragesTest.cs
  .Lib9c.Tests/Action/Garages/UnloadFromMyGaragesTest.cs
  .Lib9c.Tests/Model/Mail/UnloadFromMyGaragesRecipientMailTest.cs
  .Lib9c.Tests/Model/State/AvatarStateTest.cs
  Lib9c.Abstractions/IDeliverToOthersGaragesV1.cs
  Lib9c.Abstractions/ILoadIntoMyGaragesV1.cs
  Lib9c.Abstractions/IUnloadFromMyGaragesV1.cs
  Lib9c/Action/Garages/DeliverToOthersGarages.cs
  Lib9c/Action/Garages/GarageUtils.cs
  Lib9c/Action/Garages/LoadIntoMyGarages.cs
  Lib9c/Action/Garages/UnloadFromMyGarages.cs
  Lib9c/Action/HackAndSlash3.cs
  Lib9c/Action/MimisbrunnrBattle0.cs
  Lib9c/Model/Mail/IMail.cs
  Lib9c/Model/Mail/Mail.cs
  Lib9c/Model/Mail/UnloadFromMyGaragesRecipientMail.cs
  Lib9c/Model/State/AvatarState.cs
Labels: Extra Large

#1990 Add CODEOWNERS
  CODEOWNERS
Labels: enhancement, Extra Small
