Repository planetarium/lib9c, pull requests merged in 2023-02, with the labels that each got.

#1686 Introduce PetEnhancement action
  .Lib9c.Tests/Action/PetEnhancement0Test.cs
  .Lib9c.Tests/Helper/PetHelperTest.cs
  .Lib9c.Tests/Model/State/PetStateTest.cs
  .Lib9c.Tests/TableData/Pet/PetCostSheetTest.cs
  .Lib9c.Tests/TableData/Pet/PetOptionSheetTest.cs
  .Lib9c.Tests/TableData/Pet/PetSheetTest.cs
  .Lib9c.Tests/TestUtils.cs
  Lib9c/Action/AddressExtension.cs
  Lib9c/Action/FailedLoadStateException.cs
  Lib9c/Action/NotEnoughFungibleAssetValueException.cs
  Lib9c/Action/PetEnhancement.cs
  Lib9c/Addresses.cs
  Lib9c/Exceptions/InvalidActionFieldException.cs
  Lib9c/Exceptions/PetCostNotFoundException.cs
  Lib9c/Helper/PetHelper.cs
  Lib9c/Model/State/PetState.cs
  Lib9c/TableData/Exceptions.cs
  Lib9c/TableData/Pet/PetOptionSheet.cs
  Lib9c/TableData/Pet/PetSheet.cs
Labels: Extra Large

#1694 Remove check in Miner.cs
  Lib9c.Miner/Miner.cs
Labels: Extra Small

#1575 Update RedeemRewardSheet (for Arena Championship)
  Lib9c/TableCSV/RedeemRewardSheet.csv
Labels: Extra Small

#1697 Extend tx lifetime on tests
  .Lib9c.Tests/StagePolicyTest.cs
Labels: Extra Small

#1698 Add new id for arena grand final rewards
  Lib9c/TableCSV/RedeemRewardSheet.csv
Labels: Extra Small

#1703 Fixed tests failing occasionally due to long running time
  .Lib9c.Tests/StagePolicyTest.cs
Labels: Extra Small

#1706 Implement interfaces missing
  Lib9c.Abstractions/IClaimRaidRewardV1.cs
  Lib9c/Action/BattleArena5.cs
  Lib9c/Action/ClaimRaidReward.cs
Labels: bug, Extra Small

#1712 Craft action scenario tests
  .Lib9c.Tests/Action/PetEnhancement0Test.cs
  .Lib9c.Tests/Action/Scenario/ItemCraftTest.cs
  .Lib9c.Tests/Action/Scenario/RapidCombinationTest.cs
  .Lib9c.Tests/Util/CraftUtil.cs
  .Lib9c.Tests/Util/CsvUtil.cs
  .Lib9c.Tests/Util/InitializeUtil.cs
  .Lib9c.Tests/Util/QuestUtil.cs
  Lib9c/Model/EnumType/CraftType.cs
  Lib9c/Model/Quest/QuestList.cs
  Lib9c/TableData/Item/ConsumableItemRecipeSheet.cs
  Lib9c/TableData/Item/EquipmentItemRecipeSheet.cs
Labels: enhancement, Extra Large

#1714 Compat with mpc for IL2CPP
  Lib9c.DevExtensions/TestbedHelper.cs
  Lib9c.MessagePack/Action/NCActionEvaluation.cs
  Lib9c.MessagePack/Formatters/AddressFormatter.cs
  Lib9c.MessagePack/Formatters/ExceptionFormatter.cs
  Lib9c/Action/GoldDistribution.cs
Labels: Extra Small

#1721 Fix pet data
  .Lib9c.Tests/Action/PetEnhancement0Test.cs
  .Lib9c.Tests/Model/State/PetStateTest.cs
  Lib9c/Action/CreateAvatar.cs
  Lib9c/TableCSV/Pet/PetCostSheet.csv
  Lib9c/TableCSV/Pet/PetOptionSheet.csv
  Lib9c/TableCSV/Pet/PetSheet.csv
Labels: Extra Large

#1723 handle FailedLoadStateException at test create avatar
  Lib9c/Action/CreateAvatar.cs
Labels: Extra Small

#1724 Update pet id on `ItemEnhancement`
  Lib9c/Action/ItemEnhancement.cs
Labels: Extra Small

#1725 Check custom actions deserialization
  Lib9c.Miner.Tests/CustomActionsDeserializableValidatorTest.cs
  Lib9c.Miner.Tests/Lib9c.Miner.Tests.csproj
  Lib9c.Miner.Tests/Usings.cs
  Lib9c.Miner/ActionTypeLoaderContext.cs
  Lib9c.Miner/CustomActionsDeserializableValidator.cs
  Lib9c.Miner/Miner.cs
  Lib9c.sln
Labels: bug, Medium

#1727 Rename `Lib9c.Miner.Tests` -> `.Lib9c.Miner.Tests`
  .Lib9c.Miner.Tests/CustomActionsDeserializableValidatorTest.cs
  .Lib9c.Miner.Tests/Lib9c.Miner.Tests.csproj
  .Lib9c.Miner.Tests/Usings.cs
  Lib9c.sln
Labels: bug, No Changes

#1728 Ignore invalid txs
  Lib9c.Miner/Miner.cs
Labels: bug, Extra Small

#1716 Scenario tests for pets
  .Lib9c.Tests/Action/Scenario/Pet/AdditionalOptionRateByFixedValueTest.cs
  .Lib9c.Tests/Action/Scenario/Pet/CommonTest.cs
  .Lib9c.Tests/Action/Scenario/Pet/DiscountMaterialCostCrystalTest.cs
  .Lib9c.Tests/Action/Scenario/Pet/IncreaseBlockPerHourglassTest.cs
  .Lib9c.Tests/Action/Scenario/Pet/ReduceRequiredBlockTest.cs
  .Lib9c.Tests/Util/CraftUtil.cs
  .Lib9c.Tests/Util/CurrencyUtil.cs
Labels: enhancement, Extra Large

#1732 feat: Introduce test utils
  .Lib9c.Tests/Util/CraftUtil.cs
  .Lib9c.Tests/Util/CsvUtil.cs
  .Lib9c.Tests/Util/CurrencyUtil.cs
  .Lib9c.Tests/Util/InitializeUtil.cs
  .Lib9c.Tests/Util/QuestUtil.cs
  Lib9c/Addresses.cs
Labels: Medium

#1735 Support zero crystal fee on `Raid`.
  .Lib9c.Tests/Action/Raid4Test.cs
  Lib9c/Action/Raid.cs
Labels: Small

#1733 Introduce market models & register action
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/ExceptionTest.cs
  .Lib9c.Tests/Action/RegisterProductTest.cs
  Lib9c/Action/AssetInfo.cs
  Lib9c/Action/IRegisterInfo.cs
  Lib9c/Action/InvalidCurrencyException.cs
  Lib9c/Action/InvalidProductTypeException.cs
  Lib9c/Action/ProductInfo.cs
  Lib9c/Action/RegisterInfo.cs
  Lib9c/Action/RegisterProduct.cs
  Lib9c/Addresses.cs
  Lib9c/Model/Market/FavProduct.cs
  Lib9c/Model/Market/ItemProduct.cs
  Lib9c/Model/Market/Product.cs
  Lib9c/Model/Market/ProductFactory.cs
  Lib9c/Model/Market/ProductReceipt.cs
  Lib9c/Model/Market/ProductType.cs
  Lib9c/Model/Market/ProductsState.cs
  Lib9c/Model/State/MarketState.cs
Labels: Extra Large

#1738 Sync class name and filename
  Lib9c.Policy/Policy/MaxTransactionsBytesPolicy.cs
Labels: No Changes

#1743 Disable global usings to support Unity
  Lib9c.Policy/Lib9c.Policy.csproj
  Lib9c.Renderers/ActionEvaluation.cs
  Lib9c.Renderers/Lib9c.Renderers.csproj
  Lib9c.Utils/Lib9c.Utils.csproj
Labels: bug, Extra Small

#1740 Introduce BuyProduct action
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/BuyProductTest.cs
  .Lib9c.Tests/Action/ExceptionTest.cs
  Lib9c/Action/BuyProduct.cs
  Lib9c/Action/ProductNotFoundException.cs
  Lib9c/Action/RegisterProduct.cs
  Lib9c/Model/Mail/IMail.cs
  Lib9c/Model/Mail/Mail.cs
  Lib9c/Model/Mail/ProductBuyerMail.cs
  Lib9c/Model/Mail/ProductSellerMail.cs
Labels: Extra Large

#1720 Introduce SecureMiningReward action
  .Lib9c.Tests/Action/SecureMiningRewardTest.cs
  Lib9c.Abstractions/ISecureMiningReward.cs
  Lib9c/Action/SecureMiningReward.cs
Labels: Medium

#1745 🔧 Fixed index used for policy
  Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
  Lib9c.Policy/Policy/BlockPolicySource.cs
  Lib9c/Action/ActionObsoleteAttribute.cs
Labels: bug, Extra Small

#1742 Introduce re-register product
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/ReRegisterProductTest.cs
  .Lib9c.Tests/Action/Scenario/MarketScenarioTest.cs
  Lib9c/Action/ReRegisterProduct.cs
  Lib9c/Action/UpdateSell.cs
Labels: Extra Large

#1718 Introduce transfer crystal white listing
  .Lib9c.Tests/Action/ExceptionTest.cs
  .Lib9c.Tests/Action/TransferAssetTest.cs
  .Lib9c.Tests/Action/TransferAssetsTest.cs
  Lib9c/Action/InvalidTransferCurrencyException.cs
  Lib9c/Action/TransferAsset.cs
  Lib9c/Action/TransferAssets.cs
Labels: Small

#1750 fix: build errors
  Lib9c.sln
Labels: No Changes

#1752 fix: `IReadOnlySet<T>` to `IReadOnlyList<T>` for Unity
  Lib9c/Action/TransferAsset.cs
Labels: Extra Small

#1755 Update Pet date Draft
  Lib9c/TableCSV/Pet/PetCostSheet.csv
  Lib9c/TableCSV/Pet/PetOptionSheet.csv
  Lib9c/TableCSV/Pet/PetSheet.csv
Labels: Extra Large

#1756 prepare avatar state for previewnet
  .Lib9c.Tests/Action/CreateAvatarTest.cs
  .Lib9c.Tests/Action/Scenario/Pet/AdditionalOptionRateByFixedValueTest.cs
  .Lib9c.Tests/Action/Scenario/Pet/CommonTest.cs
  .Lib9c.Tests/Policy/BlockPolicyTest.cs
  Lib9c.Utils/BlockHelper.cs
  Lib9c/Action/CreateAvatar.cs
Labels: Medium

#1759 Arena & Worldboss Schedule Change
  Lib9c/TableCSV/Arena/ArenaSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
Labels: Small
