Repository planetarium/lib9c, pull requests merged in 2024-01, with the labels that each got.

#2317 handle-acs-timeout
  Lib9c.Policy/NCStagePolicy.cs
Labels: Extra Small

#2318 Validate ticket count
  .Lib9c.Tests/Action/BattleArenaTest.cs
  Lib9c/Action/BattleArena.cs
Labels: Extra Small

#2319 main merge release/1.7.1
  .Lib9c.Tests/Action/BattleArenaTest.cs
  Lib9c.Policy/NCStagePolicy.cs
  Lib9c/Action/BattleArena.cs
Labels: Small

#2321 development merge main 1.7.1
  .Lib9c.Tests/Action/BattleArenaTest.cs
  Lib9c.Policy/NCStagePolicy.cs
  Lib9c/Action/BattleArena.cs
Labels: Small

#2257 add unity meta files
  Lib9c/TableCSV/StakeRegularFixedRewardSheet_V1.csv.meta
  Lib9c/TableCSV/StakeRegularFixedRewardSheet_V2.csv.meta
  Lib9c/TableCSV/StakeRegularRewardSheet_V1.csv.meta
  Lib9c/TableCSV/StakeRegularRewardSheet_V2.csv.meta
  Lib9c/TableCSV/StakeRegularRewardSheet_V3.csv.meta
  Lib9c/TableCSV/StakeRegularRewardSheet_V4.csv.meta
  Lib9c/TableCSV/StakeRegularRewardSheet_V5.csv.meta
Labels: Extra Small

#2322 Add devforum badge to README
  README.md
Labels: documentation, Extra Small

#2328 Extract StakeRewardCalculator to check rewards outside of action
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/Model/State/StakeRewardCalculator.cs
Labels: Medium

#2332 Support decimal rates of 3 or more digits
  Lib9c/Model/State/StakeRewardCalculator.cs
Labels: bug, Extra Small

#2333 Fix clone method to deep copy
  .Lib9c.Tests/Model/State/AvatarStateTest.cs
  Lib9c/Model/Item/Inventory.cs
  Lib9c/Model/Quest/QuestList.cs
  Lib9c/Model/State/AgentState.cs
  Lib9c/Model/State/AvatarState.cs
  Lib9c/Model/WorldInformation.cs
Labels: Extra Small

#2340 exception handling in stagepolicy iteration
  Lib9c.Policy/NCStagePolicy.cs
Labels: Extra Small

#2346 Remove unused codes related to MonsterCollection
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/ClaimMonsterCollectionReward0Test.cs
  .Lib9c.Tests/Action/ClaimMonsterCollectionReward2Test.cs
  .Lib9c.Tests/Action/ClaimMonsterCollectionRewardTest.cs
  .Lib9c.Tests/Action/MonsterCollect0Test.cs
  .Lib9c.Tests/Action/MonsterCollect2Test.cs
  .Lib9c.Tests/Action/MonsterCollectTest.cs
  Lib9c/Action/ClaimMonsterCollectionReward.cs
  Lib9c/Action/ClaimMonsterCollectionReward0.cs
  Lib9c/Action/ClaimMonsterCollectionReward2.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Action/MonsterCollect.cs
  Lib9c/Action/MonsterCollect0.cs
  Lib9c/Action/MonsterCollect2.cs
Labels: Extra Large

#2347 stake reward allow non-tradable
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Fixtures/TableCSV/Stake/StakePolicySheetFixtures.cs
  .Lib9c.Tests/Fixtures/TableCSV/Stake/StakeRegularFixedRewardSheetFixtures.cs
  .Lib9c.Tests/Fixtures/TableCSV/Stake/StakeRegularRewardSheetFixtures.cs
  .Lib9c.Tests/TableData/StakeRegularRewardSheetTest.cs
  Lib9c/Action/ClaimStakeReward.cs
  Lib9c/TableCSV/Stake/StakePolicySheet.csv
  Lib9c/TableCSV/StakeRegularFixedRewardSheet_V3.csv
  Lib9c/TableCSV/StakeRegularRewardSheet_V6.csv
  Lib9c/TableData/StakeRegularRewardSheet.cs
Labels: Large

#2351 Allow material in garages
  .Lib9c.Tests/Action/Garages/DeliverToOthersGaragesTest.cs
  .Lib9c.Tests/Action/Garages/LoadIntoMyGaragesTest.cs
  Lib9c/Action/Garages/LoadIntoMyGarages.cs
  Lib9c/TableCSV/Garages/LoadIntoMyGaragesCostSheet.csv
Labels: Medium, hardfork

#2357 🧹 Reduced warnings
  .Lib9c.DevExtensions.Tests/Action/ManipulateStateTest.cs
Labels: Extra Small

#2358 🔀 [Libplanet 4.0] Merge 1.7.0 tag into libplanet 4.0
  .Lib9c.Tests/Action/Factory/ClaimStakeRewardFactoryTest.cs
  .Lib9c.Tests/Lib9c.Tests.csproj
  Lib9c/Action/ClaimStakeReward2.cs
  Lib9c/Action/ClaimStakeReward8.cs
  Lib9c/Action/Factory/ClaimStakeRewardFactory.cs
  Lib9c/Action/TransferAsset3.cs
Labels: Large

#2361 🔀 [Libplanet 4.0] Merge 1.7.1 into libplanet 4.0
  .Lib9c.Tests/Action/BattleArenaTest.cs
  Lib9c.Policy/NCStagePolicy.cs
  Lib9c/Action/BattleArena.cs
Labels: Small
