Repository planetarium/lib9c, pull requests merged in 2024-08, with the labels that each got.

#2724 Update custom craft logic
  .Lib9c.Tests/Action/CustomEquipmentCraft/CustomEquipmentCraftTest.cs
  Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
  Lib9c/Action/Exceptions/DuplicatedCraftSlotIndexException.cs
  Lib9c/Helper/CustomCraftHelper.cs
  Lib9c/Model/Item/ItemBase.cs
  Lib9c/Model/Item/ItemFactory.cs
  Lib9c/Model/Item/ItemType.cs
  Lib9c/Model/Skill/SkillFactory.cs
  Lib9c/Model/State/GameConfigState.cs
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftIconSheet.csv
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftRelationshipSheet.csv
  Lib9c/TableCSV/GameConfigSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
  Lib9c/TableData/CustomEquipmentCraft/CustomEquipmentCraftRelationshipSheet.cs
Labels: enhancement

#2733 Adjust planetarium guild owner address
  .Lib9c.Tests/Action/Guild/MakeGuildTest.cs
  .Lib9c.Tests/Action/Guild/Migration/GuildMigrationCtrlTest.cs
  .Lib9c.Tests/Action/Guild/Migration/MigratePledgeToGuildTest.cs
  .Lib9c.Tests/PolicyAction/Tx/Begin/AutoJoinGuildTest.cs
  Lib9c/Action/Guild/GuildConfig.cs
  Lib9c/Action/Guild/MakeGuild.cs
  Lib9c/Action/Guild/Migration/Controls/GuildMigrationCtrl.cs
  Lib9c/Action/Guild/Migration/MigratePledgeToGuild.cs
Labels: bug

#2734 Some works
  .Lib9c.Benchmarks/.gitignore
  .Lib9c.Benchmarks/Actions/AutoJoinGuild.cs
  .Lib9c.Benchmarks/Actions/MigratePledgeToGuild.cs
  .Lib9c.Benchmarks/Actions/TransferAsset.cs
  .Lib9c.Benchmarks/Lib9c.Benchmarks.csproj
  .Lib9c.Benchmarks/Program.cs
  .Lib9c.Plugin/PluginActionEvaluator.cs
  .Lib9c.Tests/Action/Guild/Migration/GuildMigrationCtrlTest.cs
  .Lib9c.Tests/Action/Guild/Migration/MigratePledgeToGuildTest.cs
  @planetarium/lib9c/src/actions/approve_pledge.ts
  @planetarium/lib9c/src/actions/make_guild.ts
  @planetarium/lib9c/src/actions/migrate_pledge_to_guild.ts
  @planetarium/lib9c/src/index.ts
  @planetarium/lib9c/tests/actions/approve_pledge.test.ts
  @planetarium/lib9c/tests/actions/fixtures.ts
  @planetarium/lib9c/tests/actions/make_guild.test.ts
  @planetarium/lib9c/tests/actions/migrate_pledge_to_guild.test.ts
  Lib9c.Policy/Policy/BlockPolicySource.cs
  Lib9c/Action/Guild/Migration/Controls/GuildMigrationCtrl.cs
Labels: bug, js

#2759 Introduce new mail type: CustomCraft
  .Lib9c.Tests/Model/Mail/CustomCraftMailTest.cs
  Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
  Lib9c/Model/Mail/CustomCraftMail.cs
  Lib9c/Model/Mail/IMail.cs
  Lib9c/Model/Mail/Mail.cs
Labels: enhancement

#2769 Extend Tx size limit from 500K to 1M
  Lib9c.Policy/Policy/MaxTransactionsBytesPolicy.cs
Labels: bug

#2771 Apply heimdall internal snapshot reset
  Lib9c.Policy/Policy/MaxTransactionsBytesPolicy.cs
Labels: bug

#2784 Change block index to apply new policy
  Lib9c.Policy/Policy/MaxTransactionsBytesPolicy.cs
Labels: bug

#2788 Update names
  .Lib9c.Tests/Action/CustomEquipmentCraft/CustomEquipmentCraftTest.cs
  .Lib9c.Tests/TableData/CustomEquipmentCraft/CustomEquipmentCraftRecipeSheetTest.cs
  Lib9c/Helper/CustomCraftHelper.cs
  Lib9c/Model/Item/ItemType.cs
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftRecipeSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
  Lib9c/TableData/CustomEquipmentCraft/CustomEquipmentCraftRecipeSheet.cs
Labels: enhancement

#2792 Set version to 1.17.2
  Lib9c.Abstractions/Lib9c.Abstractions.csproj
  Lib9c.MessagePack/Lib9c.MessagePack.csproj
  Lib9c.Renderers/Lib9c.Renderers.csproj
  Lib9c/Lib9c.csproj
Labels: bug

#2795 Fix with code formatting
  .Lib9c.Tests/Action/HackAndSlashSweepTest.cs
  Lib9c/Action/HackAndSlashSweep.cs
Labels: bug

#2796 Release 1.17.3
  .Lib9c.Tests/Action/HackAndSlashSweepTest.cs
  Lib9c/Action/HackAndSlashSweep.cs
Labels: bug
