Repository planetarium/lib9c, pull requests merged in 2024-09, with the labels that each got.

#2811 Add new fields into Equipment model
  .Lib9c.Tests/Action/CustomEquipmentCraft/CustomEquipmentCraftTest.cs
  Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
  Lib9c/Model/Item/Equipment.cs
  Lib9c/Model/Item/ItemFactory.cs
  Lib9c/SerializeKeys.cs
Labels: enhancement

#2805 Select adventure boss avoiding latest 2 seasons
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  .Lib9c.Tests/Action/AdventureBoss/WantedTest.cs
  Lib9c/Action/AdventureBoss/Wanted.cs
Labels: enhancement

#2817 Update docs
  CONTRIBUTING.md
  README.md
Labels: documentation

#2818 Exclude BTAI from docs
  docs/docfx.json
  docs/filter.yml
Labels: documentation

#2814 Prevent usage of unimplemented serialization method
  .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
  .Lib9c.Tests/Action/Stake0Test.cs
  .Lib9c.Tests/Action/Stake2Test.cs
  .Lib9c.Tests/Action/StakeTest.cs
  .Lib9c.Tests/Model/State/LazyStateTest.cs
  Lib9c/Model/State/ActivatedAccountsState.cs
  Lib9c/Model/State/AdminState.cs
  Lib9c/Model/State/AgentState.cs
  Lib9c/Model/State/AuthorizedMinersState.cs
  Lib9c/Model/State/AvatarState.cs
  Lib9c/Model/State/CombinationSlotState.cs
  Lib9c/Model/State/CreditsState.cs
  Lib9c/Model/State/GameConfigState.cs
  Lib9c/Model/State/GoldBalanceState.cs
  Lib9c/Model/State/GoldCurrencyState.cs
  Lib9c/Model/State/MonsterCollectionState.cs
  Lib9c/Model/State/MonsterCollectionState0.cs
  Lib9c/Model/State/PendingActivationState.cs
  Lib9c/Model/State/RankingMapState.cs
  Lib9c/Model/State/RankingState.cs
  Lib9c/Model/State/RankingState0.cs
  Lib9c/Model/State/RankingState1.cs
  Lib9c/Model/State/RedeemCodeState.cs
  Lib9c/Model/State/ShardedShopState.cs
  Lib9c/Model/State/ShardedShopStateV2.cs
  Lib9c/Model/State/ShopState.cs
  Lib9c/Model/State/StakeState.cs
  Lib9c/Model/State/State.cs
  Lib9c/Model/State/WeeklyArenaState.cs
Labels: bug, refactoring

#2828 Change additional cost in custom craft
  .Lib9c.Tests/Action/CustomEquipmentCraft/CustomEquipmentCraftTest.cs
  .Lib9c.Tests/TableData/CustomEquipmentCraft/CustomEquipmentCraftCostSheetTest.cs
  .Lib9c.Tests/TableData/CustomEquipmentCraft/CustomEquipmentCraftRelationshipSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
  Lib9c/Helper/CustomCraftHelper.cs
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftCostSheet.csv
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftCostSheet.csv.meta
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftRelationshipSheet.csv
  Lib9c/TableData/CustomEquipmentCraft/CustomEquipmentCraftCostSheet.cs
  Lib9c/TableData/CustomEquipmentCraft/CustomEquipmentCraftRelationshipSheet.cs
Labels: enhancement

#2832 docs: move articles from devportal
  docs/README.md
  docs/articles/currencies/mead.md
  docs/articles/currencies/toc.yml
  docs/articles/system/adventure.md
  docs/articles/system/agent.md
  docs/articles/system/arena.md
  docs/articles/system/avatar/avatar.md
  docs/articles/system/avatar/inventory.md
  docs/articles/system/avatar/quest-list.md
  docs/articles/system/avatar/toc.yml
  docs/articles/system/avatar/world-information.md
  docs/articles/system/toc.yml
  docs/articles/toc.yml
Labels: documentation

#2833 Update README
  README.md
Labels: documentation

#2685 Remove unused actions
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/ActivateAccountTest.cs
  .Lib9c.Tests/Action/AddActivatedAccountTest.cs
  .Lib9c.Tests/Action/Snapshot/TransferAsset0SnapshotTest.cs
  .Lib9c.Tests/Action/Snapshot/transfer_asset.PlainValue.verified.txt
  .Lib9c.Tests/Action/Snapshot/transfer_asset.TransferCrystal.diff.verified.txt
  .Lib9c.Tests/Action/Snapshot/transfer_asset.TransferWithMemo.diff.verified.txt
  .Lib9c.Tests/Action/Stake0Test.cs
  .Lib9c.Tests/Policy/BlockPolicySourceTest.cs
  .Lib9c.Tests/Policy/BlockPolicyTest.cs
  Lib9c/Action/ActivateAccount.cs
  Lib9c/Action/AddActivatedAccount.cs
  Lib9c/Action/Stake0.cs
  Lib9c/Action/TransferAsset0.cs
  Lib9c/Model/ActivationKey.cs
  Lib9c/Model/State/PendingActivationState.cs
Labels: refactoring

#2838 Introduce `IWorld.RemoveLegacyState` extension method
  Lib9c/Action/Stake.cs
  Lib9c/Module/LegacyModule.cs
Labels: refactoring

#2850 Update CP selecting logic
  .Lib9c.Tests/Action/CustomEquipmentCraft/CustomEquipmentCraftTest.cs
  .Lib9c.Tests/TableData/CustomEquipmentCraft/CustomEquipmentCraftRelationshipSheetTest.cs
  Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
  Lib9c/Helper/CustomCraftHelper.cs
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftRelationshipSheet.csv
  Lib9c/TableData/CustomEquipmentCraft/CustomEquipmentCraftRelationshipSheet.cs
Labels: enhancement

#2856 Ignore empty data with throwing exception for missing data
  Lib9c/TableData/AdventureBoss/AdventureBossFloorFirstRewardSheet.cs
Labels: bug
