Repository planetarium/lib9c, pull requests merged in 2024-06, with the labels that each got.

#2601 Document @planetarium/lib9c with vitepress
  @planetarium/lib9c/docs/.gitignore
  @planetarium/lib9c/docs/.vitepress/config.ts
  @planetarium/lib9c/docs/docs/actions.md
  @planetarium/lib9c/docs/docs/index.md
  @planetarium/lib9c/docs/docs/utility.md
  @planetarium/lib9c/docs/index.md
  @planetarium/lib9c/docs/ko/docs/actions.md
  @planetarium/lib9c/docs/ko/docs/index.md
  @planetarium/lib9c/docs/ko/docs/utility.md
  @planetarium/lib9c/docs/ko/index.md
  @planetarium/lib9c/package.json
  @planetarium/pnpm-lock.yaml
Labels: documentation, js

#2603 Document lib9c
  @planetarium/lib9c/docs/.vitepress/config.ts
  @planetarium/lib9c/docs/docs/utility.md
Labels: bug, documentation

#2604 Fix `@planetarium/lib9c` document
  @planetarium/lib9c/docs/.vitepress/config.ts
  @planetarium/lib9c/docs/docs/actions.md
  @planetarium/lib9c/docs/docs/installation.md
  @planetarium/lib9c/docs/docs/utility.md
  @planetarium/lib9c/docs/ko/docs/actions.md
  @planetarium/lib9c/docs/ko/docs/installation.md
  @planetarium/lib9c/docs/ko/docs/utility.md
Labels: bug, documentation, js

#2606 Update raffle reward calculation logic
  .Lib9c.Tests/Helper/AdventureBossHelperTest.cs
  Lib9c/Helper/AdventureBossHelper.cs
Labels: bug

#2602 Add names
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  .Lib9c.Tests/Action/AdventureBoss/ExploreAdventureBossTest.cs
  .Lib9c.Tests/Action/AdventureBoss/SweepAdventureBossTest.cs
  .Lib9c.Tests/Helper/AdventureBossHelperTest.cs
  Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
  Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
  Lib9c/Helper/AdventureBossHelper.cs
  Lib9c/Model/AdventureBoss/BountyBoard.cs
  Lib9c/Model/AdventureBoss/ExploreBoard.cs
  Lib9c/Model/AdventureBoss/Explorer.cs
  Lib9c/Model/AdventureBoss/Investor.cs
Labels: bug

#2610 Correct i18n nav
  @planetarium/lib9c/docs/.vitepress/config.ts
  @planetarium/lib9c/docs/ko/index.md
Labels: bug, documentation

#2611 Introduce AdventureBossSimulator
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  .Lib9c.Tests/Action/AdventureBoss/ExploreAdventureBossTest.cs
  .Lib9c.Tests/Action/AdventureBoss/UnlockFloorTest.cs
  .Lib9c.Tests/Lib9c.Tests.csproj
  .Lib9c.Tests/Model/AdventureBoss/AdventureBossSimulatorTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
  Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
  Lib9c/Battle/AdventureBoss/AdventureBossSimulator.cs
  Lib9c/Model/BattleStatus/AdventureBoss/Breakthrough.cs
  Lib9c/Model/IStage.cs
  Lib9c/TableCSV/AdventureBoss/FloorSheet.csv
  Lib9c/TableCSV/AdventureBoss/FloorWaveSheet.csv
  Lib9c/TableData/AdventureBoss/FloorSheet.cs
  Lib9c/TableData/AdventureBoss/FloorWaveSheet.cs
Labels: enhancement

#2618 Update simulator and test
  .Lib9c.Tests/Model/AdventureBoss/AdventureBossSimulatorTest.cs
  Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
Labels: bug

#2619 Remove wanted raffle
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  .Lib9c.Tests/Helper/AdventureBossHelperTest.cs
  Lib9c/Helper/AdventureBossHelper.cs
  Lib9c/Model/AdventureBoss/BountyBoard.cs
  Lib9c/Module/AdventureBossModule.cs
Labels: enhancement

#2625 Introduce StageBuff to AdventureBoss
  .Lib9c.Tests/Action/AdventureBoss/ExploreAdventureBossTest.cs
  .Lib9c.Tests/Model/AdventureBoss/AdventureBossSimulatorTest.cs
  Lib9c/Battle/AdventureBoss/AdventureBossSimulator.cs
  Lib9c/Model/BattleStatus/AdventureBoss/Breakthrough.cs
  Lib9c/Model/BattleStatus/AdventureBoss/StageBuff.cs
  Lib9c/Model/IStage.cs
  Lib9c/TableCSV/AdventureBoss/AdventureBossSheet.csv
  Lib9c/TableCSV/AdventureBoss/FloorSheet.csv
  Lib9c/TableCSV/AdventureBoss/FloorWaveSheet.csv
  Lib9c/TableCSV/Character/CharacterSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableData/AdventureBoss/FloorSheet.cs
Labels: enhancement

#2627 Move data to CSV
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  .Lib9c.Tests/Action/AdventureBoss/ExploreAdventureBossTest.cs
  .Lib9c.Tests/Action/AdventureBoss/SweepAdventureBossTest.cs
  .Lib9c.Tests/Action/AdventureBoss/UnlockFloorTest.cs
  .Lib9c.Tests/Action/AdventureBoss/WantedTest.cs
  .Lib9c.Tests/Helper/AdventureBossHelperTest.cs
  .Lib9c.Tests/Model/AdventureBoss/AdventureBossSimulatorTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
  Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
  Lib9c/Action/AdventureBoss/Wanted.cs
  Lib9c/Battle/AdventureBoss/AdventureBossSimulator.cs
  Lib9c/Data/AdventureBossGameData.cs
  Lib9c/Helper/AdventureBossHelper.cs
  Lib9c/Model/AdventureBoss/BountyBoard.cs
  Lib9c/Model/AdventureBoss/ExploreBoard.cs
  Lib9c/Model/BattleStatus/AdventureBoss/Breakthrough.cs
  Lib9c/Model/IStage.cs
  Lib9c/TableCSV/AdventureBoss/AdventureBossContributionRewardSheet.csv
  Lib9c/TableCSV/AdventureBoss/AdventureBossFloorFirstRewardSheet.csv
  Lib9c/TableCSV/AdventureBoss/AdventureBossFloorPointSheet.csv
  Lib9c/TableCSV/AdventureBoss/AdventureBossFloorSheet.csv
  Lib9c/TableCSV/AdventureBoss/AdventureBossFloorWaveSheet.csv
  Lib9c/TableCSV/AdventureBoss/AdventureBossNcgRewardRatioSheet.csv
  Lib9c/TableCSV/AdventureBoss/AdventureBossSheet.csv
  Lib9c/TableCSV/AdventureBoss/AdventureBossWantedRewardSheet.csv
  Lib9c/TableCSV/AdventureBoss/FloorSheet.csv
  Lib9c/TableCSV/Character/CharacterSheet.csv
  Lib9c/TableCSV/GameConfigSheet.csv
  Lib9c/TableData/AdventureBoss/AdventureBossContributionRewardSheet.cs
  Lib9c/TableData/AdventureBoss/AdventureBossFloorFirstRewardSheet.cs
  Lib9c/TableData/AdventureBoss/AdventureBossFloorPointSheet.cs
  Lib9c/TableData/AdventureBoss/AdventureBossFloorSheet.cs
  Lib9c/TableData/AdventureBoss/AdventureBossFloorWaveSheet.cs
  Lib9c/TableData/AdventureBoss/AdventureBossNcgRewardRatioSheet.cs
  Lib9c/TableData/AdventureBoss/AdventureBossSheet.cs
  Lib9c/TableData/AdventureBoss/AdventureBossWantedRewardSheet.cs
Labels: enhancement

#2632 Update CSV Data
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  .Lib9c.Tests/Action/AdventureBoss/ExploreAdventureBossTest.cs
  .Lib9c.Tests/Action/AdventureBoss/SweepAdventureBossTest.cs
  .Lib9c.Tests/Action/AdventureBoss/UnlockFloorTest.cs
  .Lib9c.Tests/Action/AdventureBoss/WantedTest.cs
  .Lib9c.Tests/Helper/AdventureBossHelperTest.cs
  .Lib9c.Tests/Lib9c.Tests.csproj
  .Lib9c.Tests/TableData/AdventureBoss/AdventureBossContributionRewardSheetTest.cs
  .Lib9c.Tests/TableData/AdventureBoss/AdventureBossWantedRewardSheetTest.cs
  Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
  Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
  Lib9c/Action/AdventureBoss/UnlockFloor.cs
  Lib9c/Action/AdventureBoss/Wanted.cs
  Lib9c/Data/AdventureBossGameData.cs
  Lib9c/Helper/AdventureBossHelper.cs
  Lib9c/Model/AdventureBoss/BountyBoard.cs
  Lib9c/Model/AdventureBoss/SeasonInfo.cs
  Lib9c/Model/State/GameConfigState.cs
  Lib9c/TableCSV/AdventureBoss/AdventureBossContributionRewardSheet.csv
  Lib9c/TableCSV/AdventureBoss/AdventureBossUnlockFloorCostSheet.csv
  Lib9c/TableCSV/AdventureBoss/AdventureBossWantedRewardSheet.csv
  Lib9c/TableCSV/GameConfigSheet.csv
  Lib9c/TableData/AdventureBoss/AdventureBossContributionRewardSheet.cs
  Lib9c/TableData/AdventureBoss/AdventureBossUnlockFloorCostSheet.cs
  Lib9c/TableData/AdventureBoss/AdventureBossWantedRewardSheet.cs
Labels: enhancement

#2633 Move AP potion amount from action to CSV
  .Lib9c.Tests/Action/AdventureBoss/SweepAdventureBossTest.cs
  Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
  Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
  Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
  Lib9c/Helper/AdventureBossHelper.cs
  Lib9c/TableCSV/AdventureBoss/AdventureBossSheet.csv
  Lib9c/TableData/AdventureBoss/AdventureBossSheet.cs
Labels: bug

#2634 Introduce ExplorerList model
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  .Lib9c.Tests/Helper/AdventureBossHelperTest.cs
  Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
  Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
  Lib9c/Action/AdventureBoss/Wanted.cs
  Lib9c/Addresses.cs
  Lib9c/Helper/AdventureBossHelper.cs
  Lib9c/Model/AdventureBoss/ExploreBoard.cs
  Lib9c/Model/AdventureBoss/ExplorerList.cs
  Lib9c/Module/AdventureBossModule.cs
Labels: enhancement

#2636 Move wanted min. bounty from action to CSV
  .Lib9c.Tests/Action/AdventureBoss/ExploreAdventureBossTest.cs
  .Lib9c.Tests/Action/AdventureBoss/SweepAdventureBossTest.cs
  .Lib9c.Tests/Action/AdventureBoss/UnlockFloorTest.cs
  .Lib9c.Tests/Action/AdventureBoss/WantedTest.cs
  Lib9c/Action/AdventureBoss/Wanted.cs
  Lib9c/Model/State/GameConfigState.cs
  Lib9c/TableCSV/GameConfigSheet.csv
Labels: enhancement

#2638 Check staking required level from latest staking policy
  .Lib9c.Tests/Action/AdventureBoss/WantedTest.cs
  Lib9c/Action/AdventureBoss/Wanted.cs
Labels: bug

#2639 Calculate contribution reward based on point, not used AP potion
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  .Lib9c.Tests/Helper/AdventureBossHelperTest.cs
  Lib9c/Helper/AdventureBossHelper.cs
Labels: bug

#2643 Operator can put bounty for multiple season in a row
  .Lib9c.Tests/Action/AdventureBoss/WantedTest.cs
  Lib9c/Action/AdventureBoss/Wanted.cs
Labels: enhancement

#2641 Apply code reviews and improve performances
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  .Lib9c.Tests/Action/AdventureBoss/ExploreAdventureBossTest.cs
  .Lib9c.Tests/Action/AdventureBoss/WantedTest.cs
  Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
  Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
  Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
  Lib9c/Action/AdventureBoss/UnlockFloor.cs
  Lib9c/Helper/AdventureBossHelper.cs
Labels: bug, enhancement

#2642 Move all adventure actions to inherit GameAction
  Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
  Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
  Lib9c/Action/AdventureBoss/UnlockFloor.cs
  Lib9c/Action/AdventureBoss/Wanted.cs
  Lib9c/Action/Exceptions/AdventureBoss/AlreadyClaimedException.cs
  Lib9c/Action/Exceptions/AdventureBoss/ClaimExpiredException.cs
  Lib9c/Action/Exceptions/AdventureBoss/InsufficientStakingException.cs
  Lib9c/Action/Exceptions/AdventureBoss/InvalidAdventureBossSeasonException.cs
  Lib9c/Action/Exceptions/AdventureBoss/InvalidBountyException.cs
  Lib9c/Action/Exceptions/AdventureBoss/MaxInvestmentCountExceededException.cs
  Lib9c/Action/Exceptions/AdventureBoss/PreviousBountyException.cs
  Lib9c/Action/Exceptions/AdventureBoss/SeasonInProgressException.cs
Labels: bug

#2644 Extend summon recipe limit to 100
  .Lib9c.Tests/TableData/Summon/SummonSheetTest.cs
  Lib9c/TableData/Summon/SummonSheet.cs
Labels: enhancement

#2645 Use FloorId to get floor related data
  .Lib9c.Tests/Model/AdventureBoss/AdventureBossSimulatorTest.cs
  Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
  Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
  Lib9c/Battle/AdventureBoss/AdventureBossSimulator.cs
Labels: bug

#2647 Bugfix/adv boss/season address form hex
  .Lib9c.Tests/Helper/AdventureBossHelperTest.cs
  Lib9c/Helper/AdventureBossHelper.cs
Labels: bug

#2652 Use floorId to add breakthrough event
  .Lib9c.Tests/Model/AdventureBoss/AdventureBossSimulatorTest.cs
  Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
  Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
  Lib9c/Battle/AdventureBoss/AdventureBossSimulator.cs
  Lib9c/Model/BattleStatus/AdventureBoss/Breakthrough.cs
  Lib9c/Model/IStage.cs
Labels: bug

#2656 Fix floor order
  Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
  Lib9c/Battle/AdventureBoss/AdventureBossSimulator.cs
Labels: bug

#2651 Optimize ClaimAdventureBossReward action
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
  Lib9c/Action/Exceptions/EmptyRewardException.cs
  Lib9c/Data/AdventureBossGameData.cs
  Lib9c/Helper/AdventureBossHelper.cs
Labels: enhancement

#2648 Treat season as decimal to make address form
  .Lib9c.Tests/Helper/AdventureBossHelperTest.cs
  Lib9c/Helper/AdventureBossHelper.cs
Labels: bug
