Repository planetarium/lib9c, pull requests merged in 2024-05, with the labels that each got.

#2555 Introduce `@planetarium/lib9c`
  .Lib9c.Tools/SubCommand/Action.cs
  .github/workflows/main.yml
  .github/workflows/publish.yml
  @planetarium/.editorconfig
  @planetarium/.gitignore
  @planetarium/lib9c/CONTRIBUTING.md
  @planetarium/lib9c/LICENSE
  @planetarium/lib9c/README.md
  @planetarium/lib9c/biome.json
  @planetarium/lib9c/cli/main.ts
  @planetarium/lib9c/jsr.json
  @planetarium/lib9c/package.json
  @planetarium/lib9c/src/actions/claim_items.ts
  @planetarium/lib9c/src/actions/claim_stake_reward.ts
  @planetarium/lib9c/src/actions/common.ts
  @planetarium/lib9c/src/actions/deliver_to_others_garages.ts
  @planetarium/lib9c/src/actions/load_into_my_garages.ts
  @planetarium/lib9c/src/actions/stake.ts
  @planetarium/lib9c/src/actions/transfer_asset.ts
  @planetarium/lib9c/src/actions/transfer_assets.ts
  @planetarium/lib9c/src/index.ts
  @planetarium/lib9c/src/models/currencies.ts
  @planetarium/lib9c/src/models/hashdigest.ts
  @planetarium/lib9c/src/models/networks.ts
  @planetarium/lib9c/tests/actions/claim_items.test.ts
  @planetarium/lib9c/tests/actions/claim_stake_reward.test.ts
  @planetarium/lib9c/tests/actions/common.ts
  @planetarium/lib9c/tests/actions/deliver_to_others_garages.test.ts
  @planetarium/lib9c/tests/actions/fixtures.ts
  @planetarium/lib9c/tests/actions/load_into_my_garages.test.ts
  @planetarium/lib9c/tests/actions/stake.test.ts
  @planetarium/lib9c/tests/actions/transfer_asset.test.ts
  @planetarium/lib9c/tests/actions/transfer_assets.test.ts
  @planetarium/lib9c/tsconfig.json
  @planetarium/lib9c/tsup.config.ts
  @planetarium/lib9c/vite.config.ts
  @planetarium/pnpm-lock.yaml
  @planetarium/pnpm-workspace.yaml
Labels: js

#2561 Correct `@planetarium/lib9c` dev version suffix
  .github/workflows/publish.yml
Labels: bug, ci

#2574 Deprecate dashboard
  .github/workflows/gh-page.yml
  Dashboard/.env.example
  Dashboard/.eslintrc.cjs
  Dashboard/.gitignore
  Dashboard/.prettier.config.js
  Dashboard/README.md
  Dashboard/index.html
  Dashboard/package.json
  Dashboard/postcss.config.js
  Dashboard/src/App.tsx
  Dashboard/src/index.css
  Dashboard/src/main.tsx
  Dashboard/src/vite-env.d.ts
  Dashboard/tailwind.config.js
  Dashboard/tsconfig.json
  Dashboard/tsconfig.node.json
  Dashboard/vite.config.ts
  Dashboard/yarn.lock
Labels: dx, Dashboard

#2568 Fix QuestList.UpdateList
  .Lib9c.Tests/Model/QuestListTest.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Model/Quest/QuestList.cs
Labels: bug

#2571 MVP spec of adventure boss
  .Lib9c.Tests/Action/AdventureBoss/AdventureBossBattleTest.cs
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  .Lib9c.Tests/Action/AdventureBoss/ClaimWantedRewardTest.cs
  .Lib9c.Tests/Action/AdventureBoss/WantedTest.cs
  Lib9c/Action/AdventureBoss/AdventureBossBattle.cs
  Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
  Lib9c/Action/AdventureBoss/ClaimWantedReward.cs
  Lib9c/Action/AdventureBoss/Wanted.cs
  Lib9c/Action/Exceptions/AdventureBoss/ClaimExpiredException.cs
  Lib9c/Action/Exceptions/AdventureBoss/InsufficientStakingException.cs
  Lib9c/Action/Exceptions/AdventureBoss/InvalidAdventureBossSeasonException.cs
  Lib9c/Action/Exceptions/AdventureBoss/InvalidBountyException.cs
  Lib9c/Action/Exceptions/AdventureBoss/MaxInvestmentCountExceededException.cs
  Lib9c/Action/Exceptions/AdventureBoss/PreviousBountyException.cs
  Lib9c/Action/Exceptions/AdventureBoss/SeasonInProgressException.cs
  Lib9c/Addresses.cs
  Lib9c/Model/AdventureBoss/BountyBoard.cs
  Lib9c/Model/AdventureBoss/ExploreInfo.cs
  Lib9c/Model/AdventureBoss/Investor.cs
  Lib9c/Model/AdventureBoss/LatestSeason.cs
  Lib9c/Model/AdventureBoss/SeasonInfo.cs
  Lib9c/Module/AdventureBossModule.cs
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
Labels: enhancement

#2579 Adventure Boss: Wanted
  Lib9c/Action/AdventureBoss/Wanted.cs
Labels: enhancement

#2585 Claim adventure boss reward
  .Lib9c.Tests/Action/AdventureBoss/AdventureBossBattleTest.cs
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  .Lib9c.Tests/Action/AdventureBoss/ClaimWantedRewardTest.cs
  .Lib9c.Tests/Action/AdventureBoss/WantedTest.cs
  Lib9c/Action/AdventureBoss/AdventureBossBattle.cs
  Lib9c/Action/AdventureBoss/Wanted.cs
  Lib9c/Addresses.cs
  Lib9c/Helper/AdventureBossHelper.cs
  Lib9c/Model/AdventureBoss/BountyBoard.cs
  Lib9c/Model/AdventureBoss/ExploreBoard.cs
  Lib9c/Model/AdventureBoss/Explorer.cs
  Lib9c/Model/AdventureBoss/Investor.cs
  Lib9c/Model/AdventureBoss/LatestSeason.cs
  Lib9c/Model/AdventureBoss/SeasonInfo.cs
  Lib9c/Module/AdventureBossModule.cs
Labels: enhancement

#2587 Introduce ClaimAdventureBossReward action
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  .Lib9c.Tests/Action/AdventureBoss/ClaimWantedRewardTest.cs
  Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
  Lib9c/Action/AdventureBoss/ClaimWantedReward.cs
  Lib9c/Action/AdventureBoss/Wanted.cs
  Lib9c/Action/Exceptions/AdventureBoss/AlreadyClaimedException.cs
  Lib9c/Helper/AdventureBossHelper.cs
  Lib9c/Model/AdventureBoss/BountyBoard.cs
  Lib9c/Model/AdventureBoss/Explorer.cs
  Lib9c/Module/AdventureBossModule.cs
Labels: enhancement

#2592 ci: publish @planetarium/lib9c with timestamp
  .github/workflows/publish.yml
Labels: bug, ci, js

#2593 chore: prepare @planetarium/lib9c 0.2.0 pre-releases
  @planetarium/lib9c/jsr.json
  @planetarium/lib9c/package.json
Labels: bug, ci, js

#2590 Claim adventure boss reward
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  .Lib9c.Tests/Action/AdventureBoss/WantedTest.cs
  Lib9c/Action/AdventureBoss/AdventureBossBattle.cs
  Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
  Lib9c/Action/AdventureBoss/Wanted.cs
  Lib9c/Helper/AdventureBossHelper.cs
  Lib9c/Model/AdventureBoss/BountyBoard.cs
  Lib9c/Model/AdventureBoss/ExploreBoard.cs
  Lib9c/Model/AdventureBoss/Explorer.cs
  Lib9c/Module/AdventureBossModule.cs
Labels: enhancement

#2594 Introduce UnlockFloor action
  .Lib9c.Tests/Action/AdventureBoss/UnlockFloorTest.cs
  Lib9c/Action/AdventureBoss/UnlockFloor.cs
  Lib9c/Model/AdventureBoss/Explorer.cs
Labels: enhancement

#2600 Document @planetarium/lib9c
  @planetarium/lib9c/src/actions/claim_items.ts
  @planetarium/lib9c/src/actions/claim_stake_reward.ts
  @planetarium/lib9c/src/actions/common.ts
  @planetarium/lib9c/src/actions/daily_reward.ts
  @planetarium/lib9c/src/actions/deliver_to_others_garages.ts
  @planetarium/lib9c/src/actions/load_into_my_garages.ts
  @planetarium/lib9c/src/actions/stake.ts
  @planetarium/lib9c/src/actions/transfer_asset.ts
  @planetarium/lib9c/src/actions/transfer_assets.ts
  @planetarium/lib9c/src/index.ts
  @planetarium/lib9c/src/models/currencies.ts
  @planetarium/lib9c/src/models/hashdigest.ts
  @planetarium/lib9c/src/models/networks.ts
Labels: js
