Repository planetarium/lib9c, pull requests merged in 2024-04, with the labels that each got.

#2497 Rune multi level up
  .Lib9c.Tests/Action/RuneEnhancementTest.cs
  Lib9c/Action/RuneEnhancement.cs
  Lib9c/Helper/RuneHelper.cs
  Lib9c/Model/State/RuneState.cs
Labels: enhancement, Large

#2503 👻 Restore unity methods
  Lib9c/Action/CreateAvatar.cs
Labels: Extra Small

#2502 Migrate `AvatarState.actionPoint` to use `ActionPointModule`
  .Lib9c.Tests/Action/CancelProductRegistrationTest.cs
  .Lib9c.Tests/Action/ChargeActionPointTest.cs
  .Lib9c.Tests/Action/CombinationConsumableTest.cs
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  .Lib9c.Tests/Action/CreateAvatarTest.cs
  .Lib9c.Tests/Action/EventConsumableItemCraftsTest.cs
  .Lib9c.Tests/Action/GrindingTest.cs
  .Lib9c.Tests/Action/HackAndSlashSweepTest.cs
  .Lib9c.Tests/Action/HackAndSlashTest.cs
  .Lib9c.Tests/Action/ReRegisterProduct0Test.cs
  .Lib9c.Tests/Action/ReRegisterProductTest.cs
  .Lib9c.Tests/Action/RegisterProductTest.cs
  .Lib9c.Tests/Action/Scenario/AuraScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/CollectionScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/MarketScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/WorldUnlockScenarioTest.cs
  .Lib9c.Tests/Action/SellCancellationTest.cs
  .Lib9c.Tests/Helper/InventoryExtensionsTest.cs
  .Lib9c.Tests/Model/State/AvatarStateTest.cs
  Lib9c/Action/CancelProductRegistration.cs
  Lib9c/Action/ChargeActionPoint.cs
  Lib9c/Action/CombinationConsumable.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Action/CreateAvatar.cs
  Lib9c/Action/EventConsumableItemCrafts.cs
  Lib9c/Action/Grinding.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlashSweep.cs
  Lib9c/Action/ItemEnhancement.cs
  Lib9c/Action/ItemEnhancement7.cs
  Lib9c/Action/ReRegisterProduct.cs
  Lib9c/Action/ReRegisterProduct0.cs
  Lib9c/Action/RegisterProduct.cs
  Lib9c/Action/RegisterProduct0.cs
  Lib9c/Helper/InventoryExtensions.cs
  Lib9c/Helper/Validator.cs
  Lib9c/Model/State/AvatarState.cs
  Lib9c/Module/ActionPointModule.cs
Labels: Extra Large

#2509 merge improve/action-execute
  .Lib9c.Tests/Action/CancelProductRegistrationTest.cs
  .Lib9c.Tests/Action/ChargeActionPointTest.cs
  .Lib9c.Tests/Action/CombinationConsumableTest.cs
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  .Lib9c.Tests/Action/CreateAvatarTest.cs
  .Lib9c.Tests/Action/DailyRewardTest.cs
  .Lib9c.Tests/Action/EventConsumableItemCraftsTest.cs
  .Lib9c.Tests/Action/GrindingTest.cs
  .Lib9c.Tests/Action/HackAndSlashSweepTest.cs
  .Lib9c.Tests/Action/HackAndSlashTest.cs
  .Lib9c.Tests/Action/ReRegisterProduct0Test.cs
  .Lib9c.Tests/Action/ReRegisterProductTest.cs
  .Lib9c.Tests/Action/RegisterProductTest.cs
  .Lib9c.Tests/Action/Scenario/AuraScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/CollectionScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/MarketScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/WorldUnlockScenarioTest.cs
  .Lib9c.Tests/Action/SellCancellationTest.cs
  .Lib9c.Tests/Helper/InventoryExtensionsTest.cs
  .Lib9c.Tests/Model/State/AvatarStateTest.cs
  Lib9c/Action/CancelProductRegistration.cs
  Lib9c/Action/ChargeActionPoint.cs
  Lib9c/Action/CombinationConsumable.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Action/CreateAvatar.cs
  Lib9c/Action/DailyReward.cs
  Lib9c/Action/EventConsumableItemCrafts.cs
  Lib9c/Action/Grinding.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlashSweep.cs
  Lib9c/Action/ItemEnhancement.cs
  Lib9c/Action/ItemEnhancement7.cs
  Lib9c/Action/ReRegisterProduct.cs
  Lib9c/Action/ReRegisterProduct0.cs
  Lib9c/Action/RegisterProduct.cs
  Lib9c/Action/RegisterProduct0.cs
  Lib9c/Addresses.cs
  Lib9c/Helper/InventoryExtensions.cs
  Lib9c/Helper/Validator.cs
  Lib9c/Model/State/AvatarState.cs
  Lib9c/Module/ActionPointModule.cs
  Lib9c/Module/DailyRewardModule.cs
Labels: Extra Large

#2508 Fix duplicate collection id
  .Lib9c.Tests/Model/State/CollectionStateTest.cs
  .Lib9c.Tests/Module/CollectionModuleTest.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlashSweep.cs
  Lib9c/Action/Raid.cs
  Lib9c/Model/State/CollectionState.cs
Labels: Extra Small

#2510 Refactor DPoS actions
  .Lib9c.Tests/Action/DPoS/Control/RedelegateCtrlTest.cs
  Lib9c/Action/DPoS/CancelUndelegation.cs
  Lib9c/Action/DPoS/Control/Bond.cs
  Lib9c/Action/DPoS/Control/DelegateCtrl.cs
  Lib9c/Action/DPoS/Control/RedelegateCtrl.cs
  Lib9c/Action/DPoS/Control/UnbondingSetCtrl.cs
  Lib9c/Action/DPoS/Control/UndelegateCtrl.cs
  Lib9c/Action/DPoS/Control/ValidatorCtrl.cs
  Lib9c/Action/DPoS/Control/ValidatorDelegationSetCtrl.cs
  Lib9c/Action/DPoS/Control/ValidatorPowerIndexCtrl.cs
  Lib9c/Action/DPoS/Control/ValidatorRewardsCtrl.cs
  Lib9c/Action/DPoS/Control/ValidatorSetCtrl.cs
  Lib9c/Action/DPoS/Delegate.cs
  Lib9c/Action/DPoS/PromoteValidator.cs
  Lib9c/Action/DPoS/Redelegate.cs
  Lib9c/Action/DPoS/Sys/AllocateReward.cs
  Lib9c/Action/DPoS/Sys/UpdateValidators.cs
  Lib9c/Action/DPoS/Undelegate.cs
  Lib9c/Action/DPoS/Util/DPoSModule.cs
  Lib9c/Action/DPoS/WithdrawDelegator.cs
  Lib9c/Action/DPoS/WithdrawValidator.cs
Labels: Extra Small

#2482 V200160 data
  .Lib9c.Tests/Model/Skill/Adventure/CombatTest.cs
  .Lib9c.Tests/Model/Skill/Arena/ArenaCombatTest.cs
  Lib9c/TableCSV/Character/CharacterLevelSheet.csv
  Lib9c/TableCSV/Character/CharacterSheet.csv
  Lib9c/TableCSV/Cost/EnhancementCostSheetV3.csv
  Lib9c/TableCSV/Item/CostumeItemSheet.csv
  Lib9c/TableCSV/Item/CostumeStatSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemOptionSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemSubRecipeSheetV2.csv
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/DeBuffLimitSheet.csv
  Lib9c/TableCSV/Skill/EnemySkillSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableCSV/WorldAndStage/StageSheet.csv
  Lib9c/TableCSV/WorldAndStage/StageWaveSheet.csv
Labels: Extra Large

#2511 Introduce RuneStateModule
  .Lib9c.Tests/Action/RuneEnhancementTest.cs
  .Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs
  Lib9c/Action/RuneEnhancement.cs
  Lib9c/Addresses.cs
  Lib9c/Model/State/AllRuneState.cs
  Lib9c/Model/State/RuneState.cs
  Lib9c/Module/RuneStateModule.cs
Labels: enhancement, Large

#2521 Refactor decimal places of currency used in dpos.
  .Lib9c.Tests/Action/DPoS/Control/DelegateCtrlTest.cs
  .Lib9c.Tests/Action/DPoS/Control/RedelegateCtrlTest.cs
  .Lib9c.Tests/Action/DPoS/Control/UndelegateCtrlTest.cs
  .Lib9c.Tests/Action/DPoS/Control/ValidatorCtrlTest.cs
  .Lib9c.Tests/Action/DPoS/Control/ValidatorPowerIndexCtrlTest.cs
  .Lib9c.Tests/Action/DPoS/Control/ValidatorSetCtrlTest.cs
  .Lib9c.Tests/Action/DPoS/DistributeTest.cs
  .Lib9c.Tests/Action/DPoS/Model/RedelegationEntryTest.cs
  .Lib9c.Tests/Action/DPoS/Model/UndelegationEntryTest.cs
  .Lib9c.Tests/Action/DPoS/Model/ValidatorPowerTest.cs
  .Lib9c.Tests/Action/DPoS/Model/ValidatorTest.cs
  .Lib9c.Tests/Action/DPoS/PoSTest.cs
  .Lib9c.Tests/Action/DPoS/ValidatorPowerComparerTest.cs
  Lib9c/Action/DPoS/Control/ValidatorCtrl.cs
  Lib9c/Action/DPoS/Misc/Asset.cs
  Lib9c/Action/DPoS/Model/Validator.cs
Labels: Large

#2519 Introduce RuneLevelBonus
  .Lib9c.Tests/Action/RuneEnhancementTest.cs
  .Lib9c.Tests/TableData/Rune/RuneLevelBonusSheetTest.cs
  .Lib9c.Tests/TableData/Rune/RuneListSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlashSweep.cs
  Lib9c/Action/JoinArena.cs
  Lib9c/Action/JoinArena3.cs
  Lib9c/Action/Raid.cs
  Lib9c/Action/RuneEnhancement.cs
  Lib9c/Helper/RuneHelper.cs
  Lib9c/Model/State/AllRuneState.cs
  Lib9c/Model/State/RuneSlotState.cs
  Lib9c/Module/RuneStateModule.cs
  Lib9c/TableCSV/Rune/RuneLevelBonusSheet.csv
  Lib9c/TableCSV/Rune/RuneLevelBonusSheet.csv.meta
  Lib9c/TableCSV/Rune/RuneListSheet.csv
  Lib9c/TableCSV/Rune/RuneListSheet.csv.meta
  Lib9c/TableCSV/RuneListSheet.csv
  Lib9c/TableData/Rune/RuneLevelBonusSheet.cs
  Lib9c/TableData/Rune/RuneListSheet.cs
Labels: enhancement, Large

#2499 Seed should returns value set on instantiation
  .Lib9c.Tests/Action/Common/TestRandom.cs
Labels: bug, Extra Small

#2517 Introduce slashing/jailing for DPoS
  .Lib9c.Tests/Action/DPoS/Control/EvidenceCtrlTest.cs
  .Lib9c.Tests/Action/DPoS/Control/SlashCtrlTest.cs
  .Lib9c.Tests/Action/DPoS/Control/ValidatorCtrlTest.cs
  .Lib9c.Tests/Action/DPoS/Control/ValidatorDelegationSetCtrlTest.cs
  .Lib9c.Tests/Action/DPoS/Control/ValidatorSigningInfoCtrlTest.cs
  .Lib9c.Tests/Action/DPoS/PoSTest.cs
  Lib9c/Action/DPoS/Control/DelegateCtrl.cs
  Lib9c/Action/DPoS/Control/Environment.cs
  Lib9c/Action/DPoS/Control/EvidenceCtrl.cs
  Lib9c/Action/DPoS/Control/RedelegateCtrl.cs
  Lib9c/Action/DPoS/Control/SlashCtrl.cs
  Lib9c/Action/DPoS/Control/UnbondingSetCtrl.cs
  Lib9c/Action/DPoS/Control/UndelegateCtrl.cs
  Lib9c/Action/DPoS/Control/ValidatorCtrl.cs
  Lib9c/Action/DPoS/Control/ValidatorDelegationSetCtrl.cs
  Lib9c/Action/DPoS/Control/ValidatorPowerIndexCtrl.cs
  Lib9c/Action/DPoS/Control/ValidatorRewardsCtrl.cs
  Lib9c/Action/DPoS/Control/ValidatorSetCtrl.cs
  Lib9c/Action/DPoS/Control/ValidatorSigningInfoCtrl.cs
  Lib9c/Action/DPoS/Model/Delegation.cs
  Lib9c/Action/DPoS/Model/Evidence.cs
  Lib9c/Action/DPoS/Model/Infraction.cs
  Lib9c/Action/DPoS/Model/RedelegationEntry.cs
  Lib9c/Action/DPoS/Model/UndelegationEntry.cs
  Lib9c/Action/DPoS/Model/ValidatorSigningInfo.cs
  Lib9c/Action/DPoS/Unjail.cs
  Lib9c/Action/DPoS/Util/DPoSModule.cs
Labels: Extra Large

#2525 Refactor quest serialize type
  .Lib9c.Tests/Action/MigrateAgentAvatarTest.cs
  .Lib9c.Tests/Model/QuestListTest.cs
  .Lib9c.Tests/Util/InitializeUtil.cs
  Lib9c/Action/MigrationAvatarState.cs
  Lib9c/Model/Quest/CollectQuest.cs
  Lib9c/Model/Quest/CombinationEquipmentQuest.cs
  Lib9c/Model/Quest/CombinationQuest.cs
  Lib9c/Model/Quest/GeneralQuest.cs
  Lib9c/Model/Quest/GoldQuest.cs
  Lib9c/Model/Quest/ItemEnhancementQuest.cs
  Lib9c/Model/Quest/ItemGradeQuest.cs
  Lib9c/Model/Quest/ItemTypeCollectQuest.cs
  Lib9c/Model/Quest/MonsterQuest.cs
  Lib9c/Model/Quest/Quest.cs
  Lib9c/Model/Quest/QuestList.cs
  Lib9c/Model/Quest/TradeQuest.cs
  Lib9c/Model/Quest/WorldQuest.cs
  Lib9c/Module/AvatarModule.cs
Labels: Medium

#2524 Introduce rune level bonus
  .Lib9c.DevExtensions.Tests/Action/CreateOrReplaceAvatarTest.cs
  .Lib9c.Tests/Action/RaidTest.cs
  .Lib9c.Tests/Action/RuneEnhancementTest.cs
  .Lib9c.Tests/Action/Scenario/AuraScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs
  .Lib9c.Tests/Battle/CPHelperTest.cs
  .Lib9c.Tests/Model/Arena/PlayerDigestTest.cs
  .Lib9c.Tests/Model/ArenaSimulatorTest.cs
  .Lib9c.Tests/Model/BattleLogTest.cs
  .Lib9c.Tests/Model/PlayerTest.cs
  .Lib9c.Tests/Model/RaidSimulatorV3Test.cs
  .Lib9c.Tests/Model/Rune/AllRuneStateTest.cs
  .Lib9c.Tests/Model/Skill/Adventure/DoubleAttackTest.cs
  .Lib9c.Tests/Model/Skill/Adventure/NormalAttackTest.cs
  .Lib9c.Tests/Model/Skill/Adventure/ShatterStrikeTest.cs
  .Lib9c.Tests/Model/Skill/BuffFactoryTest.cs
  .Lib9c.Tests/Model/Skill/Raid/NormalAttackTest.cs
  .Lib9c.Tests/Model/StageSimulatorTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlashSweep.cs
  Lib9c/Action/Raid.cs
  Lib9c/Action/RuneEnhancement.cs
  Lib9c/Battle/CPHelper.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Extensions/SheetsExtensions.cs
  Lib9c/Helper/RuneHelper.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/ArenaPlayerDigest.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Model/Stat/CharacterStats.cs
  Lib9c/Module/LegacyModule.cs
  Lib9c/Module/RuneStateModule.cs
  Lib9c/TableCSV/Rune/RuneListSheet.csv
  Lib9c/TableData/SimulatorSheets.cs
Labels: enhancement, Extra Large

#2539 Update rune level bonus
  .Lib9c.Tests/Action/RuneEnhancementTest.cs
  .Lib9c.Tests/Action/RuneHelperTest.cs
  .Lib9c.Tests/Model/ArenaSimulatorTest.cs
  Lib9c/Helper/RuneHelper.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Stat/CharacterStats.cs
  Lib9c/TableCSV/Rune/RuneLevelBonusSheet.csv
  Lib9c/TableCSV/Rune/RuneListSheet.csv
Labels: enhancement

#2542 Extend SummonSheet recipe limitation
  .Lib9c.Tests/TableData/Summon/SummonSheetTest.cs
  Lib9c/Action/AuraSummon.cs
  Lib9c/Action/RuneSummon.cs
  Lib9c/TableData/Summon/SummonSheet.cs
Labels: enhancement

#2546 Fix CombinationEquipmentQuest deserialize
  .Lib9c.Tests/Model/QuestListTest.cs
  Lib9c/Model/Quest/CombinationEquipmentQuest.cs
Labels: bug

#2548 Fix missing statCP by rune level bonus
  Lib9c/Action/HackAndSlashSweep.cs
  Lib9c/Action/Raid.cs
  Lib9c/Battle/CPHelper.cs
Labels: bug

#2545 Add limit of crystal from grinding
  .Lib9c.Tests/CrystalCalculatorTest.cs
  Lib9c/Action/Grinding.cs
  Lib9c/Helper/CrystalCalculator.cs
Labels: bug
