Repository planetarium/lib9c, pull requests merged in 2024-11, with the labels that each got.

#2953 Feature/optimization get avatar state
  Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
  Lib9c/Action/AdventureBoss/UnlockFloor.cs
  Lib9c/Action/AdventureBoss/Wanted.cs
  Lib9c/Action/CreateAvatar.cs
Labels: enhancement

#2990 ci: run gh-actions validation every pushing and cron
  .github/workflows/validate-github-actions-workflows.yml
Labels: ci

#2997 ci: prevent to add items without docs
  .github/workflows/lint.yml
  Lib9c.Abstractions/Lib9c.Abstractions.csproj
  Lib9c.Common.ruleset
  Lib9c/Lib9c.csproj
Labels: ci

#3000 Extend Thor Tx. size to 1MiB
  Lib9c.Policy/Policy/MaxTransactionsBytesPolicy.cs
Labels: enhancement

#3016 Update github actions to latest major version
  .github/workflows/lib9c_plugin_build_and_push_s3.yaml
  .github/workflows/main.yml
  .github/workflows/publish.yml
  .github/workflows/release.yaml
Labels: enhancement

#3042 Add account addresses documentations
  docs/articles/system/account.md
  docs/articles/system/toc.yml
Labels: documentation
