Repository planetarium/lib9c, pull requests merged in 2024-02, with the labels that each got.

#2360 Introduce CollectionState, ActivateCollection
  .Lib9c.Tests/Action/ActivateCollectionTest.cs
  .Lib9c.Tests/Model/State/CollectionStateTest.cs
  .Lib9c.Tests/TableData/CollectionSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/ActivateCollection.cs
  Lib9c/Addresses.cs
  Lib9c/Model/Collection/CollectionFactory.cs
  Lib9c/Model/Collection/FungibleCollectionMaterial.cs
  Lib9c/Model/Collection/ICollectionMaterial.cs
  Lib9c/Model/Collection/MaterialType.cs
  Lib9c/Model/Collection/NonFungibleCollectionMaterial.cs
  Lib9c/Model/Item/Inventory.cs
  Lib9c/Model/State/CollectionState.cs
  Lib9c/Module/CollectionModule.cs
  Lib9c/TableCSV/CollectionSheet.csv
  Lib9c/TableData/CollectionSheet.cs
Labels: Large

#2370 Fix legacy BuyProduct SetAvatarState
  Lib9c/Action/BuyProduct.cs
Labels: Extra Small

#2367 Calculate collection stats
  .Lib9c.Tests/Action/Scenario/AuraScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/CollectionScenarioTest.cs
  .Lib9c.Tests/Model/ArenaSimulatorTest.cs
  .Lib9c.Tests/Model/BattleLogTest.cs
  .Lib9c.Tests/Model/PlayerTest.cs
  .Lib9c.Tests/Model/RaidSimulatorV3Test.cs
  .Lib9c.Tests/Model/Skill/NormalAttackTest.cs
  .Lib9c.Tests/Model/StageSimulatorTest.cs
  .Lib9c.Tests/Module/CollectionModuleTest.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/Raid.cs
  Lib9c/Arena/ArenaSimulator.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Model/Stat/CharacterStats.cs
  Lib9c/Module/CollectionModule.cs
Labels: Extra Large

#2372 Collectionsheer draft
  Lib9c/TableCSV/CollectionSheet.csv
Labels: Extra Large

#2373 Fix `UnloadFromMyGarage` action
  .Lib9c.Tests/Action/Garages/UnloadFromMyGaragesTest.cs
  Lib9c/Action/Garages/UnloadFromMyGarages.cs
Labels: Extra Small

#2377 Update maxtransactionpersignerblockpolicy
  Lib9c.Policy/Policy/BlockPolicySource.cs
  Lib9c.Policy/Policy/MaxTransactionsPerSignerPerBlockPolicy.cs
  Lib9c/Planet.cs
Labels: Extra Small

#2375 Rebalancing CharacterStats
  .Lib9c.Tests/Model/PlayerTest.cs
  .Lib9c.Tests/Model/RankingSimulatorTest.cs
  .Lib9c.Tests/Model/RankingSimulatorV1Test.cs
  .Lib9c.Tests/Model/StageSimulatorTest.cs
  .Lib9c.Tests/Model/StageSimulatorV1Test.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Model/Stat/CharacterStats.cs
Labels: Large

#2385 Calculate collection stats cp
  .Lib9c.Tests/Battle/CPHelperTest.cs
  Lib9c/Action/HackAndSlashSweep.cs
  Lib9c/Action/Raid.cs
  Lib9c/Battle/CPHelper.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Model/Stat/CharacterStats.cs
  Lib9c/TableData/Rune/RuneOptionSheet.cs
Labels: Medium

#2386 AvatarState ctor returns null for invalid bencoded values
  Lib9c/Action/Garages/GarageUtils.cs
  Lib9c/Action/MintAssets.cs
  Lib9c/Action/Stake.cs
  Lib9c/Exceptions/StateNullException.cs
  Lib9c/Module/AvatarModule.cs
Labels: Small

#2348 Bump VersionPrefix to 1.8.0
  Lib9c/Lib9c.csproj
Labels: bug, Extra Small

#2391 Fix IncreaseHpForArena
  .Lib9c.Tests/Model/ArenaSimulatorTest.cs
  .Lib9c.Tests/Model/PlayerTest.cs
  .Lib9c.Tests/Model/Skill/BuffFactoryTest.cs
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/Model/Stat/CharacterStats.cs
Labels: Medium

#2392 Apply missing collection modifier in event dungeon
  .Lib9c.Tests/Action/Scenario/CollectionScenarioTest.cs
  Lib9c/Action/EventDungeonBattle.cs
Labels: bug, Small

#2376 Change SPD calculating logic: resolves #2352
  .Lib9c.Tests/Model/ArenaSimulatorTest.cs
  .Lib9c.Tests/Model/RaidSimulatorV3Test.cs
  .Lib9c.Tests/Model/StageSimulatorTest.cs
  Lib9c.Policy/Policy/BlockPolicySource.cs
  Lib9c.Policy/Policy/MaxTransactionsBytesPolicy.cs
  Lib9c.Policy/Policy/MaxTransactionsPerBlockPolicy.cs
  Lib9c.Policy/Policy/MaxTransactionsPerSignerPerBlockPolicy.cs
  Lib9c.Policy/Policy/MinTransactionsPerBlockPolicy.cs
  Lib9c.Policy/Policy/NCBlockPolicy.cs
  Lib9c/Arena/ArenaSimulator.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Lib9c.csproj
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Planet.cs
Labels: enhancement, Large

#2394 Remove unnecessary legacy keys
  .Lib9c.DevExtensions.Tests/Action/Craft/UnlocakCraftActionTest.cs
  .Lib9c.DevExtensions.Tests/Action/ManipulateStateTest.cs
  .Lib9c.DevExtensions.Tests/Action/Stage/ClearStageTest.cs
  .Lib9c.Tests/Action/EventConsumableItemCrafts0Test.cs
  .Lib9c.Tests/Action/EventMaterialItemCrafts0Test.cs
  .Lib9c.Tests/Action/HackAndSlashRandomBuffTest.cs
  .Lib9c.Tests/Action/RuneEnhancementTest.cs
  .Lib9c.Tests/Action/Scenario/AuraScenarioTest.cs
  .Lib9c.Tests/Action/SellTest.cs
  Lib9c.DevExtensions/Action/Craft/UnlockCraftAction.cs
  Lib9c.DevExtensions/Action/CreateArenaDummy.cs
  Lib9c.DevExtensions/Action/CreateTestbed.cs
  Lib9c/Action/Buy.cs
  Lib9c/Action/ChargeActionPoint.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Action/Coupons/RedeemCoupon.cs
  Lib9c/Action/CreateAvatar.cs
  Lib9c/Action/Grinding.cs
  Lib9c/Action/Grinding0.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/ItemEnhancement.cs
  Lib9c/Action/ItemEnhancement10.cs
  Lib9c/Action/ItemEnhancement11.cs
  Lib9c/Action/ItemEnhancement12.cs
  Lib9c/Action/ItemEnhancement13.cs
  Lib9c/Action/ItemEnhancement7.cs
  Lib9c/Action/ItemEnhancement9.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Action/RapidCombination.cs
  Lib9c/Action/RapidCombination5.cs
  Lib9c/Action/RedeemCode.cs
  Lib9c/Action/RedeemCode2.cs
  Lib9c/Action/RuneSummon.cs
  Lib9c/Action/SellCancellation.cs
Labels: Medium

#2395 Update collection material check SkillContains
  .Lib9c.Tests/TableData/CollectionSheetTest.cs
  Lib9c/TableData/CollectionSheet.cs
Labels: Extra Small

#2396 Refactor configure character stats
  .Lib9c.Tests/Model/Skill/BuffFactoryTest.cs
  Lib9c/Arena/ArenaSimulator.cs
  Lib9c/Battle/CPHelper.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Model/Stat/CharacterStats.cs
Labels: Small

#2393 Feature/world 8 focus
  .Lib9c.Tests/Model/Skill/NormalAttackTest.cs
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/Model/Buff/Focus.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Skill/ActionBuffType.cs
  Lib9c/Model/Skill/SkillCategory.cs
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillActionBuffSheet.csv
Labels: enhancement, Medium

#2404 Merge collection system to development
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/ActivateCollectionTest.cs
  .Lib9c.Tests/Action/Scenario/AuraScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/CollectionScenarioTest.cs
  .Lib9c.Tests/Battle/CPHelperTest.cs
  .Lib9c.Tests/Model/ArenaSimulatorTest.cs
  .Lib9c.Tests/Model/BattleLogTest.cs
  .Lib9c.Tests/Model/Collection/FungibleCollectionMaterialTest.cs
  .Lib9c.Tests/Model/Collection/NonFungibleCollectionMaterialTest.cs
  .Lib9c.Tests/Model/Item/InventoryTest.cs
  .Lib9c.Tests/Model/PlayerTest.cs
  .Lib9c.Tests/Model/RaidSimulatorV3Test.cs
  .Lib9c.Tests/Model/RankingSimulatorTest.cs
  .Lib9c.Tests/Model/RankingSimulatorV1Test.cs
  .Lib9c.Tests/Model/Skill/BuffFactoryTest.cs
  .Lib9c.Tests/Model/Skill/NormalAttackTest.cs
  .Lib9c.Tests/Model/StageSimulatorTest.cs
  .Lib9c.Tests/Model/StageSimulatorV1Test.cs
  .Lib9c.Tests/Model/State/CollectionStateTest.cs
  .Lib9c.Tests/Module/CollectionModuleTest.cs
  .Lib9c.Tests/TableData/CollectionSheetTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/ActivateCollection.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlashSweep.cs
  Lib9c/Action/Raid.cs
  Lib9c/Addresses.cs
  Lib9c/Arena/ArenaSimulator.cs
  Lib9c/Battle/CPHelper.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Model/Buff/BuffFactory.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Character/Player.cs
  Lib9c/Model/Collection/CollectionFactory.cs
  Lib9c/Model/Collection/FungibleCollectionMaterial.cs
  Lib9c/Model/Collection/ICollectionMaterial.cs
  Lib9c/Model/Collection/MaterialType.cs
  Lib9c/Model/Collection/NonFungibleCollectionMaterial.cs
  Lib9c/Model/Item/Inventory.cs
  Lib9c/Model/Stat/CharacterStats.cs
  Lib9c/Model/State/CollectionState.cs
  Lib9c/Module/CollectionModule.cs
  Lib9c/TableCSV/CollectionSheet.csv
  Lib9c/TableCSV/CollectionSheet.csv.meta
  Lib9c/TableData/CollectionSheet.cs
  Lib9c/TableData/Rune/RuneOptionSheet.cs
Labels: enhancement, Extra Large

#2410 restore maxtxperblock
  Lib9c.Policy/Policy/BlockPolicySource.cs
Labels: Extra Small

#2406 Fix broken tests
  .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
  _typos.toml
Labels: bug, Large

#2412 Update maxtxblockpolicy
  Lib9c.Policy/Policy/BlockPolicySource.cs
Labels: Extra Small

#2413 Add block index validation to NonFungibleItem
  .Lib9c.Tests/Model/Collection/NonFungibleCollectionMaterialTest.cs
  .Lib9c.Tests/Model/Item/InventoryTest.cs
  Lib9c/Action/ActivateCollection.cs
  Lib9c/Model/Collection/NonFungibleCollectionMaterial.cs
  Lib9c/Model/Item/Inventory.cs
Labels: bug, Extra Small

#2411 🧹 Remove unused actions
  .Lib9c.Tests/Action/AddActivatedAccount0Test.cs
  .Lib9c.Tests/Action/BuyProduct0Test.cs
  .Lib9c.Tests/Action/BuyProductTest.cs
  .Lib9c.Tests/Action/BuyTest.cs
  .Lib9c.Tests/Action/CancelProductRegistration0Test.cs
  .Lib9c.Tests/Action/ChargeActionPoint0Test.cs
  .Lib9c.Tests/Action/ChargeActionPoint2Test.cs
  .Lib9c.Tests/Action/EventConsumableItemCraftsTest.cs
  .Lib9c.Tests/Action/EventMaterialItemCraftsTest.cs
  .Lib9c.Tests/Action/MarketValidationTest.cs
  .Lib9c.Tests/Action/RedeemCode0Test.cs
  .Lib9c.Tests/Action/RegisterProductTest.cs
  .Lib9c.Tests/Action/Scenario/AuraScenarioTest.cs
  .Lib9c.Tests/Action/Scenario/ItemCraftTest.cs
  .Lib9c.Tests/Action/Scenario/MarketScenarioTest.cs
  Lib9c/Action/AddActivatedAccount0.cs
  Lib9c/Action/BuyProduct0.cs
  Lib9c/Action/BuyProduct2.cs
  Lib9c/Action/ChargeActionPoint0.cs
  Lib9c/Action/ChargeActionPoint2.cs
  Lib9c/Action/EventConsumableItemCrafts0.cs
  Lib9c/Action/EventMaterialItemCrafts0.cs
  Lib9c/Action/ReRegisterProduct.cs
  Lib9c/Action/RedeemCode0.cs
  Lib9c/Action/RegisterProduct2.cs
Labels: Extra Large

#2416 Make focus skill works in arena
  .Lib9c.Tests/Model/Skill/Arena/ArenaNormalAttackTest.cs
  Lib9c/Model/Character/ArenaCharacter.cs
Labels: enhancement, Small

#2414 Introduce TwinAttack Skill
  .Lib9c.Tests/Model/Skill/Arena/ArenaDoubleAttackTest.cs
  .Lib9c.Tests/Model/Skill/DoubleAttackTest.cs
  Lib9c/Model/Skill/Arena/ArenaAttackSkill.cs
  Lib9c/Model/Skill/AttackSkill.cs
  Lib9c/Model/Skill/SkillCategory.cs
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableData/Skill/SkillSheet.cs
Labels: enhancement, Medium

#2419 Refactoring CollectionModule
  .Lib9c.Tests/Module/CollectionModuleTest.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Module/CollectionModule.cs
Labels: bug, enhancement

#2427 Fix missing update current hp
  .Lib9c.Tests/Model/ArenaSimulatorTest.cs
  .Lib9c.Tests/Model/PlayerTest.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/Player.cs
Labels: bug, Extra Small

#2428 Release/1.9.1
  .Lib9c.Tests/Model/ArenaSimulatorTest.cs
  .Lib9c.Tests/Model/PlayerTest.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/Player.cs
Labels: Extra Small

#2431 Divide SetRuneStats, RuneSkills for fix rune skill
  .Lib9c.Tests/Model/ArenaSimulatorTest.cs
  .Lib9c.Tests/Model/PlayerTest.cs
  Lib9c/Arena/ArenaSimulatorV4.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/Player.cs
Labels: bug, Medium

#2432 Development back merge 1.9.2
  .Lib9c.Tests/Model/ArenaSimulatorTest.cs
  .Lib9c.Tests/Model/PlayerTest.cs
  Lib9c/Arena/ArenaSimulatorV4.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/Player.cs
Labels: Medium

#2423 🧹 Remove `CombinationEquipment16`
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  .Lib9c.Tests/Action/Scenario/ItemCraftTest.cs
  .Lib9c.Tests/Action/Scenario/Pet/AdditionalOptionRateByFixedValueTest.cs
  .Lib9c.Tests/Action/Scenario/Pet/CommonTest.cs
  .Lib9c.Tests/Action/Scenario/Pet/DiscountMaterialCostCrystalTest.cs
  .Lib9c.Tests/Action/Scenario/Pet/IncreaseBlockPerHourglassTest.cs
  .Lib9c.Tests/Action/Scenario/Pet/ReduceRequiredBlockTest.cs
  Lib9c/Action/CombinationEquipment16.cs
  Lib9c/Action/CombinationEquipment5.cs
Labels: Extra Large

#2434 🧹 Remove duplicated `static` methods
  .Lib9c.Tests/Action/CombinationEquipmentTest.cs
  .Lib9c.Tests/Extensions/EquipmentExtensionsTest.cs
  Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
  Lib9c/Action/AuraSummon.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Action/CombinationEquipment16.cs
Labels: Small
