Repository planetarium/lib9c, pull requests merged in 2024-07, with the labels that each got.

#2663 Add missing BuffLinkSheet to AdventureBossSimulator
  .Lib9c.Tests/Model/AdventureBoss/AdventureBossSimulatorTest.cs
  Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
  Lib9c/Battle/AdventureBoss/AdventureBossSimulator.cs
Labels: bug

#2666 Avoid SerializationException when Exception deserialize
  .Lib9c.Tests/Action/ExceptionTest.cs
  Lib9c/Action/Exceptions/AdventureBoss/AlreadyClaimedException.cs
  Lib9c/Action/Exceptions/AdventureBoss/ClaimExpiredException.cs
  Lib9c/Action/Exceptions/AdventureBoss/InsufficientStakingException.cs
  Lib9c/Action/Exceptions/AdventureBoss/InvalidAdventureBossSeasonException.cs
  Lib9c/Action/Exceptions/AdventureBoss/InvalidBountyException.cs
  Lib9c/Action/Exceptions/AdventureBoss/MaxInvestmentCountExceededException.cs
  Lib9c/Action/Exceptions/AdventureBoss/PreviousBountyException.cs
  Lib9c/Action/Exceptions/AdventureBoss/SeasonInProgressException.cs
  Lib9c/Action/Exceptions/EmptyRewardException.cs
Labels: bug

#2669 Change reward calculating logic from round to floor
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  Lib9c/Helper/AdventureBossHelper.cs
Labels: bug

#2671 Send mail to raffle reward winner
  .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
  .Lib9c.Tests/Model/Mail/AdventureBossRaffleWinnerMailTest.cs
  Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
  Lib9c/Model/Mail/AdventureBossRaffleWinnerMail.cs
  Lib9c/Model/Mail/IMail.cs
  Lib9c/Model/Mail/Mail.cs
Labels: enhancement

#2672 Remove duplicated floor reward
  .Lib9c.Tests/Action/AdventureBoss/ExploreAdventureBossTest.cs
  .Lib9c.Tests/Model/AdventureBoss/AdventureBossSimulatorTest.cs
  Lib9c/Battle/AdventureBoss/AdventureBossSimulator.cs
Labels: bug

#2684 Prepare 1.15.0
  Lib9c/Lib9c.csproj
Labels: bug

#2691 ci(gh-actions): specify working directory
  .github/workflows/main.yml
  .github/workflows/publish.yml
Labels: bug, ci

#2692 ci(gh-actions): bump publish_jsr workflow
  .github/workflows/publish.yml
Labels: ci

#2693 Bump `@planetarium/lib9c` version
  @planetarium/lib9c/jsr.json
  @planetarium/lib9c/package.json
Labels: bug, js

#2702 Deserialize long to long
  Lib9c/Model/AdventureBoss/SeasonInfo.cs
Labels: bug

#2698 Handle divide by zero issue
  Lib9c/Helper/AdventureBossHelper.cs
Labels: bug

#2697 Introduce CustomEquipmentCraft action
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
  Lib9c/Addresses.cs
  Lib9c/Model/Item/Equipment.cs
  Lib9c/Model/State/AvatarState.cs
  Lib9c/Model/State/GameConfigState.cs
  Lib9c/Module/ProficiencyModule.cs
  Lib9c/SerializeKeys.cs
  Lib9c/TableCSV/CustomEquipmentCraft.meta
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftCostSheet.csv
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftCostSheet.csv.meta
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftIconSheet.csv
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftIconSheet.csv.meta
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftOptionSheet.csv
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftOptionSheet.csv.meta
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftProficiencySheet.csv
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftProficiencySheet.csv.meta
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftRecipeSheet.csv
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftRecipeSheet.csv.meta
  Lib9c/TableCSV/GameConfigSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
  Lib9c/TableData/CustomEquipmentCraft/CustomEquipmentCraftCostSheet.cs
  Lib9c/TableData/CustomEquipmentCraft/CustomEquipmentCraftIconSheet.cs
  Lib9c/TableData/CustomEquipmentCraft/CustomEquipmentCraftOptionSheet.cs
  Lib9c/TableData/CustomEquipmentCraft/CustomEquipmentCraftProficiencySheet.cs
  Lib9c/TableData/CustomEquipmentCraft/CustomEquipmentCraftRecipeSheet.cs
Labels: enhancement

#2716 Remove all .Libplanet submodule codeowners
  CODEOWNERS
Labels: suggestion
