Repository planetarium/lib9c, pull requests merged in 2024-03, with the labels that each got.

#2426 ♻️ 🧹 Removed `unlockedOptions` from `AgentState`
  Lib9c/Action/AuraSummon.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Model/State/AgentState.cs
Labels: Extra Small

#2418 Feature/world 8 cheat setting
  Lib9c.DevExtensions/Data/TestbedCreateAvatar.json
  Lib9c/Battle/HitHelper.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/State/AvatarState.cs
  Lib9c/Model/WorldInformation.cs
  Lib9c/TableCSV/Character/CharacterSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemOptionSheet.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableCSV/WorldAndStage/StageSheet.csv
  Lib9c/TableCSV/WorldAndStage/StageWaveSheet.csv
Labels: Large

#2437 ci: variable Lib9c.Plugin S3 path for GitHub Action
  .github/workflows/lib9c_plugin_build_and_push_s3.yaml
Labels: Extra Small

#2439 Introduce MigrateAgentAvatar action
  .Lib9c.Tests/Action/MigrateAgentAvatarTest.cs
  Lib9c/Action/MigrateAgentAvatar.cs
Labels: Large

#2441 release pull development
  .Lib9c.Tests/Action/MigrateAgentAvatarTest.cs
  .github/workflows/lib9c_plugin_build_and_push_s3.yaml
  Lib9c/Action/AuraSummon.cs
  Lib9c/Action/CombinationEquipment.cs
  Lib9c/Action/MigrateAgentAvatar.cs
  Lib9c/Model/State/AgentState.cs
Labels: Large

#2440 Implement NCIP-18
  .Lib9c.Tests/Action/ActionEvaluationTest.cs
  .Lib9c.Tests/Action/RetrieveAvatarAssetsTest.cs
  Lib9c.MessagePack/Action/NCActionEvaluation.cs
  Lib9c/Action/RetrieveAvatarAssets.cs
Labels: enhancement, Medium

#2442 add skillId in arena double attack
  Lib9c/Model/BattleStatus/Arena/ArenaDoubleAttackWithCombo.cs
  Lib9c/Model/BattleStatus/DoubleAttackWithCombo.cs
  Lib9c/Model/IArena.cs
  Lib9c/Model/IStage.cs
  Lib9c/Model/Skill/Arena/ArenaDoubleAttack.cs
  Lib9c/Model/Skill/DoubleAttack.cs
Labels: Extra Small

#2443 Introduce ShatterStrike Skill
  .Lib9c.Tests/Model/Skill/Arena/ArenaShatterStrikeTest.cs
  .Lib9c.Tests/Model/Skill/ShatterStrikeTest.cs
  Lib9c/Model/BattleStatus/Arena/ArenaShatterStrike.cs
  Lib9c/Model/BattleStatus/ShatterStrike.cs
  Lib9c/Model/IArena.cs
  Lib9c/Model/IStage.cs
  Lib9c/Model/Skill/Arena/ArenaAttackSkill.cs
  Lib9c/Model/Skill/Arena/ArenaShatterStrike.cs
  Lib9c/Model/Skill/AttackSkill.cs
  Lib9c/Model/Skill/ShatterStrike.cs
  Lib9c/Model/Skill/SkillCategory.cs
  Lib9c/Model/Skill/SkillFactory.cs
  Lib9c/TableCSV/Skill/SkillSheet.csv
Labels: enhancement, Large

#2447 Feature/world 8 dispel
  Lib9c.DevExtensions/Data/TestbedCreateAvatar.json
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
Labels: Extra Small

#2445 Feature/world 8 add grade
  Lib9c/Model/EnumType/Grade.cs
  Lib9c/TableCSV/Item/EquipmentItemSheet.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
Labels: Small

#2448 Add dispel affect test for arena
  .Lib9c.Tests/Model/Skill/Arena/ArenaCombatTest.cs
  .Lib9c.Tests/Model/Skill/CombatTest.cs
Labels: enhancement, Small

#2452 test data for shatter strike
  Lib9c.DevExtensions/Data/TestbedCreateAvatar.json
  Lib9c/Action/CombinationEquipment5.cs
  Lib9c/TableCSV/Item/EquipmentItemOptionSheet.csv
Labels: Extra Small

#2444 🦺 Restore `HackAndSlashTest.cs`
  .Lib9c.Tests/Action/HackAndSlashTest.cs
Labels: Extra Large

#2461 Remove 🧹 HackAndSlash3
  .Lib9c.Tests/Action/Scenario/WorldUnlockScenarioTest.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlash3.cs
Labels: Large

#2454 Skill updates for world 8
  .Lib9c.Tests/Action/Scenario/WorldUnlockScenarioTest.cs
  .Lib9c.Tests/Model/Skill/Arena/ArenaCombatTest.cs
  .Lib9c.Tests/Model/Skill/Arena/ArenaShatterStrikeTest.cs
  .Lib9c.Tests/Model/Skill/CombatTest.cs
  .Lib9c.Tests/Model/Skill/ShatterStrikeTest.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/HackAndSlash3.cs
  Lib9c/Action/Raid.cs
  Lib9c/Arena/ArenaSimulator.cs
  Lib9c/Arena/ArenaSimulatorV1.cs
  Lib9c/Arena/ArenaSimulatorV2.cs
  Lib9c/Arena/ArenaSimulatorV3.cs
  Lib9c/Arena/ArenaSimulatorV4.cs
  Lib9c/Arena/IArenaSimulator.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/Simulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Skill/Arena/ArenaAttackSkill.cs
  Lib9c/Model/Skill/AttackSkill.cs
  Lib9c/Model/State/GameConfigState.cs
  Lib9c/TableCSV/GameConfigSheet.csv
Labels: enhancement, Extra Large

#2453 Update 8world skill data
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
Labels: Large

#2456 Update 8World Data Update
  Lib9c/TableCSV/Cost/EnhancementCostSheetV3.csv
  Lib9c/TableCSV/Item/ConsumableItemSheet.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
Labels: Large

#2465 Increase UsableApStoneCount
  Lib9c/Action/HackAndSlashSweep.cs
Labels: Extra Small, hardfork

#2468 Hotfix/issue 2467
  .Lib9c.Tests/Action/Scenario/AuraScenarioTest.cs
  .Lib9c.Tests/Model/ArenaSimulatorTest.cs
  .Lib9c.Tests/Model/ArenaSimulatorV1Test.cs
  .Lib9c.Tests/Model/BattleLogTest.cs
  .Lib9c.Tests/Model/CharacterStatsTest.cs
  .Lib9c.Tests/Model/PlayerTest.cs
  .Lib9c.Tests/Model/RaidSimulatorV3Test.cs
  .Lib9c.Tests/Model/Skill/DoubleAttackTest.cs
  .Lib9c.Tests/Model/Skill/NormalAttackTest.cs
  .Lib9c.Tests/Model/Skill/ShatterStrikeTest.cs
  .Lib9c.Tests/Model/StageSimulatorTest.cs
  .Lib9c.Tests/TableSheets.cs
  Lib9c/Action/BattleArena.cs
  Lib9c/Action/EventDungeonBattle.cs
  Lib9c/Action/HackAndSlash.cs
  Lib9c/Action/Raid.cs
  Lib9c/Arena/ArenaSimulator.cs
  Lib9c/Arena/ArenaSimulatorV1.cs
  Lib9c/Arena/ArenaSimulatorV2.cs
  Lib9c/Arena/ArenaSimulatorV3.cs
  Lib9c/Arena/ArenaSimulatorV4.cs
  Lib9c/Arena/IArenaSimulator.cs
  Lib9c/Battle/RaidSimulator.cs
  Lib9c/Battle/Simulator.cs
  Lib9c/Battle/StageSimulator.cs
  Lib9c/Model/Character/ArenaCharacter.cs
  Lib9c/Model/Character/CharacterBase.cs
  Lib9c/Model/Skill/Arena/ArenaAreaAttack.cs
  Lib9c/Model/Skill/Arena/ArenaBlowAttack.cs
  Lib9c/Model/Skill/Arena/ArenaBuffRemovalAttack.cs
  Lib9c/Model/Skill/Arena/ArenaBuffSkill.cs
  Lib9c/Model/Skill/Arena/ArenaDoubleAttack.cs
  Lib9c/Model/Skill/Arena/ArenaHealSkill.cs
  Lib9c/Model/Skill/Arena/ArenaNormalAttack.cs
  Lib9c/Model/Skill/Arena/ArenaShatterStrike.cs
  Lib9c/Model/Skill/Arena/ArenaSkill.cs
  Lib9c/Model/Stat/CharacterStats.cs
  Lib9c/TableCSV/Skill/DeBuffLimitSheet.csv
  Lib9c/TableCSV/Skill/DeBuffLimitSheet.csv.meta
  Lib9c/TableCSV/StakeRegularFixedRewardSheet_V3.csv.meta
  Lib9c/TableCSV/StakeRegularRewardSheet_V6.csv.meta
  Lib9c/TableData/Skill/DeBuffLimitSheet.cs
Labels: Extra Large

#2470 Make Focus skill works on world bass stage
  .Lib9c.Tests/Model/Skill/Adventure/CombatTest.cs
  .Lib9c.Tests/Model/Skill/Adventure/DoubleAttackTest.cs
  .Lib9c.Tests/Model/Skill/Adventure/NormalAttackTest.cs
  .Lib9c.Tests/Model/Skill/Adventure/ShatterStrikeTest.cs
  .Lib9c.Tests/Model/Skill/Raid/NormalAttackTest.cs
  Lib9c/Battle/RaidBoss.cs
Labels: bug, Small

#2474 Fix stat conversion debuff check
  .Lib9c.Tests/Model/Skill/BuffFactoryTest.cs
  Lib9c/Model/Buff/StatBuff.cs
Labels: bug, Small

#2464 ⏪ ♻️ Restore mistakenly removed tests
  .Lib9c.Tests/Action/CombinationConsumableTest.cs
  .Lib9c.Tests/Action/CreateAvatarTest.cs
  .Lib9c.Tests/Action/EventDungeonBattleTest.cs
  .Lib9c.Tests/Action/HackAndSlashSweepTest.cs
  .Lib9c.Tests/Action/ItemEnhancementTest.cs
  .Lib9c.Tests/Action/RaidTest.cs
  .Lib9c.Tests/Action/RapidCombinationTest.cs
  .Lib9c.Tests/Model/Skill/Arena/ArenaCombatTest.cs
  .Lib9c.Tests/Model/Skill/Arena/ArenaShatterStrikeTest.cs
  .Lib9c.Tests/Model/Skill/CombatTest.cs
  .Lib9c.Tests/Model/Skill/ShatterStrikeTest.cs
Labels: Extra Large

#2476 🧹 Removed `DeletedAvatarState`
  Lib9c/Model/State/DeletedAvatarState.cs
Labels: Extra Small

#2475 customize maxtransactionperblock
  Lib9c.Policy/Policy/BlockPolicySource.cs
Labels: Extra Small

#2481 🧹 Remove unused `IAction`s
  .Lib9c.Tests/Action/ActivateAccount0Test.cs
  .Lib9c.Tests/Action/CancelProductRegistrationTest.cs
  .Lib9c.Tests/Action/Coupons/RedeemCouponTest.cs
  .Lib9c.Tests/Action/MarketValidationTest.cs
  .Lib9c.Tests/Action/RuneEnhancement0Test.cs
  .Lib9c.Tests/Action/Scenario/MarketScenarioTest.cs
  .Lib9c.Tests/Action/SellCancellationTest.cs
  .Lib9c.Tests/Action/UnlockEquipmentRecipe1Test.cs
  .Lib9c.Tests/Action/UnlockWorld1Test.cs
  Lib9c/Action/ActivateAccount0.cs
  Lib9c/Action/CancelProductRegistration0.cs
  Lib9c/Action/CreateAvatar.cs
  Lib9c/Action/CreateAvatar0.cs
  Lib9c/Action/ReRegisterProduct.cs
  Lib9c/Action/ReRegisterProduct0.cs
  Lib9c/Action/RuneEnhancement0.cs
  Lib9c/Action/UnlockEquipmentRecipe1.cs
  Lib9c/Action/UnlockWorld1.cs
  Lib9c/Model/ActivationKey.cs
Labels: Extra Large

#2483 🧹 Removed `Grinding0`
  .Lib9c.Tests/Action/Grinding0Test.cs
  Lib9c/Action/Grinding0.cs
Labels: Large

#2485 Removed `SellCancellation7` and `SellCancellation8`
  Lib9c/Action/SellCancellation7.cs
  Lib9c/Action/SellCancellation8.cs
  Lib9c/Extensions/CombinationSlotStateExtensions.cs
Labels: Large

#2488 Add the `type_id` value to pos-related actions.
  Lib9c.DPoS/Action/Sys/CancelUndelegation.cs
  Lib9c.DPoS/Action/Sys/Delegate.cs
  Lib9c.DPoS/Action/Sys/PromoteValidator.cs
  Lib9c.DPoS/Action/Sys/Redelegate.cs
  Lib9c.DPoS/Action/Sys/Undelegate.cs
  Lib9c.DPoS/Action/Sys/WithdrawDelegator.cs
  Lib9c.DPoS/Action/Sys/WithdrawValidator.cs
Labels: Extra Small

#2487 Modify Get methods to take `IWorldState`
  Lib9c.DPoS.Tests/DistributeTest.cs
  Lib9c.DPoS/Action/DPoSModule.cs
  Lib9c.DPoS/Control/AllocateReward.cs
  Lib9c.DPoS/Control/DelegateCtrl.cs
  Lib9c.DPoS/Control/RedelegateCtrl.cs
  Lib9c.DPoS/Control/UnbondingSetCtrl.cs
  Lib9c.DPoS/Control/UndelegateCtrl.cs
  Lib9c.DPoS/Control/ValidatorCtrl.cs
  Lib9c.DPoS/Control/ValidatorDelegationSetCtrl.cs
  Lib9c.DPoS/Control/ValidatorPowerIndexCtrl.cs
  Lib9c.DPoS/Control/ValidatorRewardsCtrl.cs
  Lib9c.DPoS/Control/ValidatorSetCtrl.cs
  Lib9c.DPoS/Model/Validator.cs
  Lib9c.sln.DotSettings
Labels: Small

#2491 Validate collection id already activated
  .Lib9c.Tests/Action/ActivateCollectionTest.cs
  Lib9c/Action/ActivateCollection.cs
Labels: bug, Extra Small

#2495 DailyReward 실행속도 향상
  .Lib9c.Tests/Action/DailyRewardTest.cs
  Lib9c/Action/DailyReward.cs
  Lib9c/Addresses.cs
  Lib9c/Module/ActionPointModule.cs
  Lib9c/Module/DailyRewardModule.cs
Labels: enhancement, Medium
