Repository planetarium/lib9c, pull requests merged in 2024-10, with the labels that each got.

#2866 Update v200230 Data Add
  .Lib9c.Tests/Action/CustomEquipmentCraft/CustomEquipmentCraftTest.cs
  .Lib9c.Tests/Action/GrindingTest.cs
  Lib9c/Helper/CustomCraftHelper.cs
  Lib9c/TableCSV/AdventureBoss/AdventureBossFloorFirstRewardSheet.csv
  Lib9c/TableCSV/Arena/ArenaSheet.csv
  Lib9c/TableCSV/CollectionSheet.csv
  Lib9c/TableCSV/Crystal/CrystalEquipmentGrindingSheet.csv
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftIconSheet.csv
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftOptionSheet.csv
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftRecipeSheet.csv
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftRecipeSkillSheet.csv
  Lib9c/TableCSV/CustomEquipmentCraft/CustomEquipmentCraftRelationshipSheet.csv
  Lib9c/TableCSV/GameConfigSheet.csv
  Lib9c/TableCSV/Item/CostumeStatSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemOptionSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemSheet.csv
  Lib9c/TableCSV/Item/EquipmentItemSubRecipeSheetV2.csv
  Lib9c/TableCSV/Item/ItemRequirementSheet.csv
  Lib9c/TableCSV/Item/MaterialItemSheet.csv
  Lib9c/TableCSV/Item/UnlockCombinationSlotCostSheet.csv
  Lib9c/TableCSV/Skill/ActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillActionBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillBuffSheet.csv
  Lib9c/TableCSV/Skill/SkillSheet.csv
  Lib9c/TableCSV/Skill/StatBuffSheet.csv
  Lib9c/TableCSV/Stake/StakePolicySheet.csv
  Lib9c/TableCSV/StakeRegularRewardSheet_V8.csv
  Lib9c/TableCSV/WorldBoss/WorldBossBattleRewardSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossKillRewardSheet.csv
  Lib9c/TableCSV/WorldBoss/WorldBossRankRewardSheet.csv
  Lib9c/TableCSV/_MaterialFungibleId_2024-08-22.csv
Labels: enhancement

#2883 Renamed all occurrances of SetLegacyState(_, Null) to RemoveLegacyState(_)
  .Lib9c.DevExtensions.Tests/Action/CreateOrReplaceAvatarTest.cs
  .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
  .Lib9c.Tests/Action/EndPledgeTest.cs
  .Lib9c.Tests/Action/Garages/DeliverToOthersGaragesTest.cs
  .Lib9c.Tests/Action/Garages/UnloadFromMyGaragesTest.cs
  .Lib9c.Tests/Action/Scenario/MarketScenarioTest.cs
  .Lib9c.Tests/Action/Stake2Test.cs
  Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
  Lib9c/Action/BuyProduct.cs
  Lib9c/Action/CancelProductRegistration.cs
  Lib9c/Action/EndPledge.cs
  Lib9c/Action/MigrateMonsterCollection.cs
  Lib9c/Action/Stake2.cs
Labels: refactoring

#2934 Add option count
  Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
Labels: bug
